# Character Abilities 

## Ability Scores

Each character will have a score ranging from 6 to 18 in each of the following abilities. A bonus or penalty is associated with each score, as shown on the table below. Each class has a [Prime Requisite](class.qmd#character-classes) ability score, which must be at least 9 for the character to become a member of that class. Additionally, there are required minimum and maximum scores for each character race other than Humans, as described under [Character Races](races.qmd#character-races).


<table style="border-collapse: collapse; width: 50%; margin-left: auto; margin-right: auto;">
  <thead>
    <tr>
     <th style="background-color: lightblue; border: 1px solid black;">Ability Score</th>
     <th style="background-color: lightblue;border: 1px solid black;">Bonus/Penalty</th>
    </tr>
  </thead>
  <tr style="background-color: lightgray; border: 1px solid black;">
    <td style="border: 1px solid black;">3</td>
    <td style="border: 1px solid black;">-3</td>
  </tr>
  <tr style="background-color: lightgray; border: 1px solid black;">
    <td style="border: 1px solid black;">4-5</td>
    <td style="border: 1px solid black;">-2</td>
  </tr>
  <tr style="border: 1px solid black;">
    <td style="border: 1px solid black;">6-8</td>
    <td style="border: 1px solid black;">-1</td>
  </tr>
  <tr style="border: 1px solid black;">
    <td style="border: 1px solid black;">9-12</td>
    <td style="border: 1px solid black;">0</td>
  </tr>
  <tr style="border: 1px solid black;">
    <td style="border: 1px solid black;">13-15</td>
    <td style="border: 1px solid black;">+1</td>
  </tr>
  <tr style="border: 1px solid black;">
    <td style="border: 1px solid black;">16-17</td>
    <td style="border: 1px solid black;">+2</td>
  </tr>
  <tr style="border: 1px solid black;">
    <td style="border: 1px solid black;">18</td>
    <td style="border: 1px solid black;">+3</td>
  </tr>
  <tr style="background-color: lightgray; border: 1px solid black;">
    <td style="border: 1px solid black;">19</td>
    <td style="border: 1px solid black;">+4</td>
  </tr>
  <tr style="background-color: lightgray; border: 1px solid black;">
    <td style="border: 1px solid black;">20</td>
    <td style="border: 1px solid black;">+5</td>
  </tr>
</table>
<br />
**Strength:** This ability measures the character's raw physical power. Strength is the Prime Requisite for [Fighters](class.qmd#fighter). Apply the ability bonus or penalty for Strength to all attack and damage rolls in melee (hand-to-hand) combat. Note that a penalty here will not reduce damage from a successful attack below one point in any case (see the [Combat](combatDetails.qmd#damage) section for details).

**Intelligence:** This is the ability to learn and apply knowledge. Intelligence is the Prime Requisite for [Magic-Users](class.qmd#magic-users), and they receive a Spell Bonus based on their Intelligence score. The ability bonus for Intelligence is added to the number of [languages](abilities.qmd#languages) the character can learn to read and write. Characters with an Intelligence penalty may struggle with learning languages, being limited to understanding only their native language.

**Wisdom:** Wisdom is a combination of intuition, willpower, and common sense. It is the Prime Requisite for [Clerics](class.qmd#cleric), who receive a Spell Bonus and a bonus to Turn Undead based on their Wisdom score. The Wisdom bonus or penalty may apply to some saving throws vs. magical attacks, particularly those affecting the target's will.

**Dexterity:** This ability measures the character's quickness, balance, and aptitude with tools. Dexterity is the Prime Requisite for [Thieves](class.qmd#thief). The Dexterity bonus or penalty applies to all [attack rolls](combatDetails.qmd#attacking-maneuvers) with missile (ranged) weapons, to the character's [Armor Class](equipment.qmd#armor-and-shields) value, and to the character's [Initiative](combatDetails.qmd#initiative) die roll.

**Constitution:** Constitution is a combination of general health and vitality. Apply the Constitution bonus or penalty to each hit die rolled by the character. Note that a penalty here will not reduce any hit die roll to less than 1 point.

**Charisma:** This ability represents the character's ability to influence or lead people. Those with high Charisma are well-liked or highly respected. Apply the Charisma bonus or penalty to reaction rolls. Also, the number of [retainers](hirelings.qmd#retainers) a character can hire and the loyalty of those retainers are affected by Charisma.


#### Stat Roller

```{ojs}
import { rollAbilityScore } from "./custom.js"

viewof statRolls = Inputs.button(html`<button style="color: black; background-color: lightgray;">Roll Stats</button>`, {value: null, reduce: () => [rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore()]})

```


```{ojs}
import { calculateModifier } from "./custom.js"
{
    var x = ""
    if (statRolls != null) {
        x = html`<br><table style="max-width:20%;">
                    <tr>
                        <td>${statRolls[0]}</td>
                        <td>(${calculateModifier(statRolls[0])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[1]}</td>
                        <td>(${calculateModifier(statRolls[1])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[2]}</td>
                        <td>(${calculateModifier(statRolls[2])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[3]}</td>
                        <td>(${calculateModifier(statRolls[3])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[4]}</td>
                        <td>(${calculateModifier(statRolls[4])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[5]}</td>
                        <td>(${calculateModifier(statRolls[5])})</td>
                    </tr>
                `
    } else {x = md`<br><b>Press button to roll stats<b>`}

    return x
    } 

```