# Spells, Alphabetical

<input type="text" id="input" placeholder="Filter Spell">

<div class="spell" data-tag="Alarm" id="Alarm">
## Alarm

Magic-User 1

Range: 20' + 10'/level

Duration: 2 hours/level

Alarm sounds a mental or audible alarm each time any creature larger than a rat enters the warded area or touches it. A creature that speaks the password (determined by the caster at the time of casting) does not set off the alarm. The caster decides at the time of casting whether the alarm will be mental or audible.

Mental Alarm: A mental alarm alerts the caster (and only the caster) so long as the caster remains within 1 mile of the warded area. The caster will hear a single mental “ping” sufficient to awaken the caster from normal sleep, but which does not otherwise disturb concentration. A [Silence](allSpells.html#silence-15-radius) spell has no effect on a mental alarm.

Audible Alarm: An audible alarm produces the sound of a hand bell, and anyone within 60 ft of the warded area can hear it clearly. Interposing doors or walls may reduce the distance by 10 ft or 20 ft. The sound lasts for 1 round. Creatures within a [Silence](allSpells.html#silence-15-radius) spell cannot hear the ringing.

Incorporeal creatures do not trigger the alarm.
</div>

<div class="spell" data-tag="Alter Self" id="Alarm">
## Alter Self

Magic-User 2

Range: Self

Duration: 2 hours/level

When this spell is cast, the wizard can alter their appearance and form--including clothing and equipment--to appear taller or shorter; thin, fat, or in between; human, humanoid, or any other generally man-shaped bipedal creature. The caster's body can undergo a limited physical alteration and their size can be changed up to 50%.

The caster's Hit Points, attack rolls, Armor Class, and saving throws do not change. The spell does not confer special abilities, attack forms, or defenses. Once the new form is chosen, it remains for the duration of the spell. The caster can change back into their own form at will; this ends the spell immediately. A caster who is slain automatically returns to their normal form.
</div>


<div class="spell" data-tag="Analyze Magic" id="Analyze Magic">
## Analyze Magic

Magic-User 2

Range: 5'

Duration: 1 hour/level

This spell permits the caster to discover information about a magic item or a permanently enchanted area. For each turn spent studying the enchanted item or area, the caster may learn one feature of the enchantment. Features include spell effects, bonuses, and command words or activating conditions. The GM will choose the order in which the features are revealed, but command words or activating conditions should be last. Note that the number of charges remaining for a charged item is not revealed by this spell.

Each turn of study requires the caster to make a d20 roll, adding their Intelligence bonus and level. The total result must be 16 or higher to succeed; any failure ends the spell. A natural 1 is always a failure.

The item or area to be studied must be within 5' of the caster for the full duration of scrutiny, and the caster must maintain moderate concentration.
</div>

<div class="spell" data-tag="Animal Friendship" id="Animal Friendship">
## Animal Friendship

Druid 1

Range: 30'

Duration: Permanent

Upon encountering a normal or giant-sized (but not magical) animal, the druid may begin casting this spell, which requires an hour to complete.  During this period the animal will remain nearby, and will not attack the caster or their allies for the duration of the casting (so long as they do not attack or otherwise disturb it).  At the end of the casting, if the animal rolls a successful save vs. Spells, the spell has failed.  At this point the animal acts naturally, without bearing the caster any special ill-will.

If the animal fails its save, it becomes an animal friend and joins the caster for the rest of its natural life, assisting in any way it can.  Both the caster and any other animal friends are treated as treasured partners.  There is no arcane mental connection, nor any particular control, but rather a strong fraternal bond, which should go both ways.  If the animal is treated poorly, or it's love not returned over a period of time, it could attempt another save vs. Spells at the GM's discretion.

A caster may only have, at most, twice their level in hit dice of animal friends.  If this spell is cast on an animal that would put the total above that number, it has no effect.
</div>

<div class="spell" data-tag="Animate Dead" id="Animate Dead">
## Animate Dead
 
Cleric 4, Magic-User 5

Range: Touch

Duration: Special

This spell turns the bones or bodies of dead creatures into undead skeletons or zombies that follow the caster's spoken commands. They remain animated until they are destroyed. The caster may animate a number of hit dice of undead equal to twice his or her caster level, and no more. Animated skeletons have hit dice equal to the number the creature had in life; for skeletons of humans or demi-humans, this means one hit die, regardless of the character level of the deceased. Zombies have one more hit die than the creature had in life. An animated skeleton can be created only from a mostly intact skeleton; a zombie can be created only from a mostly intact corpse. The caster must touch the remains to be animated. No character may normally control more hit dice of undead than 4 times his or her level, regardless of how many times this spell is cast.
</div>

<div class="spell" data-tag="Animate Natural Objects" id="Animate Natural Objects">
## Animate Natural Objects

Druid 6

Range: 100'+10'/level

Duration: 1 round/level

This spell functions identically to the cleric spell [Animate Objects](allSpells.html#animate-objects), but it may only be cast on living trees, plants, or fungi, wooden objects, un-worked stone or earth, or naturally-occurring bodies of water or ice.  At the GM's option other natural phenomena such as non-magical fires or weather effects might also be subject to this spell.
</div>

<div class="spell" data-tag="Animate Objects" id="Animate Objects">
## Animate Objects

Cleric 6

Range: 100'+10'/level

Duration: 1 round/level

This spell imbues inanimate objects with mobility and a semblance of life. The animated objects then attack whomever or whatever the caster designates. This spell cannot animate objects carried or worn by a creature. An animated object can be of any non-magical material. The caster can animate one object per level, up to a maximum of 25 lbs. per caster level (i.e. 300 lbs. at 12th level, 325 lbs. at 13th level, and so on).

The GM must rule on the effectiveness of animated objects in combat. In general, animated objects attack using the same attack bonus as the caster. Small or lightweight objects do no more than 1d4 damage per hit, while larger and/or heavier objects do 1d6 or 1d8 (at the GM's discretion). As a special case, weapons which are animated do damage using the normal die roll for the type, but only up to a maximum 1d8. Animated objects have a movement rate of 10', and generally must move in contact with the ground (walking, hopping, slithering, or bouncing, however seems most appropriate to the GM).
</div>

<div class="spell" data-tag="Animate Tool" id="Animate Tool">
## Animate Tool

Magic-User 0

Range: 10'

Duration: 1 turn/level

A single, small tool (such as a quill pen, spoon, sewing needle, or small hammer) is animated by this cantrip. It will perform a single, repetitive task (such as writing dictated words, stirring a pot of soup, sewing the hem of a dress, or nailing boards into a house) for as long as a turn.

The magic user must be able to perform the repeated action by hand himself. Weapons may not be animated by this cantrip, and objects animated may not be used as weapons.
</div>

<div class="spell" data-tag="Anti-Magic Shell" id="Anti-Magic Shell">
## Anti-Magic Shell

Cleric 7, Druid 7, Magic-user 6

Range: 10' Radius

Duration: 1 turn/level

Within a 10' radius around the caster, all magic is negated for the full duration of the spell.  Magical attacks will not affect the caster, magic items and spells within the radius are suppressed, and the caster cannot perform further magic until the spell has expired.

</div>

<div class="spell" data-tag="Arcane Bolt" id="Arcane Bolt">
## Arcane Bolt

Magic-user 0

Range: 30'

Duration: Instantaneous

This inherent magic is a bolt of raw arcane power. The Magic-User doesn't roll anything, but the target gets a save vs. magic to avoid all damage. The bolt has a range of 30 feet and does 1d4 damage. Since it is pure magic, it will affect creatures, which are only affected by magical weapons, but do not affect inanimate objects.

The **Feat Arcane Bolt, Greater** (Magic User only) improves **Arcane Bolt**. The Target gets a save vs. magic for half damage. The bolt has a range of 40 feet and does 1d6 damage. Since it is pure magic, it will affect creatures, which are only affected by magical weapons. The spell does not affect inanimate objects.
</div>

<div class="spell" data-tag="Assume Animal Form" id="Assume Animal Form">
## Assume Animal Form

Druid 3

Range: Self

Duration: 1 hour/level

This spell allows the caster to change into the form of any natural animal.  The assumed animal form cannot have more hit dice than the caster's level.  If slain, the caster reverts back to their original form.

The caster gains the physical capabilities and statistics of the new form but retains their own mental abilities.  The caster may remain transformed up to one hour per level, or end the spell earlier if the caster so desires.
</div>

<div class="spell" data-tag="Astral Form" id="Astral Form">
## Astral Projection

Cleric 7, Magic-user 7

Range: Self

Duration: Special

This spell frees the caster’s spirit (or soul) from their body, allowing it to travel to another plane. The caster may bring along up to one other creature per two caster levels as long as all participants are linked in a circle when the spell is cast.

The participants’ spirits are immediately transported to the destination plane where they form a new body. This new body will appear to be exactly the same as their original body, but will be acclimated to survive on this new plane. They will also have clothing and equipment identical to they were wearing when the spell was cast, though only exceptional magic items will be duplicated; most magic items will be replaced with normal items. This spell leaves the participants’ original bodies in suspended animation.

This spell will last indefinitely. It will end when the caster chooses to end the spell or the caster's new body dies. In either case, all of the new bodies pop out of existence, and the participants’ spirits return to their original bodies. If a participant other than the caster wills it, or their new body dies, they return on their own, leaving the others behind. If the original body of anyone who is still under the effects of the spell is killed, the character is killed and their new body pops out of existence.

Unlike [Gate](allSpells.html#gate), the destination cannot be the same plane as the plane of origin. Also, astral projection cannot be cast while still in the new body. To go to a different plane, the caster must end the spell, bringing everyone back to their original bodies and cast a new spell from their original bodies.
</div>

<div class="spell" data-tag="Barkskin" id="Barkskin">
## Barkskin

Druid 2, Magic-User 3

Range: Touch

Duration: 4 rounds + 1 round/level

When the **Barkskin** spell is cast upon a creature, its skin becomes as tough as bark, increasing its base Armor Class to AC 17, plus 1 AC for every two levels. Armor Class 18 at 4th level, Armor Class 19 at 6th, Armor Class 20 at 8th and so on.

This spell does not function in combination with normal armor or any magical protection. In addition, saving throw rolls vs. all attack forms except magic gain a +1 bonus. This spell can be placed on the caster or on any other creature the caster touches.
</div>

<div class="spell" data-tag="Bigby's Forceful Hand" id="Bigby's Forceful Hand">
## Bigby's Forceful Hand

Magic-user 6

Range: 10 yards/level

Duration: 1 round/level

**Bigby's Forceful Hand** is a more powerful version of [Bigby's Interposing Hand](allSpells.html#bigbys-interposing-hand). It creates a man-sized (5 feet) to gargantuan-sized (21 feet) hand that places itself between the spellcaster and a chosen opponent. This disembodied hand then moves to remain between the two, regardless of what the spellcaster does or how the opponent tries to get around it. However, the forceful hand also pushes on the opponent. This force can push away a creature weighing 500 pounds or less, slow movement to 10 feet per round if the creature weighs between 500 and 2,000 pounds, or slow movement by 50% if the creature weighs more than 2,000 pounds.

A creature pushed away is pushed to the range limit, or until pressed against an unyielding surface. The hand itself inflicts no damage. The forceful hand has an Armor Class of 18, has as many hit points as its caster in full health, and vanishes when destroyed. The caster can cause it to retreat (to release a trapped opponent, for example) or dismiss it on command.
</div>

<div class="spell" data-tag="Bigby's Grasping Hand" id="Bigby's Grasping Hand">
## Bigby's Grasping Hand

Magic-user 7

Range: 10 yards/level

Duration: 1 round/level

**Bigby's Grasping Hand** is a superior version of the 6th-level spell [Bigby's Forceful Hand](allSpells.html#bigbys-forceful-hand). It creates a man-sized (5 feet) to gargantuan-sized (21 feet) hand that appears and grasps a creature designated by the caster, regardless of what the spellcaster does or how the opponent tries to escape it. The grasping hand can hold motionless a creature or object of up to 1,000 pounds weight, slow movement to 10 feet per round if the creature weighs between 1,000 and 4,000 pounds, or slow movement by 50% if the creature weighs up to 16,000 pounds.

The hand itself inflicts no damage. The grasping hand has an Armor Class of 18, has as many hit points as its caster in full health, and vanishes when destroyed. The caster can order it to release a trapped opponent or can dismiss it on command.
</div>


<div class="spell" data-tag="Bigby's Interposing Hand" id="Bigby's Interposing Hand">
## Bigby's Interposing Hand
 
Magic-User 4

Range: 10 yards/level

Duration: 1 round/level

The **Bigby's Interposing Hand** spell creates a man-sized (5 feet) to gargantuan-sized (21 feet) hand that appears between the spellcaster and their chosen opponent. This disembodied hand then moves to remain between the two, regardless of what the spellcaster does or how the opponent tries to get around it. Neither invisibility nor polymorph fools the hand once a creature has been chosen. The hand does not pursue an opponent.

It provides cover for the caster against the selected opponent, with all the attendant combat adjustments. It has as many hit points as the caster in full health and has an Armor Class of 15.

Any creature weighing less than 2,000 pounds trying to push past the hand is slowed to half its normal movement. If the original opponent is slain, the caster can designate a new opponent for the hand. The caster can command the hand out of existence at any time.
</div>

<div class="spell" data-tag="Black Tentacles" id="Black Tentacles">
## Black Tentacles
 
Black Magic-User 4

Range: 100' + 10'/level

Duration: 1 round/level

A field of 10-foot-long rubbery tentacles will spring from the ground.  The area is up to 30 feet by 30 feet, and they will appear from whatever surface is present, including water.

The tentacles will attack any creature in the area with the intent to wrestle/grapple them. They attack with the caster’s attack bonus and are considered to have a Strength of 18.  There are more than enough tentacles to individually attack as many targets as can be present.  If the attack succeeds, the target is held immobile and takes 1d6 points of damage each round it is held.

Any creature that is not held by a tentacle may still only move through the affected area at half speed.
</div>

<div class="spell" data-tag="Blade Barrier" id="Blade Barrier">
## Blade Barrier

Cleric 6

Range: 90'

Duration: 1 round/level

This spell creates a wall of whirling blades up to 20' long per caster level, or a ringed wall of whirling blades with a radius of up to 5' per two levels. Either form will be up to 20 ft. high (as allowed by available space). Any creature passing through the wall takes 1d6 points of damage per caster level (maximum 15d6), with a save vs. Death Ray reducing damage to half.

If the caster evokes the barrier so that it appears where creatures are, each creature takes damage as if passing through the wall. Each such creature can avoid the wall (ending up on the side of its choice) and thus take no damage by making a successful save vs. Death Ray.

A blade barrier provides cover (+4 bonus to Armor Class) against attacks made through it.
</div>

<div class="spell" data-tag="Bless*" id="Bless*">
## Bless*

Cleric 2

Range: 50' radius

Duration: 1 minute/level

This spell gives the caster and his or her allies (within a 50' radius of the caster) a bonus of +1 on attack rolls, morale checks (for monsters or NPCs allied with the caster), and saving throws against magical [Fear](allSpells.html#remove-fear).

The reverse of **Bless** is called **Bane**. It fills the caster's enemies (within a 50' radius) with fear and doubt, causing each affected creature to suffer a -1 penalty on attack rolls, morale checks, and saving throws against magical [Fear](allSpells.html#remove-fear).
</div>

<div class="spell" data-tag="Blight" id="Blight">
## Blight
 
Black Magic-User 5

Range: Touch

Duration: Instantaneous

This spell withers a single plant of any size.  It causes 1d6 points of damage per level of the caster to the touched plant creature.  The creature is allowed a save vs. Spells for half damage.  If the plant is not a creature, it immediately withers and dies with no saving throw.

Only the touched plant is affected; the spell has no effect on anything else in the area.
</div>

<div class="spell" data-tag="Blink" id="Blink">
## Blink
 
Magic-User 4

Range: Self

Duration: 1 round/level

By means of this spell, the wizard causes their material form to “blink” directly from one point to another at a random time and in a random direction. This means that melee attacks against the wizard automatically miss if initiative indicates they fall after the caster has blinked.

Each round the spell is in effect, the wizard rolls 2d8 to determine the timing of the blink--the result of the dice roll is used as the wizard's initiative for that round. The wizard disappears and instantaneously reappears 10 feet distant from their previous position. (Direction is determined by a roll of 1d8: 1 = right ahead, 2 = right, 3 = right behind, 4 = behind, 5 = left behind, 6 = left, 7 = left ahead, 8 = ahead.) The caster cannot blink into a solid object; if such is indicated, reroll the direction.   If blinking is impossible except into a fixed, solid object, the caster is then trapped on the Ethereal Plane.

During each round that the caster blinks, they can be attacked only by opponents who win initiative or by those who are able to strike both locations at once (for example, with a breath weapon, fireball, or similar wide-area attack forms). Opponents with multiple attacks, or those operating under haste or similar effects, can often strike early enough to have at least one attack against the caster.

If the spellcaster holds off their attack (if any) until after the blink, the 2d8 delay until the blink is added to their normal 1d10 initiative roll (thus, the caster probably attacks last in the round). The spellcaster can also try to get their attack in before the caster blinks (the caster must announce their intent before rolling the 2d8 for blink timing and the 1d10 for initiative).

In this case, the caster compares the two dice rolls, hoping that their initiative roll is lower than their blink roll (the two rolls are not added if the caster is trying to attack before the caster blinks). If so, the caster attacks according to their initiative roll, then blinks according to the blink roll. If their blink roll is lower than their initiative roll, however, the caster blinks first and then attacks in whatever direction the caster's facing (the caster must go through with their attack, even if the caster is facing in the wrong direction to affect anyone).
</div>

<div class="spell" data-tag="Boneskin" id="Boneskin">
## Boneskin

Black Magic-User 2

Range: Self

Duration: 1 turn/level

 The caster manifests a chitinous bone-like armor, giving a +4 bonus to AC. The boney bulk that is added doesn’t affect other spell casting.
 </div>

<div class="spell" data-tag="Burning Hands" id="Burning Hands">
## Burning Hands

Magic-User 1

Range: Special

Duration: 1 round

When the wizard casts this spell, a jet of searing flame shoots from their fingertips. Their hands must be held so as to send forth a fanlike sheet of flames: The wizard's thumbs must touch each other and the fingers must be spread. The burning hands send out flame jets 5 feet long in a horizontal arc of about 120 degrees in front of the wizard.

Any creature in the area of the flames suffers 1d3 points of damage, plus 2 points for each level of experience of the spellcaster, to a maximum of 1d3+20 points of fire damage. Those successfully saving vs. spell receive half damage. Flammable materials touched by the fire burn (for example, cloth, paper, parchment, thin wood, etc.). Such materials can be extinguished in the next round if no other action is taken.
</div>

<div class="spell" data-tag="Call Lightning" id="Call Lightning">
## Call Lightning

Druid 3

Range: 100' + 10'/level

Duration: 1 round/level

Immediately upon completion of the spell, and at most once per round thereafter, the caster may call down a 5 ft wide, 30 ft long vertical bolt of lightning that deals 3d6 points of electricity damage.  The bolt of lightning flashes down in a vertical stroke at whichever target point the caster chooses within the spell’s range (measured from the caster's position at the time of casting).  Any creature in the target area or in the path of the bolt is affected; a successful save vs. Spells reduces damage taken by half.

The caster needs not call a bolt of lightning immediately; other actions, even spellcasting, can be performed.  However, each round after the first the caster may choose to call a bolt instead of taking some other normal action.  The caster may call a total number of bolts equal to one-third of their caster level, rounded down.

If the caster is outdoors and in a stormy area – a rain shower, clouds and wind, hot and cloudy conditions, or even a tornado (including a whirlwind formed by a djinni or an air elemental) – each bolt deals 3d8 points of damage instead of 3d6.

This spell functions only where the open sky is accessible, generally meaning outdoors; bolts may be summoned through windows or skylights at the GM's discretion.
</div>

<div class="spell" data-tag="Call Woodland Beings" id="Call Woodland Beings">
## Call Woodland Beings

Druid 4

Range: 120'

Duration: 1 round/level

This spell summons woodland creatures.  They appear where the caster designates and act immediately, on their turn (they cannot be summoned into an environment that cannot support them).  They attack the caster opponents to the best of their ability.  If the caster can communicate with the creatures, the caster can direct them not to attack, to attack particular enemies or to perform other actions.

The caster may conjure one type of creature from this list, at their option:

- 4 Centaurs,

- 16 Pixies,

- 2 Treants, or

- 4 Unicorns

This spell only works outdoors in a natural location and will not function within the boundaries of any village, town, or city.
</div>

<div class="spell" data-tag="Charm Animal" id="Charm Animal">
## Charm Animal

Cleric 2, Druid 2

Range: 60'

Duration: Level+1d4 rounds

This spell allows the caster to charm one or more animals, in much the same fashion as [Charm Person](allSpells.html#charm-person), at a rate of 1 hit die per caster level. The caster may decide which individual animals out of a mixed group are to be affected first; excess hit dice of effect are ignored. No saving throw is allowed, either for normal or giant-sized animals, but creatures of more fantastic nature (as determined by the GM) are allowed a save vs. Spells to resist. When the duration expires, the animals will resume normal activity immediately.

This spell does not grant the caster any special means of communication with the affected animals; if combined with [Speak With Animals](allSpells.html#speak-with-animals), this spell becomes significantly more useful.
</div>

<div class="spell" data-tag="Charm Monster" id="Charm Monster">
## Charm Monster

Magic-User 4 

Range: 30'

Duration: Special

This spell functions like [Charm Person](allSpells.html#charm-person), except that the effect is not restricted by creature type or size. Undead monsters are unaffected. This spell can affect 3d6 hit dice of creatures of 3 or fewer hit dice, or one creature of more than 3 hit dice. Saving throws are made just as for [Charm Person](allSpells.html#charm-person).
</div>

<div class="spell" data-tag="Charm Person" id="Charm Person">
## Charm Person

Magic-User 1

Range: 30'

Duration: Special

This spell makes a humanoid creature of 4 hit dice or less regard the caster as its trusted friend and ally. Humans and demi-humans may be affected, regardless of level of ability. A save vs. Spells will negate the effect. If the creature is currently being threatened or attacked by the caster or his or her allies, it receives a +5 bonus on its saving throw. The spell does not enable the caster to control the charmed person as if it were an automaton; rather, it perceives his or her words and actions in the most favorable way. The caster can try to give the subject orders, but it will not do anything it wouldn’t ordinarily do, and further may receive an additional saving throw to overcome the magic (at the GM's discretion). The caster must speak the target's language to communicate any commands, or else be good at pantomiming; of course, if the caster is attacked, the charmed creature will act to protect its “friend” (though that could mean attacking the caster's enemies, or attempting to carry off the caster to a “safe” place). The target receives a new saving throw each day if it has an Intelligence of 13 or greater, every week if its Intelligence is 9-12, or every month if its Intelligence is 8 or less.
</div>

<div class="spell" data-tag="Chill" id="Chill">
## Chill

Black Magic-User 1

Range: 10'

Duration: 2 rounds

This spell does 1d4 points of damage to one creature within range.  Furthermore, the creature must save vs. Paralysis or suffer -1 to melee hit and damage rolls for 1d6 rounds.  A large heat source nearby gives a +2 to save.  The caster may use this spell on one target up to 2 rounds after casting.
</div>

<div class="spell" data-tag="Clairaudience" id="Clairaudience">
## Clairaudience
 
Range: 60'

Magic-User 3

Duration: 12 turns

This spell enables the caster to hear sounds in another area through the ears of a living creature in that area. The caster must specify the direction and approximate distance, up to a maximum of 60' away. If there is no appropriate creature in that area, the spell fails. No saving throw is allowed, and the target creature is unaware that it is being so used. The caster may choose another subject creature after at least a turn has passed, enabling multiple locations to be viewed. If the subject creature moves out of range, contact is lost, though the caster may be able to choose another target in this case.
</div>

<div class="spell" data-tag="Clairvoyance" id="Clairvoyance">
## Clairvoyance
 
Range: 60'

Magic-User 3

Duration: 12 turns

This spell enables the caster to see into another area through the eyes of a living creature in that area. The caster must specify the direction and approximate distance, up to a maximum of 60' away. If there is no appropriate creature in that area, the spell fails. No saving throw is allowed, and the target creature is unaware that it is being so used. The caster may choose another subject creature after at least a turn has passed, enabling multiple locations to be viewed. If the subject creature moves out of range, contact is lost, though the caster may be able to choose another target in this case.
</div>

<div class="spell" data-tag="Clean*" id="Clean*">
## Clean*

Magic-User 0

Range: 30'

Duration: Instananeous

A mage making use of this cantrip may clean, shine, dust, or polish a small object or surface of up to 1 square foot. Reversed, this becomes **Dirty**, which can make the same area dirty, tarnished, scuffed, or dusty.
</div>

<div class="spell" data-tag="Cloudkill" id="Cloudkill">
## Cloudkill
 
Magic-User 5

Range: 100'+10'/level

Duration: 6 rounds/level

This spell creates a 20'x20'x20' cloud of poison gas which moves at a rate of 10' per round under the control of the caster (so long as he or she concentrates on it). The gas kills outright any creatures of 3 or fewer hit dice or levels it comes in contact with; creatures having 4 or more hit dice or levels must save vs. Poison or die. The cloud persists for the entire duration even if the caster ceases to concentrate upon it.
</div>

<div class="spell" data-tag="Command" id="Command">
## Command

Cleric 1

Range: 10'

Duration: 1 round

The caster speaks a single-word command, which will be obeyed by a single creature within the given range. The command must be given in a language the recipient understands. The recipient will do its best to obey, as long as the command is a clear, imperative verb. "Suicide" isn't a verb. "Die" would cause the recipient to fake death for the duration of the spell (believing it was dead). Typical commands are back, halt, flee, run, stop, fall, fly, go, leave, surrender, sleep, rest, etc.

Undead are not affected. Creatures with Intelligence of 13 or more and creatures with 6 or more hit dice may save vs. Spells to resist.
</div>

<div class="spell" data-tag="Command Undead" id="Command Undead">
## Command Undead

Black Magic-User 2

Range: 30'

Duration: Special

This spell allows the caster to influence an undead creature.  If the undead creature is intelligent, this spell operates as charm person, except that the caster can influence 2 HD per caster level, instead of just a flat 4 HD.  It otherwise operates the same, including duration.

If the undead creature is unintelligent, the caster immediately gains complete control, the creature gets no saving throw, and the duration is permanent.  Any unintelligent undead controlled using this spell count against the total control limit from re-animation.
</div>

<div class="spell" data-tag="Commune" id="Commune">
## Commune

Cleric 5

Range: Self

Duration: 1 round/level

This spell puts the caster in contact with his patron deity or an extraplanar servant thereof, who answers one yes-or-no question per caster level. The ritual to cast this spell takes 1 turn to complete. The being contacted may or may not be omniscient, and further, though the being is technically allied with the caster, it may still not answer questions clearly or completely. These details are left to the GM's discretion.
</div>

<div class="spell" data-tag="Commune With Nature" id="Commune With Nature">
## Commune Wtih Nature

Druid 5

Range: See text

Duration: Instantaneous

The caster becomes one with nature, attaining knowledge of the surrounding territory.  After 10 minutes of concentration, the caster instantly gains knowledge of one fact per caster level among the following subjects: the ground or terrain, plants, minerals, bodies of water, people, general animal population, presence of woodland creatures, presence of powerful unnatural creatures, presence of settlement or structure, or even the general state of the natural setting.

In outdoor settings, the spell operates in a radius of 1 mile per caster level.  In natural underground settings – caves, caverns, and the like – the radius is limited to 100 ft per caster level.  The spell does not function where nature has been replaced by construction or settlement, such as in dungeons and towns.
</div>

<div class="spell" data-tag="Confusion" id="Confusion">
## Confusion

Magic-User 4

Range: 360'

Duration: 2 rounds+1/level

This spell causes up to 3d6 living creatures within a 30' radius circle around the target point to become confused*,*making them unable to independently determine what they will do. A saving throw vs. Spells is allowed to resist the effect. Roll on the following table on each subject's Initiative number each round to see what the subject does.

::: {#confusion-table}

| d20 | Behavior |
|-----|------------|
| 1--2 | Attack caster with melee or ranged weapons (or close with caster if attack is not possible). |
| 3--4 | Act normally. |
| 5--10 | Do nothing but babble incoherently. |
| 11--14 | Flee away from caster at top possible speed. |
| 15--20 | Attack nearest creature. |
:::

<div style="display: flex; justify-content: center;">
```{ojs}

import {confusionTable, highlightTableRow} from "./custom.js"

viewof gemJewel3 = Inputs.button(html`<button style="color: back; background-color: lightgray;">Roll on Table</button>`, {value: 0, reduce: () => highlightTableRow("#confusion-table", confusionTable())})

```
</div>

A confused character who can't carry out the indicated action does nothing but babble incoherently. Attackers are not at any special advantage when attacking a confused character. Any confused character who is attacked automatically retaliates on its next turn, as long as it is still confused when its turn comes.
</div>

<div class="spell" data-tag="Conjure Elemental" id="Conjure Elemental">
## Conjure Elemental
 
Druid, Magic-User 5

Range: 240'

Duration: Special

A portal to one of the Elemental Planes of Air, Earth, Fire, or Water is opened, allowing the Magic-User to summon an elemental from that plane. At most one elemental of each type may be summoned by the caster in a given day. Once the elemental appears, it serves the conjurer indefinitely, provided the caster concentrates on nothing but controlling the creature; spell casting, combat, or movement over half the normal rate results in loss of concentration. The conjurer, while in control of an elemental, can dismiss it to its native plane at will (doing so on his or her Initiative if in combat). If the Magic-User loses concentration, control of the summoned Elemental is lost and cannot be regained. The creature then seeks to attack the conjurer and all others in its path. Only [Dispel Magic](allSpells.html#dispel-magic) or [Dispel Evil](allSpells.html#dispel-evil) will banish the elemental once control has been lost. An elemental may, of course, choose to return to its home plane on its own; such creatures will not choose to remain on the material plane for long.
</div>

<div class="spell" data-tag="Continual Light*" id="Continual Light*">
## Continual Light*

Cleric 3, Magic-User 2

Range: 360'

Duration: 1 year/level

This spell creates a spherical region of light, as bright as full daylight up to a 30' radius, with light of lesser intensity to a radius of 60'. Continual light can be cast on an object, into the air, or at a creature, just as with the [Light](allSpells.html#light) spell, up to a maximum range of 360' from the caster. The spell remains in effect for one year per level of the caster.

As with [Light](allSpells.html#light), this spell can be used to blind a creature if cast on its visual organs. Creatures targeted by this spell are allowed a save vs. Death Ray; if the save is made, the spell is cast into the air just behind the target creature. A penalty of -4 is applied to the blinded creature's attack rolls if the saving throw fails.

The reversed spell, **Continual Darkness**, causes complete absence of light in the area of effect, overpowering normal light sources. Continual darkness may be used to blind in the same way as continual light.
</div>

<div class="spell" data-tag="Control Temperature, 10' Radius" id="Control Temperature, 10' Radius">
## Control Temperature, 10' Radius

Druid 4

Range: 0'

Duration: 1 hour/level

The caster can change automatically the surrounding temperature (10 ft radius sphere) by up to 10 degrees Fahrenheit per caster level.  The change can be upward or downward (caster’s choice)
</div>

<div class="spell" data-tag="Control Undead" id="Control Undead">
## Control Undead

Cleric 6, Black Magic-User 6

Range: 60'

Duration: 6 round/level

This spell allows for complete control of up to 3 HD/caster level of undead for a short period of time. Verbal control is required, but they will understand regardless of the language used. If communication is not possible, they will still not attack. Intelligent undead creatures may save vs. Spells to resist and will remember if they are controlled. Unintelligent undead do not get a saving throw and the control is permanent. Any unintelligent undead controlled using this spell count against the caster’s total control limit [Re-animation](allSpells.html#re-animation).
</div>

<div class="spell" data-tag="Control Weather" id="Control Weather">
## Control Weather

Cleric 7, Druid 7

Range: 2 miles

Duration: 4d12 hours

The caster can change the weather in the local area. Any kind of weather appropriate to the climate and season of the area may be invoked. It takes 10 minutes for the weather to change to the desired conditions. For the duration of the spell, the caster may again change the conditions, but any such change will take another 10 minutes for the new conditions to arrive.

The caster has control over the general conditions of the weather, such as the direction and force of the winds, whether lightning is occurring, whether there is a tornado, and other directives. But, there is no specific control, so lightning cannot be forced to hit a particular spot and the path of a tornado cannot be dictated.

The spell allows the caster to remove conditions as well as bring them. (For example, an existing tornado can be replaced with calm weather.) At the end of the spell, the current conditions will continue, the caster just won’t be able to control them anymore.
</div>

<div class="spell" data-tag="Corpse Feast" id="Corpse Feast">
## Corpse Feast
 
Black Magic-User 4

Range: 5'/level

Duration: Instantaneous

This spell heals the caster and nearby active undead beings by draining the last energies from any fresh corpses (no more than an hour old) within the spell range.  The corpse must have been a living sentient being (i.e. not animal, undead, construct, elemental, etc). 

Any corpse drained using this spell provides vigor to the caster and their active undead allies within range, healing 1d4 hit points per corpse, up to their maximum.  Slain or destroyed undead do not heal or rise anew.  Any corpses consumed by this spell cannot be raised or resurrected.
</div>

<div class="spell" data-tag="Corpse Servant" id="Corpse Servant">
## Corpse Servant

Black Magic-User 1

Range: Touch

Duration: 1 hour/level

This spell allows the caster to temporarily animate skeletons or zombies.  A number of hit dice equal to the caster's level may be animated for up to one hour per caster level.  These non-permanent undead do not count towards the [Re-animation](allSpells.html#re-animation) spell limitations, but they otherwise conform to the permanent undead created by that spell.  Only one instance of this spell may be active at a time for any particular caster.

Animated skeletons have hit dice equal to the number the creature had in life; for skeletons of humans or demi-humans, this means one hit die, regardless of the character level of the deceased.  Zombies have one more hit die than the creature had in life.  An animated skeleton can be created only from a mostly intact skeleton; a zombie can be created only from a mostly intact corpse.  The caster must touch the remains to be animated.
</div>

<div class="spell" data-tag="Create Food" id="Create Food">
Cleric 5

Range: 10'

Duration: Permanent

The food that this spell creates is simple fare of the caster's choice, highly nourishing, but rather bland. Up to 3 men or one horse per caster level can be fed for one day with this spell. Food so created decays and becomes inedible within 24 hours, although it can be kept fresh for another 24 hours by casting [Purify Food and Water](allSpells.html#purify-food-and-water) on it.
</div>


<div class="spell" data-tag="Create Water" id="Create Water">
## Create Water

Cleric 4

Range: 10'

Duration: Permanent

This spell creates one gallon of water per caster level. Note that one or more vessels to contain the water must be available at the time of casting. The water created by this spell is just like clean rain water. Note: Water weighs about 8 pounds per gallon, and one cubic foot of water is roughly 8 gallons.
</div>

<div class="spell" data-tag="Cure Blindness*" id="Cure Blindness*">
## Cure Blindness*

Cleric 3

Range: Touch

Duration: Instantaneous

With this spell the caster can cure a creature suffering blindness (whether caused by injury or by magic, including [Light](allSpells.html#light) or [Continual Light](allSpells.html#continual-light)). Blindness caused by a curse cannot be cured by this spell.

Reversed, this spell becomes **Cause Blindness**, which causes a living creature touched to become blind. A successful melee attack roll is required to touch the
victim, and no Saving Throw is allowed. Blinded creatures suffer the penalties described in [Deafness and Blindness](combat.qmd#deafness-and-blindness).
</div>

<div class="spell" data-tag="Cure Deafness*" id="Cure Deafness*">
## Cure Deafness*

Cleric 3

Range: Touch

Duration: Instantaneous

With this spell the caster can cure a creature suffering deafneass (whether caused by injury or by magic, including **Cause Deafness**). Blindness caused by a curse cannot be cured by this spell.

Reversed, this spell becomes **Cause Deafness**, which causes a living creature touched to become deaf. A successful melee attack roll is required to touch the
victim, and no Saving Throw is allowed. Deafened creatures suffer the penalties described in [Deafness and Blindness](combat.qmd#deafness-and-blindness).
</div>

<div class="spell" data-tag="Cure Disease*" id="Cure Disease*">
## Cure Disease*

Cleric 3, Druid 3

Range: Touch

Duration: Instantaneous

Cure disease cures all diseases that the subject is suffering from. The spell also kills parasites afflicting the target creature. Certain special diseases may not be countered by this spell or may be countered only by a caster of a certain level or higher.

Note: This spell does not prevent reinfection after a new exposure to the same disease.

The reverse spell **Cause Disease** infects the target creature with a debilitating disease, causing it to suffer from symptoms such as fever, weakness, or nausea. The affected creature must make a saving throw to resist the disease's effects. On a failed save, the creature suffers ongoing damage and penalties to its abilities until the disease is cured. The exact effects of the disease and the duration of its affliction can vary depending on the caster's level and the discretion of the Game Master.
</div>

<div class="spell" data-tag="Cure Light Wounds*" id="Cure Light Wounds*">
## Cure Light Wounds*

Cleric 1, Druid 1

Range: Touch

Duration: Instantaneous

With this spell the caster heals 1d6+1 hit points of damage by laying his or her hand upon the injured creature.

The reverse form of this spell, **Cause Light Wounds**, causes 1d6+1 damage to the creature affected by it. A successful attack roll is required in this case.

Undead are affected by this spell and its reverse in opposite fashion; they are injured by **Cure Light Wounds** and healed by **Cause Light Wounds**.
</div>

<div class="spell" data-tag="Cure Minor Wounds*" id="Cure Minor Wounds*">
## Cure Minor Wounds*

Cleric 0, Druid 0

Range: Touch

Duration: Instantaneous

With this spell the caster heals 1 hit points of damage by laying his or her hand upon the injured creature.

The reverse form of this spell, **Cause Minor Wounds**, causes 1 damage to the creature affected by it. A successful attack roll is required in this case.

Undead are affected by this spell and its reverse in opposite fashion; they are injured by **Cure Minor Wounds** and healed by **Cause Minor Wounds**.
</div>

<div class="spell" data-tag="Cure Serious Wounds*" id="Cure Serious Wounds*">
## Cure Serious Wounds*
Cleric 4, Druid 4

Range: Touch

Duration: Instantaneous

This spell works exactly like [Cure Light Wounds](allSpells.html#cure-light-wounds), save that it heals 2d6 points of damage, plus 1 point per caster level. The reverse, **Cause Serious Wounds**, also works exactly like [Cause Light Wounds](allSpells.html#cure-light-wounds), except that it inflicts 2d6 + caster level in damage.
</div>

<div class="spell" data-tag="Dancing Lights" id="Dancing Light">
## Dancing Lights

Magic-User 0

Range: 100' + 10'/level

Duration: Instananeous

Depending on the version selected, you create up to four lights that resemble lanterns or torches (and cast that amount of light), or up to four glowing spheres of light (which look like will-o’-wisps), or one faintly glowing, vaguely humanoid shape. The dancing lights must stay within a 10-foot-radius area in relation to each other but otherwise move as you desire (no concentration required): forward or back, up or down, straight or turning corners, or the like. The lights can move up to 100 feet per round. A light winks out if the distance between you and it exceeds the spell’s range.

Dancing lights can be made permanent with a [Permanency](allSpells.html#permanency) spell.
</div>

<div class="spell" data-tag="Dark Flame" id="Dark Flame">
## Dark Flame

Black Magic-User 2

Range: Touch

Duration: 1 turn/level

The caster produces a magical “dark flame” upon an object that does not produce heat or use oxygen. However, the magical dark flames allow all within 30 feet radius to see via Darkvision within the spell area, much like a normal lit torchwould allow for normal vision. The darkvision does not extend beyond the spell radius, and neither does the effect extend to any who might leave the area of effect. The spell does not provide any stealth bonus within the effect, as all (including foes) receive the darkvision.     However, because there is no light produced it may augment stealthy movement in general against those outside the spell range.
</div>


<div class="spell" data-tag="Darkvision" id="Darkvision">
## Darkvision

Magic-User 3

Range: Touch

Duration: 1 hour/level

The subject receives Darkvision with a range of 60' for the duration of the spell. See [here](dungeonAdventures.html#darkvision) for a description of Darkvision.
</div>

<div class="spell" data-tag="Death Spell" id="Death Spell">
## Death Spell
 
Magic-User 6

Range: 240'

Duration: Instantaneous

This spell will kill 3d12 hit dice or levels of creatures in a 30' radius sphere centered wherever the caster wishes (within the range limit). Excess levels of effectiveness are lost. Each creature affected is allowed to save vs. Death Ray; those that fail the save die immediately. Creatures of 8 or more hit dice or levels are immune to the spell, as are undead monsters, golems, and any other “creature” that is not truly alive.
</div>

<div class="spell" data-tag="Decay Flesh" id="Decay Flesh">
## Decay Flesh

Black Magic-User 1

Range: Touch

Duration: Instantaneous

This is a version of the [Cause Light Wounds](allSpells.html#cure-light-wounds) spell dealing 1d6+1 points of damage to the creature affected by it.  The caster must make a successful attack to inflict the damage.  A missed attack roll does not dispel the effect, as it can be active until used or until a number of rounds equal to the caster's level have passed.

Unlike the Clerical spell mentioned, this spell may not be reversed.  However, this spell does work upon undead creatures in the opposite fashion; they are healed 1d6+1 hit points instead.
</div>

<div class="spell" data-tag="Delayed Blast Fireball" id="Delayed Blase Fireball">
## Delayed Blast Fireball

Magic-user 7

Range: 100' + 10'/level

Duration: Special

This spell creates a small glowing bead at any location chosen by the caster, up to the listed range. This bead will explode in an improved form of fireball at a time chosen by the caster; when it explodes, it will do 1d6+1 points of damage per caster level to all within a spherical volume with a 20' radius, just as with the standard fireball spell. The bead may explode immediately if the caster so desires, or may be delayed up to 10 rounds; the caster chooses the time when the spell is cast, and cannot subsequently be changed.

If a delay is chosen, the glowing bead lies at its destination until it detonates. A creature can pick up and hurl the bead (with the same range as a dagger); if the bead is handled within 1 round of its scheduled detonation, there is a 25% chance that the bead detonates instantly, i.e. before it can be thrown.
</div>

<div class="spell" data-tag="Designor’s Wind Mastery" id="Designor’s Wind Mastery">
## Designor’s Wind Mastery
 
Druid 4, Magic-User 5

Range: 0'

Duration: 1 turn/level

The caster alters wind force around them (40 ft per caster level radius cylinder 40 ft high).  The caster can make the wind blow in a certain direction or manner, increase its strength, or decrease its strength.  The new wind direction and strength persist until the spell ends or until the caster chooses to alter it, which requires concentration.  The caster may create an “eye” of calm air up to 40 ft radius around them and may choose to limit the area of effect to any cylindrical area less than their full limit.

The caster may choose wind patterns over the spell’s area.  The caster can choose a downdraft blows from the center outward, an updraft blows from the outer edges in toward the center, a rotation that causes the winds to circle the center or a blast that simply causes the winds to blow in one direction across the entire area from one side to the other.

For every three caster levels, the caster can increase or decrease wind condition by one level.
</div>

<div class="spell" data-tag="Detect Evil*" id="Detect Evil*">
## Detect Evil*

Cleric 1, Magic-User 2

Range: 60'

Duration: 1 round/level

This spell allows the caster to detect evil; specifically, the caster can detect creatures with evil intentions, magic items with evil enchantments, and possibly extraplanar creatures of evil nature. Normal characters, even “bad” characters, cannot be detected by this spell, as only overwhelming evil is detectable. The caster sees the “evil” creatures or objects with a definite glow around them, but the glow cannot be seen by anyone else.

The exact definition of evil is left for the GM to decide. Note that items such as ordinary traps or poisons are not “evil,” and thus not detectable by this spell.

Reversed, this spell becomes **Detect Good**, which works just as described above with respect to detecting “good” enchantments, angelic creatures, and so on.
</div>

<div class="spell" data-tag="Detect Invisible" id="Detect Invisible">
## Detect Invisible
 
Magic-User 2

Range: 60'

Duration: 1 turn/level

By means of this spell the caster is able to see invisible characters, creatures or objects within the given range, seeing them as translucent shapes.
</div>

<div class="spell" data-tag="Detect Magic" id="Detect Magic">
## Detect Magic

Cleric 1, Druid 1, Magic-User 1

Range: 60'

Duration: 2 turns

The caster of this spell is able to detect enchanted or enspelled objects or creatures within the given range by sight, seeing them surrounded by a pale glowing light. Only the caster sees the glow. Invisible creatures or objects are not detected by this spell, but the emanations of the invisibility magic will be seen as an amorphous glowing fog, possibly allowing the caster (only) to attack the invisible creature at an attack penalty of only -2.

</div>

<div class="spell" data-tag="Detect Poison" id="Detect Poison">
## Detect Poison

Cleric 1, Druid 1

Range: 1'

Duration: 1 turn + 1 round/level

This spell enables the priest to determine if an object has been poisoned or is poisonous. One object, or one 5-foot cubic mass, can be checked per round. The priest has a 5% chance per level of determining the exact type of poison.
</div>

<div class="spell" data-tag="Detect Scrying" id="Detect Scrying">
## Detect Scrying
 
Magic-User 4

Range: Self

Duration: 1d6 turns + 1 turn/leve1

By means of this spell, the wizard immediately becomes aware of any attempt to observe them by means of [Clairvoyance](allSpells.html#clairvoyance), [Clairaudience](allSpells.html#clairaudience), or [Magic Mirror](allSpells.html#magic-mirror). This also reveals the use of **Crystal Balls** or other magical scrying devices, provided the attempt is within the area of effect of the spell. Since the spell is centered on the spellcaster, it moves with him, enabling him to “sweep” areas for the duration of the spell.

When a scrying attempt is detected, the scryer must immediately roll a saving throw. If this is failed, the wizard who cast this spell immediately knows the identity and general location of the scryer. The general location is a direction and significant landmark close to the scryer. Thus, the caster might learn, “The wizard Sniggel spies on us from east, under the stairs,” or, “You are watched by Asquil in the city of Samarquol.”
</div>

<div class="spell" data-tag="Detect Snares and Pits" id="Detect Snares and Pits">
## Detect Snares and Pits

Druid 1

Range: 60'

Duration: 10 turns

By means of this spell, the caster can detect simple pits, deadfalls, and snares as well as mechanical traps constructed of natural materials.  The spell does not detect complex traps, including trapdoor traps.

This spell does detect certain natural hazards, for instance quicksand (detected as a snare), a sinkhole (a pit), or unsafe walls of natural rock (a deadfall).  However, it does not reveal other potentially dangerous conditions.  The spell does not detect magic traps (except those that operate by pit, deadfall, or snaring), nor mechanically complex ones, nor those that have been rendered safe or inactive.

The amount of information revealed depends on how long the Druid studies a particular area.

* 1st Round: Presence or absence of hazards.

* 2nd Round: Number of hazards and the location of each.  If a hazard is outside the Druid's line of sight, then the caster discern its direction but not its exact location.

* Each Additional Round: The general type and trigger for one particular hazard closely examined by the caster.

Each round, the Druid can turn to detect snares and pits in a new area.  The spell can penetrate barriers, but 1 ft of stone, 1 in of common metal, a thin sheet of lead, or 3 ft of wood or dirt blocks it.
</div>

<div class="spell" data-tag="Dig" id="Dig">
## Dig

Druid 5, Magic-User 4

Range: 30 yards

Duration: 1 rd/level

A **Dig** spell enables the caster to excavate 125 cubic feet of earth, sand, or mud per round (i.e., a cubic hole 5 feet on a side). In later rounds the caster can expand an existing hole or start a new one. The material thrown from the excavation scatters evenly around the pit. If the wizard continues downward past 20 feet in earth, there is a 15% chance that the pit collapses. This check is made for every 5 feet dug beyond 20 feet. Sand tends to collapse after 10 feet, mud fills in and collapses after 5 feet, and quicksand fills in as rapidly as it is dug.

Any creature at the edge (within 1 foot) of a pit must roll a successful Dexterity check or fall into the hole. Creatures moving rapidly toward a pit dug immediately before them must roll a saving throw vs. spell to avoid falling in. Any creature in a pit being excavated can climb out at a rate decided by the DM. A creature caught in a collapsing pit must roll a saving throw vs. death to avoid being buried; it escapes the pit if successful. Tunneling is possible with this spell as long as there is space available for the material removed. Chances for collapse are doubled and the safe tunneling distance is half of the safe excavation depth, unless such construction is most carefully braced and supported.

The spell is also effective against creatures of earth and rock, particularly clay golems and those from the Elemental Plane of Earth. When cast upon such a creature, it suffers 4d6 points of damage. A successful saving throw vs. spell reduces this damage to half.
</div>

<div class="spell" data-tag="Dimension Door" id="Dimension Door">
## Dimension Door

Magic-User 4 

Range: 10'

Duration: Instantaneous

The caster of this spell instantly transfers himself or herself, or any single target creature within range, to any spot within 200' plus 20' per caster level. The caster or target creature always arrives at exactly the spot desired, whether the caster visualizes the area or states direction and distance. An unwilling target may save vs. Spells to avoid being transported. Anything worn or carried by the caster or target creature will be transported also, including another character or creature if the transportee can lift it. If the target area is within a solid object, the spell fails automatically.
</div>

<div class="spell" data-tag="Disintegrate" id="Disintegrate">
## Disintegrate
 
Magic-User 6

Range: 60'

Duration: Instantaneous

This spell causes a thin, green ray to spring from the caster's pointing finger. Any single creature or object (up to a 10x10x10 foot cube of material) is entirely disintegrated, leaving behind only a trace of fine dust. A disintegrated creature’s equipment is unaffected.

A creature that makes a successful save vs. Spells is unaffected. The ray can target only one creature per casting, if that target saves, the spell is wasted.
</div>

<div class="spell" data-tag="Dispel Evil" id="Dispel Evil">
## Dispel Evil

Cleric 5

Range: Touch

Duration: 1 round/level

This powerful spell aids the caster in dealing with creatures from the nether planes, hereafter called "evil creatures."

First, the caster gains a +4 bonus to Armor Class against attacks by evil creatures.

Second, the caster can choose to drive an evil creature back to its home plane by touch (requiring a successful attack roll). The creature can negate the effects with a successful save vs. Spells. This use discharges and ends the spell, even if the saving throw succeeds.

Third, with a touch the caster can automatically dispel any one spell cast by an evil creature. Exception: Spells that can't be dispelled by [Dispel Magic](allSpells.html#dispel-magic) also can't be dispelled by **Dispel Evil**. Saving throws do not apply to this effect. This use also ends the spell.

The exact definition of evil is left for the GM to decide; however, extraplanar creatures that oppose the caster should almost always qualify.
</div>

<div class="spell" data-tag="Dispel Magic" id="Dispel Magic">
## Dispel Magic

Cleric 4, Magic-User 3

Range: 120'

Duration: Instantaneous

The caster can use dispel magic to end ongoing spells that have been cast on a creature or object, or to end ongoing spells (or at least their effects) within a cubic area 20' on a side. The caster must choose whether to dispel magic on a creature or object, or to affect an area.

If dispel magic is targeted at a creature, all spell effects (including ongoing potion effects) may be canceled. If cast upon an area, all such effects within the area may be canceled. Any spell or effect having a caster level equal to or less than the **Dispel Magic** caster's level is ended automatically. Those created by higher level casters might not be canceled; there is a 5% chance the dispel magic will fail for each level the spell effect exceeds the caster level. For example, a 10^th^ level caster dispelling magic created by a 14^th^ level caster has a 20% chance of failure.

Some spells cannot be ended by dispel magic; this specifically includes any curse, including those created by [Bestow Curse](allSpells.html#remove-curse) (the reverse of **Remove Curse**) as well as by cursed items.
</div>

<div class="spell" data-tag="Disruption" id="Disruption">
## Disruption*

Cleric 1

Range: Touch

Duration: 1 turn/level

The Disruption spell blesses one blunt melee weapon, be it a mace, hammer, staff, with divine power. When fighting undead creatures or beings of the netherworld (demons, devils, and the like) the weapon is enhanced by +1 to hit and damage. This is in addition to any existing powers for an enchanted weapon.

Any being subject to this bonus that is struck in combat must save versus Magic or be turned, exactly like the cleric ability (see Turning in the core rules), causing the affected monster to flee the area. The character wielding the blessed weapon may opt to not cause the disruption effect, but must declare their intention before their attack roll. The caster can have only one weapon blessed in this manner at a time.

The reverse of this spell **Corruption** works exactly the same against creatures of goodness from various heavenly realms. Only those worshiping vile powers would have access to the reversed version of this spell.
</div>

<div class="spell" data-tag="Divination" id="Divination">
## Divination

Cleric 4, Magic-User 4

Range: Self

Duration: Instantaneous

This magic and an offering (such as tea leaves) puts the caster in contact with the pattern of the universe. This pattern can be deciphered to interpret dreams, predict the future, Identify a Magic Item, or to find hidden things.            

The caster may ask a single question. The DM roles on the chart below and gives tan appropriate reply based on that role. The reply might be a short phrase, a cryptic rhyme, or an omen.

|   (1d20)    |   Description            |
|-------------|--------------------------|
| 1-3 (15%)   | Total Failure; no answer |
| 4-6 (15%)   | Partial Failure; Misleading answer |
| 7-13 (35%)  | Partial Success; Cryptic answer |
| 14-17 (20%) | Success; Clear but Succinct answer |
| 18-20 (15%) | Complete Success; Clear and Detailed answer |
</div>


<div class="spell" data-tag="Dowse" id="Dowse">
## Dowse

Cleric 0, Druid 0

Range: Self

Duration: Contcentration

This minor magical effect allows the caster to sense the presence of potable water using a forked stick (any will do, but some have favorites). While outdoors the dowsing rod will twist to point in the direction of such fresh water up to 1000 feet +100' per level of the caster. Water that is underground, in containers, or within structures can be located within 25 feet +5' per level. The effect lasts as long as the caster maintains concentration.
</div>

<div class="spell" data-tag="Drainblade" id="Drainblade">
## Drainblade
 
Black Magic-User 3

Range: Touch

Duration: 1 round/level

This spell imbues an edged weapon with the ability to drain blood with each successful strike made against a living creature.  When a living creature is hit by a drainbladed weapon, the target suffers 1 additional point of damage.  If the wielder of the weapon is injured, the extra point of damage is transferred to them as healing energy.  In no way can this healing energy grant more hit points than the wielder's normal maximum.

Against nonliving creatures, such as undead, golems, living statues, etc, this spell has no effect.
</div>

<div class="spell" data-tag="Drawmij’s Instant Summons" id="Drawmij’s Instant Summons">
## Drawmij’s Instant Summons

Magic-user 7

Range: Infinite + special

Duration: Instantaneous

When this spell is cast, the magic-user teleports some desired item from virtually any location directly to their hand. The single object can be no longer in any dimension than a sword, can have no more weight than a shield (about eight pounds), and must be nonliving. The desired item is then transported instantly into the Magic-User's hand. The item must have been previously touched and specifically named; only that particular item is summoned by the spell.
</div>

<div class="spell" data-tag="Earthquake" id="Earthquake">
## Earthquake

Cleric 7, Druid 7

Range: 400' + 40'/level

Duration: 1 round

When cast, this spell causes a powerful, but localized, earthquake that is 10 feet in diameter per caster level. The shock of the quake will knock down creatures, topple plants, collapse structures, open cracks in the earth, and more. The effect lasts for one round, during which creatures in the affected area cannot move or act. The earthquake affects everything touching the ground in the affected area. The specific effect depends on the type of terrain where the spell is cast:

• Cave, cavern, tunnel: Causes the roof to collapse causing 8d6 damage to everyone in the affected area (save vs. Petrify for half damage), pinning all creatures beneath the rubble. Small rooms and tunnels become completely filled.

• Cliff: Causes a landslide. Any creatures in the path take 8d6 damage (save vs. Petrify for half damage), pinning all creatures beneath the rubble.

• Open ground: All creatures in the area must save vs. Petrify or fall to the ground. Fissures open up and all creatures in the area have a 1 in 4 chance of falling in (save vs. Death Ray to avoid). After the end of the spell, the fissures close up, killing anything that fell in.

• Structures: Any structures directly touching the affected ground take 100 points of damage, ignoring [hardness](combat.html#attacking-a-vehicle). If this causes the structure to collapse, anyone trapped inside takes 8d6 damage (save vs. Petrify for half damage) and is pinned beneath the rubble.

• River, lake, marsh: Fissures in the bottom drain the water away, resulting in a muddy quicksand-like surface to remain. All creatures in the affected area must save vs. Death Ray or be stuck. After the end of the spell, the surrounding water rushes back in, potentially drowning any creatures stuck in the mud.

Any creature pinned by rubble takes 1d6 points of non-lethal damage per minute until rescued or they fall unconscious. Once unconscious, they take 1d6 points of lethal damage per minute until they are rescued or die.
</div>

<div class="spell" data-tag="Ethereal" id="Ethereal">
## Ethereal
 
Black Magic-User 3

Range: Touch

Duration: 1 turn/level

This spell causes the recipient to enter the ethereal plane. They become semi-transparent and immaterial.  While in this state, magical weapons or weapons with certain special properties are necessary to strike the recipient.  Any stealth checks such as Move Silently or Hide are made at +4, and the character may move through materials up to 1 inch thick per level of the caster.  Some materials may prevent passage such as lead, gold, or other materials with special properties. While able to move through materials and effectively weightless, the ethereal being does not gain any other special movement modes like flying or levitation; walking upon materials such as water is possible though.

The ethereal character may not make physical attacks but may cast spells that do not require physical contact.  While the spell is active, the individual may choose to revert back and forth between corporeal and incorporeal forms on their turn, remaining in the chosen state until their next turn. 

There is a 10% chance (DC 2) that each turn that a creature is ethereal that they will draw the attention of a wraith (1) or ghost (2) that will immediately attack.
</div>

<div class="spell" data-tag="Enervation" id="Enervation">
## Enervation

Black Magic-User 4

Range: 50'

Duration: Instantaneous

The caster points a finger at their intended target and rolls a ranged attack roll against the target that ignores armor (but not any Dexterity bonus).  If the narrow ray of crackling black energy hits, the target suffers 1d4 negative levels and all of the effects described in [Energy Drain](combat.html#energy-drain). There is no saving throw, only the attack roll.

If the target survives, it will lose the negative levels (i.e. regain their levels) after a number of hours equal to the caster’s level.

An undead creature struck by the ray gains 5d4 temporary hit points for one hour.
</div>

<div class="spell" data-tag="Enlarge" id="Enlarge">
## Enlarge*

Magic-User 1

Range: 5 yards/level

Duration: 5 rounds/level

This spell causes instant growth of a creature or object, increasing both size and weight. It can be cast only upon a single creature (or a symbiotic or community entity) or upon a single object that does not exceed 10 cubic feet in volume per caster level. The object or creature must be seen to be affected. It grows by up to 10% per level of experience of the magic-user, increasing this amount in height, width, and weight will increase cubicly.

All equipment worn or carried by a creature is enlarged by the spell. Unwilling victims are entitled to a saving throw vs. spell. A successful saving throw means the spell fails. If insufficient room is available for the desired growth, the creature or object attains the maximum possible size, bursting weak enclosures in the process, but it is constrained without harm by stronger materials--the spell cannot be used to crush a creature by growth.

Magical properties are not increased by this spell--a huge sword +1 is still only +1, a staff-sized wand is still only capable of its normal functions, a giant-sized potion merely requires a greater fluid intake to make its magical effects operate, etc. Weight, mass, and strength are affected, though. Thus, a table blocking a door would be heavier and more effective, a hurled stone would have more mass (and cause more damage), chains would be more massive, doors thicker, a thin line turned to a sizeable, longer rope, and so on. A creature's hit points, Armor Class, and attack rolls do not change, but damage rolls increase proportionately with size.

For example, a fighter at 160% normal size hits with their long sword and rolls a 6 for damage. The adjusted damage roll is 10 (that is, 6 x 1.6 = 9.6, rounded up). Bonuses due to Strength, class, and magic are not altered.

The reverse spell, **Reduce**, negates the enlarge spell or makes creatures or objects smaller. The creature or object loses 10% of its original size for every level of the caster, to a minimum of 10% of the original size. Thereafter, the size shrinks by 1-foot increments to less than 1 foot, by 1-inch increments to 1 inch, and by 1/10-inch increments to a minimum of 1/10 of an inch--the recipient cannot dwindle away to nothingness.

For example, a 16-foot-tall giant reduced by a 15th-level magic-user (15 steps) would be reduced to 1.6 feet (in nine steps), then to 6/10 of a foot or 7.2 inches (in one step), and finally to 2.2 inches (in the last five steps). A shrinking object may damage weaker materials affixed to it, but an object will shrink only as long as the object itself is not damaged. Unwilling creatures are allowed a saving throw vs. spell.
</div>


<div class="spell" data-tag="Entagle" id="Entagle">
## Entagle

Druid 1

Range: 200'

Duration: 3 rounds/level

This spell causes existing grasses, trees, bushes, shrubs, or other plants to entwine around creatures in a 40 ft x 40 ft area. At the GM's discretion a caster underground may use roots of plants or trees if such are present. Most creatures within the area of effect move at ¼ normal speed; very large and/or very strong creatures (at least as big or strong as a giant or dragon) move at ½ normal speed.

If the creature affected is running at the time the spell is cast, the creature must make a saving throw vs Spell (with Dexterity bonus applied, if any) or trip and become prone and trapped until the end of spell.  Entangled creatures may not attack nor take most actions other than movement due to the interference of the enchanted plants. This spell is only effective in a settings where plants will grow, including wilderness areas, farmland, and earthen-walled tunnels.
</div>


<div class="spell" data-tag="Entangling Thorns" id="Entangling Thorns">
## Entangling Thorns

Druid 3

Range: 100'+10'/level

Duration: 1 round/level

The druid chooses one target creature (or object) within range, beneath which great thorny tendrils quickly grow up and around. If the subject fails its save vs. Spells, it is held immobile, suffering a -2 penalty to hit and a -4 penalty to its armor class. In addition, the thorny growths cause 1d4 points of damage to the target each round. An individual so entangled may only cast spells if a DC 15 is achieved, modified by their primary spell casting ability score bonus.

The process of breaking free takes the entire round, during which damage is still incurred. Additionally, the thorny growths can be directly attacked (against AC 11) with small bladed weapons such as daggers or hand axes. The vines have 22 hp and destroying them ends the spell. Immediately. Using other larger weapons or spells will damage the entangled creature as much as the thorns, splitting the damage between them equally.
</div>

<div class="spell" data-tag="ESP" id="ESP">
## ESP
 
Magic-User 2

Range: 60'

Duration: 1 turn/level

This spell permits the caster to detect the surface thoughts of one or more targets within range.  The caster must designate a direction, and then concentrate for a turn in order to “hear” the thoughts.  Each turn the caster may choose to “listen” in a different direction.  The caster may stop listening, then resume again later, so long as the duration has not expired.  The target creature is not normally aware of being spied upon in this way.

Rock more than 2 inches thick or a thin coating of lead or gold will block the spell.  All undead creatures are immune to this effect, as are mindless creatures such as golems.
</div>

<div class="spell" data-tag="Ether Bold" id="Ether Bolt">
## Ether Bolt
 
Magic-User 2

Range: 30' + 5'/level

Duration: Instantaneous

This spell fires off a missile or beam-like effect that only strikes foes that are insubstantial, ethereal, phase-shifted, or otherwise not fully materially present. This primarily includes various types of undead, but may include other beings that have similar qualities such as shadows. Much like a magic missile, the bolt strikes unerringly if the target is in sight, causing 1d4 points of force-like impact damage per level of the caster, striking as if the target was a completely solid being.
</div>

<div class="spell" data-tag="Extension" id="Extension">
## Extension

Magic-User 4

Range: Special

Duration: Special

By use of an extension spell, the wizard doubles the duration of a previously cast 1st-, 2nd-, or 3rd-level spell. Naturally, the spell affects only spells that have durations.

This spell must be cast immediately after the spell to be extended, either by the original caster or another wizard. If a complete round or more elapses, the extension fails and is wasted.
</div>

<div class="spell" data-tag="Eyebite" id="Eyebit">
## Eyebite
 
Black Magic-User 6

Range: 60'

Duration: 1 round/3 levels

Each round the caster may target a single living creature for the duration of the spell.  The affected creature suffers effects depending on its total hit dice.  If the target has 10 HD or more, it is sickened.  If the target has 5 HD through 9 HD, it is panicked and sickened.  If the target has 4 HD or fewer, it is comatose, panicked, and sickened.  The effects are cumulative and concurrent.  Targeting each additional creature after the first requires an action, and only one may be targeted in a given round.

The target must save vs. Death Ray to avoid the worst effect of the spell.  If the target is affected by more than one effect, the remaining effects are still present.

If a creature is sickened, it suffers from a -2 modifier for attack rolls, damage rolls, and saving throws.  This effect lasts for 1 turn per caster level.

If a creature is panicked, it will flee for 1d4 rounds.  After that, the victim will flee again for 1d4 rounds if it can still see the caster.  Even after the fleeing ends, the creature is still affected by the sickening as described above.

If a creature is comatose, it falls into a coma for 1 turn per caster level.  During this time, the victim cannot be awakened by any means short of dispelling the effect.  Even if the comma is dispelled, the creature is still subject to fleeing if the caster is visible, and is still sickened.  This is not a sleep effect.
</div>

<div class="spell" data-tag="Faerie Fire" id="Faerie Fire">
## Faerie Fire

Druid 1, Magic-User 2

Range: 200’ +10'/level

Duration: 1 minute/level

A pale glow surrounds and outlines all objects including individuals within a 20 ft radius from a point chosen by the caster.  Outlined subjects shed light as candles.  Outlined creatures do not benefit from the concealment normally provided by darkness, and the spell effectively negates the effects of blur, displacement, invisibility, or similar effects. 

The light is too dim to have any special effect on undead or dark-dwelling creatures vulnerable to light.  The faerie fire can be blue, green, or violet, according to your choice at the time of casting.  The faerie fire does not cause any harm to the objects or creatures thus outlined.
</div>

<div class="spell" data-tag="Faerie Ring" id="Faerie Ring">
## Faerie Ring

Druid 7

Range: 10'

Duration: 1 hour/level

When the caster creates a Faerie Ring, a small circle of distinct mushrooms or toadstools grow quickly. Those that walk into the circle (about 5 foot diameter) are transported into a region that borders the FeyWild (another plane of existence). This region can be utilized as a safe place to rest and recuperate (at double normal rate for purpose of healing and restoration of spells). From this border region, one may pass back into the familiar prime world or they might travel to the actual FeyWild.

The Feywild is the Plane of Faeries and it intersects with the OnceWas. The FeyWild is an echo of the real world but suffused with potent magic and unrestrained emotions. As an echo of OnceWas, its geography is similar although not entirely identical. The landscape is markedly more dramatic and beautiful with more trees and flowers.  The mountains stand straighter and sharper. The rivers flow clearer and faster, the flowers bloom brighter and more fragrantly, and the weather manifests in supernatural ways.

Time does not flow the same in the Feywild as it does in the OnceWas. While any visitor would experience time flowing as normal, it is often the case that more time was passing in the real world, sometimes on the order of weeks, months, or years longer than expected.

More concerning, leaving the Feywild can have dire consequences. Lost time could suddenly "catch up" to a mortal, sending them into fits of exhaustion or hunger, or even killing them instantly if many years had passed. Often, memories of time spent in the Feywild become hazy and dreamlike, if not vanishing altogether.

It is said to be the place from where the first elves originated.

Ki, goddess of life and nature and Queen of faeries, is known to spend time in the FeyWild when not in Elysium or in the OnceWas.
</div>

<div class="spell" data-tag="Familiar*" id="Familiar">
## Familiar

Magic-User 1

Range: Touch

Duration: Special

With this spell, the caster binds a single animal into their service as a familiar. The spell requires 10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier. The creature must be present, and the caster must touch it to cast the spell.

Only normal (non-magical) creatures of 1-1 hit die may be made into familiars. Further, each spellcaster may have only one familiar at a time. If a familiar dies, the caster will not be able to successfully cast this spell again for 2d6 months (the period to be rolled by the GM and not revealed to the player). A saving throw vs. Spells is allowed to resist, and if this roll succeeds, the animal chosen is not compatible with the caster and cannot become their familiar.

The familiar will behave as if permanently charmed by its master and will perform any task assigned to it to the best of its ability. The creature's morale is increased by 2 points (to a maximum of 11), and it receives improved intelligence equal to 3+1d4 points. Familiars also age at half the normal rate for their kind, so a cat familiar (for instance) might easily live forty years.

The familiar's hit points are added to the Magic User 's. If a familiar is slain, the Magic User loses double the familiar's hit points, permanently.

In combat, it shares initiative and acts at the end of the Magic User’s turn.

Within 200 feet, the Magic User can see through the familiar's eyes and hear what it hears, returning to the Magic User’s senses at will. During this time, the Magic User is deaf and blind regarding their own senses.

Additionally, while the familiar is within 100 feet of the Magic User, they can communicate telepathically. This communication is in simple telepathic concepts, such as "3 angry people. One is short" or "path forks, 3 ways ahead, smells like food". Not enough detail for a map.
</div>

<div class="spell" data-tag="Flame Strike" id="Flame Strike">
## Flame Strike

Druid 5, Magic-User 5

Range: 60'

Duration: Instantaneoous

A **Flame Strike** produces a vertical column of divine fire roaring downward (cylinder of 10 ft radius, 30 ft high).  The spell deals 6d8 points of damage to any creatures within the area of effect; a save vs. Spells for half damage is allowed.
</div>

<div class="spell" data-tag="Feather Fall" id="Feather Fall">
## Feather Fall

Magic-User 1

Range: 10 yards/level

Duration: 1 round/level

When this spell is cast, the creature(s) or object(s) affected immediately assumes the mass of a piece of down. The rate of falling is instantly changed to a mere 2 feet per second (120 feet per round), and no damage is incurred upon landing while the spell is in effect. However, when the spell duration ceases, a normal rate of fall occurs. The spell can be cast upon the wizard or some other creature or object up to the maximum range and lasts for one round for each level of the wizard.

The feather fall affects one or more objects or creatures in a 10-foot cube, as long as the maximum weight of the creatures or objects does not exceed a combined total of 200 pounds plus 200 pounds per level of the spellcaster.

For example, a 2nd-level wizard has a range of 20 yards, a duration of two rounds, and a weight limit of 600 pounds when casting this spell. The spell works only upon free-falling, flying, or propelled objects (such as missiles). It does not affect a sword blow or a charging creature. Note that the spell can be effectively combined with [Gust of Wind](allSpells.html#gust-of-wind) and similar spells.
</div>

<div class="spell" data-tag="Feeblemind*" id="Feeblemind*">
## Feeblemind*

Range: 180'

Magic-User 5

Duration: Permanent

This spell allows the caster to inflict a terrible curse on a living creature, reducing both Intelligence and Charisma to just 1 point each. A saving throw vs. Spells is
allowed to resist this effect, but if the target creature is a spellcaster a penalty of -4 is applied to the saving throw.

Once feebleminded, the victim of this spell can no longer cast spells, speak or understand any language, or indeed communicate at all as their mind can no longer
understand even such simple things as pointing or beckoning. The victim still knows their friends and allies and will follow them and try to help or protect
them.

This effect can be removed with a [Heal](allSpells.html#heal) spell, or with the reversed form of this spell **Restoremind**.
</div>

<div class="spell" data-tag="Find Traps" id="Find Traps">
## Find Traps

Cleric 2

Range: 30'

Duration: 3 turns

This spell permits the caster to detect a variety of traps, both mechanical and magical. When the caster moves within 30’ of a trap, he or she will see it glow with a faint greenish-blue aura. The caster is not, however, able to detect certain natural hazards such as quicksand, a sinkhole, or unsafe walls of natural rock. The spell also does not bestow the caster with the knowledge needed to disarm the trap, nor any details about its type or nature.
</div>

<div class="spell" data-tag="Find the Path" id="Find the Path">
## Find the Path

Cleric 6, Druid 6

Range: Touch

Duration: 1 turn/level

The recipient of this spell can find the shortest, most direct physical route to a specified destination. The caster must have some knowledge about the location; any location the caster has ever visited can be so located, as well as locations described to the caster. Even knowing the name of a location (if it has a name) is enough for this spell to function.

The locale can be outdoors or underground. **Find the path** works with respect to locations, not objects or creatures. The location must be on the same plane as the caster at the time of casting.

The spell enables the subject to sense the correct direction that will eventually lead it to its destination, indicating at appropriate times the exact path to follow or physical actions to take. For example, the spell enables the subject to detect secret doors and to know any passwords required. The spell ends when the destination is reached or the duration expires, whichever comes first.
</div>

<div class="spell" data-tag="Fireball" id="Fireball">

## Fireball

Range: 100'+10'/level

Magic-User 3

Duration: Instantaneous

Casting this spell causes a tiny glowing ember about the
size of a pea to fly forth from the caster's pointing finger,
by which the direction of flight is indicated. The ember
flies as fast as an arrow and explodes into flames filling
a 20' radius sphere when it reaches a distance chosen
by the caster (up to its maximum range), or sooner if it
impacts any solid or liquid surface. Those within the
area of the flames suffer 1d6 points of damage per
caster level, with a saving throw vs. Spells allowed for
half damage.

No roll is normally required when casting this spell, but
if the caster wishes to project the ember through a slit or
other small opening they must roll a missile attack
(without range adjustments) to hit it; failure indicates
the fireball hits an adjacent surface and detonates there.

Combustible objects or substances within the area of
effect will generally catch fire and possibly be destroyed
(as determined by the GM). Metals with low melting
points such as gold, silver, lead, copper, or bronze may
be softened briefly and thus deformed, but the flames
do not persist long enough to actually melt the metal
items unless they are very small (such as a thin gold
neck chain for example).

While the fireball exerts little if any force or pressure
when exploding, it may still destroy weak or flammable
barriers; if such a thing happens (in the determination
of the GM, of course), the fireball completes its
expansion in the space beyond the destroyed barrier.

</div>
<div class="spell" data-tag="Flesh to Stone*" id="Flesh to Stone*">

## Flesh to Stone*

Range: 30'/level

Magic-User 6

Duration: Permanent

This spell causes a living creature, along with all gear it
wears or carries, to be petrified. This is the same effect
caused by the gaze of a medusa or the touch of a
cockatrice. A saving throw vs. Petrification is allowed to
resist the spell.

The petrified victim becomes dormant; its mind cannot
be contacted in any way, and it is neither properly alive
nor dead. Damage inflicted on its statue-like form will
apply to its fleshy form if it is ever restored; simply
breaking off an arm or leg is probably enough to result
in death due to blood loss. The GM should determine
the effects of any such injury.

The reverse spell, **stone to flesh**, acts as a counterspell for **flesh to stone**, restoring the creature just as it was when it was petrified. It does nothing if applied to stone that is not the result of **flesh to stone** or similar petrification effects (such as a medusa's gaze).

</div>
<div class="spell" data-tag="Floating Disc" id="Floating Disc">

## Floating Disc

Range: 0

Magic-User 1

Duration: 5 turns +1/level

The casting of this spell causes an invisible platform of
magical force to appear. It is about the size of a shield,
about 3 feet in diameter and an inch deep at its center.
It can support a maximum of 500 pounds of weight.
(Note that water weighs about 8 pounds per gallon.)
The disc floats level to the ground, at about the height
of the caster's waist. It remains still when within 10' of
the caster, and follows at the caster's movement rate if
they move away from it. The floating disc can be
pushed as needed to position it but will be dispelled if
somehow moved more than 10 feet from the caster.
When the spell duration expires, the disc disappears
from existence and drops whatever was supported to
the surface beneath.

The disc must be loaded so that the items placed upon
it are properly supported, or they will (of course) fall off.
For example, the disc can support just over 62 gallons
of water, but the water must be in a barrel or other
reasonable container that can be placed upon the disc.
Similarly, a pile of loose coins will tend to slip and slide
about, and some will fall off with every step the caster
takes; but a large sack full of coins, properly tied, will
remain stable.

</div>
<div class="spell" data-tag="Fly" id="Fly">

## Fly

Range: Touch

Magic-User 3

Duration: 1 turn/level

The subject of this spell can fly at a speed equal to his or her normal ground movement rate (as adjusted by encumbrance). The subject can ascend at half speed and descend at double speed, with the same maneuverability as the subject has when moving on the ground. Flying under the effect of this spell requires only as much concentration as walking, so the subject can attack or cast spells normally. The subject of a fly spell can neither charge nor run, nor carry aloft more weight than his or her maximum load.

If the spell duration expires while the subject is still airborne, the magic fails slowly such that the subject descends at a rate of 120 feet per round for 1d10 rounds. If the subject reaches the ground in that time they land safely; if not, the subject falls the rest of the distance and suffers normal falling damage. However, if this spell is ended by [Dispel Magic](allSpells.html#dispel-magic) or similar outside forces, the subject falls immediately. For any such fall, see [Falling Damage](combat.qmd#falling-damage) for details of the consequences.

</div>

<div class="spell" data-tag="Gate" id="Gate">
## Gate

Cleric 7, Magic-User 7

Range: 120'

Duration: Special

This spell creates an inter-dimensional connection between the caster’s location and another plane. This allows for travel between the two locations in either direction. The gate stays open as long as the caster concentrates on it, up to 1 round/caster level plus one additional round.

The gate appears as a flat circle with a diameter of 5 to 20 feet (caster's choice). It can be situated at any angle, but will usually be vertical. The back (the side facing away from the caster) is filled with an insubstantial opaque haze and passing through does nothing. The front shows where the gate is connected. This is full opening between locations with complete visibility (subject to the conditions on the other side; from a place in the air to a place in the water will get expected results) and accessibility.

The gate is full two-way, and anyone on either side can pass back and forth either way, including going one way and back the other as long as the gate stays open. Any number of people or things can use the gate, subject to the spell's duration and normal physical constraints. When the spell expires (or if the caster ends or loses concentration) it goes away, but can always be recreated by casting the spell again.

Note that the spell will allow both sides to be on the same plane if so desired, and that means it can also work as a very powerful alternative to teleportation.

As long as the destination is known and exists as known, the gate will open where desired. If not, the gate will open in a random location on the plane (i.e. wherever the GM wants it to). Some extraordinary creatures, at the GM’s discretion, are powerful enough to detect that a gate is about to open and prevent it.
</div>

<div class="spell" data-tag="Gishigan's Geas*" id="Geas*">
## Gishigan’s Geas*
 
Magic-User 6

Range: 5' per level

Duration: Special

**Gishigan’s Geas** places a magical command on a creature to carry out some service or to refrain from some action or course of activity, as desired by the caster. The target creature must be able to understand the caster for this spell to take effect. While a geas cannot compel a creature to kill itself or perform acts that would result in certain death, it can cause almost any other course of activity.

A saving throw vs. Spells will allow an unwilling target to resist a geas when it is first cast. However, the target may choose to accept the geas, typically as part of a bargain with the caster to perform some service.

The geased creature must follow the given instructions until the geas is completed, no matter how long it takes.

If the instructions involve some open-ended task that the recipient cannot complete through his or her own actions, the spell remains in effect for a maximum of one day per caster level. A clever recipient can subvert some instructions, at the GM's discretion.

For every 24 hours that the subject chooses not to obey the geas (or is prevented from obeying it), it suffers a --2 penalty to each of its ability scores, up to a total of --8. No ability score can be reduced to less than 3 by this effect. The ability score penalties are removed 24 hours after the subject resumes obeying the geas.

A geas (and all effects thereof) can be ended by a [Remove] Curse(allSpells.html#remove-curse) spell, or by a **Wish**, or by the reverse of this spell. [Dispel Magic](allSpells.html#dispel-magic) does not affect a geas.
</div>

<div class="spell" data-tag="Growth of Animals" id="Growth of Animals">
## Growth of Animals

Cleric 3

Range: 60'+10'/level

Duration: 1 turn/level

This spell causes an animal to grow to twice its normal size and eight times its normal weight. The affected creature will do double normal damage with all physical attacks, and its existing natural Armor Class increases by 2. The animal's carrying capacity is also doubled. Unfriendly animals may save vs. Spells to resist this spell; normally, domesticated animals will not attempt to resist it, though they may become confused or panicky afterward (at the GM's discretion).

All equipment worn or carried by an animal is similarly enlarged by the spell, though this change has no effect on the magical properties of any such equipment. Any enlarged item that leaves the enlarged creature's possession instantly returns to its normal size.

The spell gives no means of command or influence over the enlarged animals.

</div>
<div class="spell" data-tag="Growth of Plants*" id="Growth of Plants*">

## Growth of Plants*

Range: 120'

Magic-User 4

Duration: Permanent

This spell causes normal vegetation of any sort within
range to become thick and overgrown. The area of
effect is determined by the caster, but cannot exceed
1,000 square feet (a 10'x100' area or equivalent) per 5
caster levels. The plants become densely entangled,
and characters or creatures wishing to move through
must hack or force their way through it. All movement
within the affected area is reduced to no more than 5’
per round for less than giant sized creatures; giant sized
creatures are reduced to half normal movement rate.

This spell cannot take effect in an area that does not
already have some plants present. Any sort of
animated plant creature affected by this spell is allowed
a saving throw vs. Spells to resist, but if this save fails it
is affected as with **growth of animals** above.

The reverse form, **shrink plants**, may be used to
render overgrown areas passable. The area of effect is
identical to the normal version. Animated plant
creatures are normally unaffected by this spell, but if
such creatures have already been enlarged by **growth of plants** this spell will reverse the effect. In the latter
case, a saving throw vs. Spells is allowed to resist.

Both forms of this spell are permanent until countered,
either by the reverse of the spell or by **dispel magic**.

</div>
<div class="spell" data-tag="Hallucinatory Terrain" id="Hallucinatory Terrain">

## Hallucinatory Terrain

Magic-User 4

Range: 400'+40'/level

Duration: 12 turns/level

This spell makes one 10 yard cube per level of outdoor terrain appear like a different type (i.e. field into forest, grassland into desert, or the like). This spell requires a full turn to cast.

The affected terrain looks, sounds, and smells like another sort of natural terrain. Structures, equipment, and creatures within the area are not hidden or changed in appearance. A save vs. Spells is allowed to see through the illusion, but only if the creatures or characters affected actively attempt to do so.

</div>
<div class="spell" data-tag="Haste*" id="Haste*">

## Haste*

Range: 30'+10'/level

Magic-User 3

Duration: 1 round/level

This spell accelerates the actions of 1 creature per caster
level. The affected creatures move and act twice as fast
as normal, having double their normal movement rates
and making twice the normal attacks per round, for the
duration of the spell. Spellcasting is not accelerated,
nor is the use of magic items such as wands, which may
still be used just once per round. Multiple haste or
speed effects don’t combine; only apply the most
powerful or longest lasting effect.

In combat, the subject of this spell performs a full round
of actions (movement followed by attacking) on their
normal Initiative; after all combatants have acted, the
subject may perform another round of actions as
before. If two or more combatants are under the effect
of this spell, use the same Initiative numbers to
determine the order of their actions in each of their
"extra" rounds.

Reversed, haste becomes **slow**; affected creatures move at half speed, attacking half as often (generally, every other round) and making half a normal move each round. Naturally, target creatures may save vs. Spells to avoid the effect. Haste and slow counter and dispel each other.

</div>
<div class="spell" data-tag="Heal*" id="Heal*">

## Heal*

Range: Touch

Cleric 6

Duration: Permanent

This spell enables the caster to almost totally cure
wounds, diseases, and other afflictions of a single living
creature. With a touch the caster cures blindness,
deafness, **confusion**, disease, **feeblemind**, choking,
nausea, and poison. All but 1d4 hit points are restored
to the subject, if it has any injuries. Ability points losses
are fully restored, if and only if those losses would be
recoverable without this spell; permanent losses to
ability scores are not recovered. Energy drain is also
not affected by this spell.

The reversed spell, **harm**, injures the creature touched so horribly that it is left with only 1d4 hit points. The caster must succeed at a normal attack roll in this case; failure means the spell is wasted. Note that, if the victim has fewer hit points remaining than the number rolled, he or she will take at least one point of damage (and this is the only case in which **harm** may kill a creature).

Generally, both **heal** and** harm** only affect living creatures. If used against an undead creature, heal instead acts like harm; likewise, harm affects undead like heal. Constructs such as golems are unaffected by either spell.

</div>
<div class="spell" data-tag="Hold Monster" id="Hold Monster">

## Hold Monster

Range: 180'

Magic-User 5

Duration: 2d8 turns

This spell functions like **hold person**, except that it affects any living creature that fails its save vs. Spells.

</div>
<div class="spell" data-tag="Hold Person" id="Hold Person">

## Hold Person

Range: 180'

Cleric 2, Magic-User 3

Duration: 2d8 turns

This spell will render any living (not undead) humanoid
creature (as defined in **charm person**) paralyzed.
Creatures larger than ogres will not be affected by this
spell. Targets of the spell are conscious and able to
breathe, but cannot move, act, or speak in any way. A
successful save vs. Spells is allowed to resist the effect.
The spell may be cast at a single person, who makes
their save at -2, or at a group, in which case 1d4 of the
creatures in the group may be affected.

A paralyzed swimmer can’t swim and may drown. A
character who has somehow gained wings and is then
paralyzed while airborne will not be able to move its
wings to fly and will thus fall.

</div>
<div class="spell" data-tag="Hold Portal" id="Hold Portal">

## Hold Portal

Range: 100'+10'/level

Magic-User 1

Duration: 1 round/level

This spell secures a portal such as a door, gate,
window, or shutter made of normal non-magical
building materials; the portal behaves as if securely
locked for the duration of the spell. The door may be
opened early only by means of **knock** or a successful
casting of **dispel magic**, or by literally destroying the
door (which may well require more time than the
duration of this spell allows).

</div>
<div class="spell" data-tag="Ice Storm" id="Ice Storm">

## Ice Storm

Range: 300'+30'/level

Magic-User 4

Duration: 1 round

This spell causes a powerful storm of sleet and hail to
fall in a 20' radius around the target spot for a full
round. This effect causes 5d6 points of damage to
every creature within the area, with a save vs. Spells
allowed to reduce damage by half. The ice storm fills a
vertical volume of 40', so creatures higher than that
distance above the target spot are unaffected. Any
creature naturally resistant to cold takes half damage (or
one-quarter damage if it makes its save).

Visibility within the storm is very poor, such that most
creatures will attack with a penalty of -2 on the attack
roll. Walking movement is reduced to half speed, and
running is not possible within the storm; anyone who
tries will fall down and be forced to remain on the
ground until the spell ends. Flying is likewise
impossible, and any flying creature within the area will
be driven to the ground. A penalty of -20% is applied
to any Listen rolls made by those in the storm's area.

When the spell ends, the hail and ice deposited by the
storm disappears as if it had never existed.

</div>
<div class="spell" data-tag="Insect Plague" id="Insect Plague">

## Insect Plague

Range: 300'+30'/level

Cleric 5

Duration: 1 round/level

This spell summons one swarm of locusts per three caster levels, to a maximum of six swarms at 18^th^ level. See [Insect Swarm](monstersAll.qmd#insect-swarm) in the **Monsters** section for the effects of a swarm. As explained there, a normal swarm of insects occupies a contiguous area equal to three 10 foot cubes; all swarms summoned by this spell must be contiguous with each other such that they effectively form a single huge swarm, though the caster may stretch them out in a line, form them into a block, or indeed arrange them in some serpentine form if desired.

The summoned swarms persist for the duration above,
or until they are slain, whichever comes first. The
caster may summon them in areas where creatures are
already located. Once summoned, the swarms are
stationary until they disappear or are slain, and they
attack any creatures who are within their area.

</div>
<div class="spell" data-tag="Invisibility" id="Invisibility">

## Invisibility

Range: Touch

Magic-User 2

Duration: Special

This spell causes the creature touched (who may be the
caster) to become invisible, undetectable by normal
vision or Darkvision. Invisible creatures may be
detected by those with non-visual sensory abilities.

All items worn or carried by the target when the spell is
cast become invisible as well. If the target lays down an invisible item, it instantly becomes visible again; on the  other hand, items picked up do not automatically  become invisible. If the target places a visible item entirely inside its invisible clothing, backpack, pouch, or other container so that if the target were visible the item could not be seen, it will become invisible just as if it
were held when the spell was cast.

Note that casting this spell upon another makes the
target invisible to the caster as well as everyone else. A
party of invisible characters will likely experience
problems with running into or tripping over each other.
The spell lasts at most 24 hours if not ended sooner. It
ends instantly if the target attacks an opponent or casts
any spell. Other actions do not normally end the spell.
The target may end the spell at will.

Objects that shed light may be made invisible but the
light itself will remain visible, and the source of that light
(and the character carrying it) can thus be discovered.
Rain, dust, paint, and any other visible substance
thrown or applied to an invisible creature will also
render it detectable.

</div>
<div class="spell" data-tag="Invisibility 10' Radius" id="Invisibility 10' Radius">

## Invisibility 10' Radius

Magic-User 3

Range: Touch

Duration: 1 turn/level

The target of this spell becomes invisible just as with
**invisibility**, but in addition all other creatures within 10
feet of the target at the time of casting (referred to as
members of the group) also become invisible. Unlike
with normal invisibility, all members can see each other
and themselves normally.

If any member negates the effect by attacking or casting
a spell, it becomes visible but all other members remain
invisible. However, if the original subject takes an
action that negates the invisibility, it ends for the entire
group. If a member negates its own invisibility, that
member will no longer be able to see the still-invisible
group members. Moving further than 10 feet from the
target also causes a group member to become visible;
returning to the area does not reinstate the invisibility.

</div>
<div class="spell" data-tag="Invisible Stalker" id="Invisible Stalker">

## Invisible Stalker

Range: 0

Magic-User 6

Duration: Special

The caster summons an **invisible stalker** to do his or her bidding (see the [Monsters](monstersAll.qmd#invisible-stalker) section, below, for details). The spell persists until **dispel evil** is cast on the creature, it is slain, or the task is fulfilled. The GM is advised to review the monster entry for the invisible stalker when this spell is used, as they may not always be reliable servants.

</div>
<div class="spell" data-tag="Knock" id="Knock">

## Knock

Range: 30'

Magic-User 2

Duration: Special

The knock spell opens stuck, barred, locked, **held**, or **wizard locked** doors. It opens secret doors, as well as locked or trick-opening boxes or chests. It also loosens welds, shackles, or chains (provided they serve to hold shut something which can be opened). If used to open a **wizard locked** door, the spell does not remove the **wizard lock** but simply suspends its functioning for one turn. In all other cases, the door does not relock itself or become stuck again on its own. Knock will not raise a portcullis or operate any other similar mechanism, nor will it affect ropes, vines, and the like. 

Each casting undoes a single method of securing the
door or item, so that for example a door which is both
locked and stuck can be unlocked but will still be stuck;
a second casting of knock will open such a door.

</div>
<div class="spell" data-tag="Levitate" id="Levitate">

## Levitate

Range: Touch

Magic-User 2

Duration: 1 turn/level

When this spell is cast, the caster or any one creature or
object they touch begins to levitate. Levitation allows
the caster to cause the subject to rise or fall at a rate of
as much as 20 feet per round.

If a target creature is unwilling, the caster must roll a
successful attack roll in order to touch the target, and
even if this roll succeeds the target is allowed a save vs.
Spells to resist the magic. Likewise, if the target is an
object being held by an unwilling creature, a similar
attack roll and saving throw will be required.
Unattended objects are automatically affected when
touched.

The caster controls the levitating subject mentally. If
the caster ceases to control the subject, it remains at its
current altitude until the spell ends, at which point it
falls.

Levitation does not provide any means of horizontal
movement, but neither is the levitated subject fixed in
place. It can be moved by pushing or by towing with a
rope, for example. A creature being levitated can pull
itself along a cliff face or across a ceiling, or pull itself
with a rope fixed to a solid object. Movement of this
sort is usually at half normal walking speed. The
subject cannot, however, change its own altitude.

If a levitating creature attempts to attack with most
weapons it will find that it is unstable. The first such
attack is made at a penalty of -1 on the attack roll, and
this penalty worsens by an additional -1 each round to
a maximum penalty of -5. Should the creature refrain
from making an attack for a full round, it is reduced to
the -1 penalty level on the next round. This does not
usually affect spellcasting while levitated, however.

</div>
<div class="spell" data-tag="Light*" id="Light*">

## Light*

Range: 120'

Cleric 1, Magic-User 1

Duration: 6 turns + 1/level

This spell creates a light equal to torchlight which illuminates a 30' radius area (and provides dim light for an additional 20') around the target location or object. The effect is immobile if cast into an area, but it can be cast on a movable object. Light taken into an area of magical darkness does not function.

Reversed, **light** becomes **darkness**, creating an area of darkness just as described above. This darkness blocks out Darkvision and negates mundane light sources.

A light spell may be cast to counter and dispel the darkness spell of an equal or lower level caster (and vice versa). Doing so causes both spells to instantly cease, restoring the existing ambient light level.

Either version of this spell may be used to blind an opponent by means of casting it on the target's ocular organs. The target is allowed a saving throw vs. Death Ray to avoid the effect, and if the save is made, the spell does not take effect at all. A **light** or **darkness** spell cast to blind does not have the given area of effect (that is, no light or darkness is shed around the victim).

</div>
<div class="spell" data-tag="Lightning Bolt" id="Lightning Bolt">

## Lightning Bolt

Range: 100' + 10'/level

Magic-User 3

Duration: Instantaneous

Casting this spell causes a bright thin spark about the
thickness of a string to fly forth from the caster's
pointing finger, which indicates the direction. The spark
stretches as fast as an arrow's flight until it reaches the
caster's chosen distance (but not more than the range
given above) or strikes a solid or liquid surface, at which
point it explodes into a full-fledged bolt of lightning
extending another 60 feet further. The lightning bolt
passes through an area 5 feet wide, arcing and jumping,
so that while it is not actually 5 feet wide, for game
purposes it is treated as if it were.

Those within the area of the lightning bolt suffer 1d6
points of damage per caster level, with a saving throw
vs. Spells allowed for half damage.

If a lightning bolt is targeted at a body of water it
explodes at the point of impact, as described above, but
within the water volume struck it expands like a fireball
to a maximum radius of 20 feet instead of performing
as it does in the air. If a lightning bolt is cast
underwater it explodes in the same way, but at the tip
of the caster's outstretched finger.

The lightning bolt sets fire to combustibles and damages
objects in its path. It can damage metals with a low
melting point; metals such as gold, silver, lead, copper,
or bronze may be softened briefly and thus deformed,
but the lightning does not persist long enough to
actually melt the metal items unless they are very small
(such as a thin gold neck chain for example).

If the damage caused to an interposing barrier shatters
or breaks through it, the bolt may continue beyond the
barrier if the spell’s range permits; otherwise, it may
reflect from the barrier back toward the caster, or in a
random direction at the GM's option. Creatures already
affected by the lightning bolt do not take additional
damage if struck by the reflection of the same bolt.

</div>
<div class="spell" data-tag="Locate Object" id="Locate Object">

## Locate Object

Range: 360'

Cleric 3, Magic-User 2

Duration: 1 round/level

This spell grants the caster knowledge of the location of
an object. The caster must know the object well or be
able to clearly imagine it. (Viewing an accurate drawing
or painting will suffice for the latter option.) A general
item can be located; if more than one such item is in
range, the spell will lead the caster to the nearest one.

Unique or unusual items can only be located if the
caster has first-hand knowledge (not merely through
divination such as **clairvoyance** or a **crystal ball**). The
spell cannot be used to locate creatures of any sort. A
layer of lead or gold no thicker than foil surrounding the
item will prevent it from being located.

</div>
<div class="spell" data-tag="Lower Water" id="Lower Water">

## Lower Water

Range: 20'/level

Magic-User 6

Duration: 1 turn/level

Using this spell the caster lowers the level of the water
in a river, a lake, or even the sea by up to 2 feet per
caster level for the given duration, but to no less than 1
inch deep. The spell affects an area with radius of at
most 10 feet per level centered on the caster's chosen
location (within the range given).

There will be a steep slope up to the surface of any area
of un-lowered water that falls outside the spell's radius.
Ships which were already in the area of effect as well as
any that dare to enter it will be unable to climb the
slope and thus unable to leave the area (if not outright
beached by the spell in the first place).

This spell has the effect of **slow** (the reverse of **haste**)
when cast upon water elementals and other creatures
formed from water; a save vs. Spells is allowed, with
success negating the effect. It cannot be cast upon any
other kind of creatures.

</div>
<div class="spell" data-tag="Magic Jar" id="Magic Jar">

## Magic Jar

Range: 60'

Magic-User 5

Duration: Special

This spell allows the caster to attempt to possess the
body of another living creature. The caster begins by
placing their spirit into a gem, jewel, or large crystal of
some sort within the spell range, called the magic jar.
The caster needs to know where the magic jar is
located, but does not have to be able to see it. While
the caster's spirit is outside their body, that body
appears to all intents and purposes to be dead, but
does not undergo decay as a normal dead body would.

Each round after entering the magic jar the caster's spirit
can attempt to take control of the body of a living
creature within the spell range; the target is allowed a
save vs. Spells to resist. If the saving throw fails, the
spirit of the target (now called the host) is trapped in the
magic jar and the caster's spirit takes possession of the
host's body. Possession of a creature by means of this
spell is blocked by **protection from evil** or a similar
ward.

If the attempt to possess a victim fails, the caster's spirit
remains in the magic jar, and that target creature is
immune to further attempts for the duration of the spell.
The caster may make an attempt to possess another
target on the following round, if desired.

If on the other hand the possession attempt is
successful, the caster may remain in control of the host's
body for as long as desired. The caster's spirit may
return to the magic jar at any time when it is within spell
range, restoring the host's spirit to its own body. The
caster may not return to the same host's body again for
the remainder of the duration of this spell, but may
attempt to possess it again on a subsequent casting.

Whenever the caster's spirit is in the magic jar, it may
choose to return to its own body if it is within spell
range. If the body is not in range, the caster's spirit may
become trapped if no vulnerable creatures are in range.

Whenever the caster's spirit returns to their own body,
the spell ends. There is a 50% chance that the magic
jar will shatter when the spell ends (if the spell did not
end because it was broken), becoming worthless and
unusable.

When the caster's spirit possesses a host, the caster has
access to the physical abilities of the host's body,
including Strength, Dexterity, and Constitution, while
still retaining their own Intelligence, Wisdom, and
Charisma. The caster has access only to their own
knowledge, class and level, attack bonus, saving
throws, spell casting ability, and any other purely
mental capabilities.

The caster does not gain access to supernatural or
otherwise extraordinary powers of the host, and may
not be able to perform physical actions that the caster
has never done before (such as flying, if a winged body
has been possessed). The caster does have access to
the host's sensory capabilities, such as Darkvision, the
enhanced sense of smell of a dog, and so on

If the caster's spirit is in the magic jar, and the jar is
broken (whether by **dispel magic** or physical damage),
the caster's spirit will return to its own body if it is in
spell range; if not, the caster's spirit departs (i.e. the
caster dies). In either case, the spell ends.

If the caster's spirit is driven from the host body by
dispel evil, and the magic jar is in range of the host
body, the caster's spirit returns to the jar and the host's
spirit returns to its body. The caster will not be able to
possess the same host again for the remaining duration
of the spell. If the magic jar is not in range of the host
body, the caster's spirit departs, the host's spirit is freed
from the jar and also departs, and the host's body dies.

If the host's spirit is in the magic jar, and the jar is
broken while in spell range of the host body, the
caster's spirit departs, the host's spirit returns to its body,
and the spell ends. If the jar is broken while out of
range of the host's body, the host's spirit departs, the
caster's spirit is stranded in the host body. Note here
that the spell has not ended. **Dispel evil** can still be
used to drive the caster's spirit from the body, which
departs as noted, ending the spell. A stranded caster
may use another casting of this spell (with another
magic jar, of course) to return to their own body, which
of course kills the host's body.

</div>
<div class="spell" data-tag="Magic Missile" id="Magic Missile">

## Magic Missile

Range: 100'+10'/level

Magic-User 1

Duration: Instantaneous

This spell causes a missile of magical energy to dart forth from the caster's fingertip and strike its target, which must be at least partially visible to the caster, dealing 1d6+1 points of damage. The missile strikes unerringly. Specific parts of a creature can't be singled out. Inanimate objects are not damaged by the spell.

For every three caster levels beyond 1^st^, an additional missile is fired -- two at 4^th^ level, three at 7^th^, four at 10^th^, and the maximum of five missiles at 13^th^ level or higher. If the caster fires multiple missiles, he or she can target a single creature or several creatures. A single missile can strike only one creature. Targets must be designated before damage is rolled.

</div>
<div class="spell" data-tag="Magic Mouth" id="Magic Mouth">

## Magic Mouth

Range: 30'

Magic-User 1

Duration: Special

This spell places a simple form of programmed illusion
on a non-living object within range. When triggered,
the spell causes the illusion of a mouth to appear on the
object and a message to be said aloud. The
enchantment can remain in place indefinitely, but is
expended when triggered (i.e. the message is normally
delivered only once).

The message recounted may be up to three words per
caster level in length. The caster may insert pauses in
the message, but the entire message must be delivered
in a time period of no more than a turn. The voice of
the spell can be made to speak at any volume
attainable by a normal human. It will sound enough
like the caster's own voice to be recognized by a close
associate of the caster, but not identical.

The illusionary mouth moves as if actually speaking the
message being delivered, and remains visible during
pauses. If placed on an artistic depiction of a creature
with a mouth (such as a painting or statue), the spell
can be made to appear to animate the mouth of the
object.

This spell cannot be used to activate magic items which
have command words, nor to activate any other
magical effects.

The caster must choose the conditions under which this
spell is triggered. The conditions may be as
complicated or simple as desired, but must depend only
on sight and hearing; the spell has no other sensory
capabilities. The spell also has no particular
intelligence, and can be fooled by disguises or illusions.
The spell does have the capability to effectively see in
normal darkness, but not in any sort of magical
darkness, and it cannot detect invisible creatures nor
see through doors, walls, or even opaque curtains.
Likewise, stealth or magical silence are effective in
preventing audible triggers. Finally, the spell cannot
detect a character's class, level, ability scores, or any
other feature not obvious to a normal NPC.

Triggers have an effective sensory range of 10 feet per
caster level; sounds, sights, or actions outside that range
will never trigger the spell.

</div>
<div class="spell" data-tag="Massmorph" id="Massmorph">

## Massmorph

Range: 100'+10'/level

Magic-User 4

Duration: 1 hour/level

With this spell the caster causes 1d4+1 man-sized (or smaller) creatures per four caster levels to appear as if they are natural effects of the terrain (for example, trees in a forest, stalagmites in a cave, coral underwater, boulders in a cavern, etc.). All creatures to be affected must be within a 120' radius of the caster at the time the spell is cast. Only those creatures the caster wishes to hide are affected, and then only if they are willing to be concealed. The caster may include himself or herself among the affected creatures.

Those affected are thus concealed from other creatures passing through the area for so long as they remain still. If an affected creature chooses to move or attack, the illusion is dispelled for that creature, but those who remain still continue to be hidden. The caster may end the spell early if he or she wishes by speaking a single word. The illusion can also be ended by **dispel magic**.

</div>

<div class="spell" data-tag="Mind Control" id="Mind Control">

## Mind Reading

Range: 60'

Magic-User 2

Duration: 1 turn/level

This spell, sometimes incorrectly called **ESP**, permits
the caster to hear (and possibly see, if the target
visualizes anything) the surface thoughts of one or more
living creatures within range. The caster must designate
a direction or select a visible target, and then
concentrate for a turn in order to "hear" the thoughts.
Each turn the caster may choose to "listen" in a different
direction. The caster may stop listening, then resume
again later, so long as the duration has not expired.
The target creature is not normally aware of being spied
upon in this way, though any creature already under
the effect of this spell or any similar form of telepathy
will instantly know and be able to sense the direction of
the caster.

Rock more than 2 inches thick or even a very thin
covering of lead or gold will block the spell. All undead
creatures are immune to this effect, as are mindless
creatures and constructs such as golems.

</div>

<div class="spell" data-tag="Mirror Image" id="Mirror Image">

## Mirror Image

Range: Self

Magic-User 2

Duration: 1 turn/level

This spell allows the caster to create multiple illusory
duplicates (called figments) which seem to swirl and
move around and through each other as well as the
caster more or less constantly, making it impossible for
most creatures to determine which is the real one. A
total of 1d4 images plus one image per three caster
levels (maximum eight images total) are created.

The figments mimic the caster's actions, going through
the motions of casting spells, drinking potions,
levitating, and so on, just as the caster does. Figments
always look exactly like the caster.

Any opponent who attacks or casts spells directly on the
caster will always hit a figment instead. Attacking a
figment destroys it, whether or not the attack roll is
successful, as does any attack spell directed at one.
Area-effect spells are not cast directly on the caster, and
thus appear to affect all figments exactly as they affect
the caster; for instance, if the caster is subjected to a
**fireball**, all figments will appear to be injured just as the
caster was

</div>
<div class="spell" data-tag="Neutralize Poison*" id="Neutralize Poison*">

## Neutralize Poison*

Range: Touch

Cleric 4

Duration: Instantaneous

This spell detoxifies any sort of venom in the creature or object touched. A poisoned creature suffers no additional effects from the poison; if cast upon a creature slain by poison in the last 10 rounds, the creature is revived with 1 hit point. If cast upon a poisonous object (weapon, trap, etc.) the poison is rendered permanently ineffective.

Reversed, this spell becomes **poison**. The caster must make a successful attack roll; if the attack is a success, the target must save vs. Poison or die. The caster's touch remains poisonous for 1 round per level of ability, or until discharged (i.e. only one creature can be affected by the reversed spell).

</div>
<div class="spell" data-tag="Passwall" id="Passwall">

## Passwall

Range: 30'

Magic-User 5

Duration: 3 turns

Passwall creates a passage through wooden, plaster, or stone walls, but not through metal or other harder materials. The passage is up to 10 feet deep plus an additional 10 feet deep per three caster levels above 9^th^ (20 feet at 12^th^, 30 feet deep at 15^th^, 40 feet deep at 18^th^). If the wall's thickness is more than the depth of the passage created, then a single passwall simply makes a niche or short tunnel. Several passwall spells can then form a continuing passage to breach very thick walls. When passwall ends (due to duration, **dispel magic**, or caster's choice), creatures within the passage are ejected out the nearest exit.

</div>

<div class="spell" data-tag="Permanency" id="Permanency">
## Permanency
 
Range: 10'

Magic-User 6

Duration: Permanent

This spell is used to make another spell of 6th or lower level permanent. Only arcane magic can be affected: Clerical, Druidic, and other spells of divine nature can not be made permanent. No spell with a permanent or instantaneous duration can be made permanent.

A permanency spell lasts until dispelled. When it is dispelled, the other spell effect vanishes immediately. Casting a permanency spell causes the loss of 1 point of Constitution. Lost Constitution is recovered using the [Constitution Point Losses rules](combat.html#constitution-point-losses).

No more than two spells can be made permanent on a single person, item or place. If a third **Permanency** spell is cast it automatically fails, and there is a 50% that each of the two other permanency spells fails too.

A **Permanency** spell is not necessary to make any magical item; using permanency to bind a spell to an object, person, or place is not the same as crafting a magic item.

Spells that are commonly made permanent on a creature: [Detect Magic](allSpells.html#detect-magic), [Protection From Evil](allSpells.html#protection-from-evil), [Read Languages](allSpells.html#read-languages), [Read Magic](allSpells.html#read-magic), [Tongues](allSpells.html#tongues), [Detect Invisible](allSpells.html#detect-invisible), and [Fly](allSpells.html#fly).

Spells commonly made permanent on items or locations include: [Alarm](allSpells.html#alarm), [Animate Objects](allSpells.html#animate-objects), [Confusion](allSpells.html#confusion), [Dancing Lights](allSpells.html#dancing-lights), guards and wards, [Invisibility](allSpells.html#invisibility), [Phantasmal Force](allSpells.html#phantasmal-force), [Private Sanctum](allSpells.html#private-sanctum), [Magic Mouth](allSpells.html#magic-mouth), [Symbol of Pain](allSpells.html#symbol-of-pain),[Wall of Fire](allSpells.html#wall-of-fire), and [Web](allSpells.html#web).
</div>

<div class="spell" data-tag="Phantasmal Force" id="Phantasmal Force">

## Phantasmal Force

Range: 180'

Magic-User 2

Duration: concentration

This spell creates the visual illusion of an object, creature (or small group of creatures), or other effect, as visualized by the caster up to a maximum size of 20'x20'x20'. The illusion does not create sound, smell, texture, or temperature. The caster can animate the image within the limits of the area of effect. The image persists so long as the caster concentrates upon it.

If used to create the illusion of one or more creatures, they will have an Armor Class of 11 and will disappear if hit in combat. Damage done by monsters, spells, etc. simulated by this spell is not real; those "killed" or otherwise apparently disabled will wake up uninjured (at least from this spell) after 2d8 rounds. The illusory damage done will be equivalent to the normal damage for any attack form simulated.

Attempting to animate more creatures than the caster's level grants viewing creatures with at least average Intelligence an immediate save vs. Spells to recognize the creatures as illusions; those making the save will be unaffected by any actions taken by the illusions from that point on. A similar save may be granted by the GM any time he or she feels the illusion is likely to be seen through, especially if the player describes an illusion which seems improbable or otherwise poorly conceived.

</div>
<div class="spell" data-tag="Polymorph Other" id="Polymorph Other">

## Polymorph Other

Range: 30'

Magic-User 4

Duration: Permanent

This spell allows the caster to change one target into another form of living creature. The assumed form can't have more hit dice than caster's level, or be incorporeal or gaseous. Unlike **polymorph self**, the transformed target also gains the behavioral and mental traits, any physical attacks, special, supernatural or spell-like abilities of the new form, in addition to the physical capabilities and statistics of such. If the new form is substantially less intelligent, the target may not remember its former life.

The target creature will have the same number of hit points it previously had, regardless of the hit dice of the form assumed. Incorporeal or gaseous creatures are immune to this spell, as noted above. A creature with shape changing abilities such as a doppleganger can revert to its natural form after one round.

Equipment worn or carried will be dropped if the new
form is unable to wear or carry the items. If any such
items would be constricting or physically harmful to the
new form, the transformation slows and alters such that
they are dropped without damage to the items nor
harm to the target creature. If the GM determines that
any items cannot be removed in this way, they must
decide on the exact results.

Unwilling targets that successfully save against Polymorph are not affected. The spell is permanent until dispelled or the creature is slain, at which time the target reverts to his or her original form.

</div>
<div class="spell" data-tag="Polymorph Self" id="Polymorph Self">

## Polymorph Self

Range: Self

Magic-User 4

Duration: 1 hour/level

This spell allows the caster to change into a different
form of living creature. The form assumed may not
have more hit dice than the caster has levels, nor be
incorporeal or gaseous.

The caster assumes the physical nature of the assumed
form while retaining their mental and spiritual
characteristics. They gain the Armor Class and all
physical attacks possessed by the form but does not
gain any special, supernatural or spell-like abilities.
Dragon breath is a special ability, for instance, so were
the caster to assume the form of a dragon they could
use the dragon's normal claw, bite, and tail swipe
attacks, but not the dragon's breath.

If the form assumed is capable of speaking and making
appropriate gestures (as determined by the GM) the
caster may use their own spells in the assumed form.

Equipment worn or carried will be dropped if the new
form is unable to wear or carry the items. If any such
item would be constricting or physically harmful to the
new form, the transformation slows and alters such that
the item is dropped without damage to the items nor
harm to the target creature. If the GM decides that any
such item cannot be removed in this way, the spell fails.

The caster can remain transformed up to one hour per
level of ability, or may choose to end the spell before
that point if they wish.

</div>


<div class="spell" data-tag="Private Sanctum" id="Private Sanctum">
## Private Sanctum
 
Magic-User 5

Range: 30'

Duration: 24 hours

This spell creates a field impenetrable to most kinds of scrutiny. Those looking into the area from outside see only a dark, foggy mass. [Darkvision](dungeonAdventures.html#darkvision) cannot penetrate it. Eavesdroppers do not perceive any sound, no matter how loud, emanating from the area. Those inside the affected area can see and hear outside the affected area normally. Anyone inside the affected area is immune to [ESP](allSpells.html#esp) spells.

Divination spells like [Magic Mirror](allSpells.html#magic-mirror), [Clairvoyance](allSpells.html#clairvoyance), and [Clairaudience](allSpells.html#clairvaudiance) cannot perceive anything within the area.

No speech is possible between those inside and those outside the sanctum. The spell does not prevent other means of communication, such as telepathic communication, or such as that between a Magic-User and a familiar.

Private sanctum does not stop creatures from moving into and out of the area.
</div>


<div class="spell" data-tag="Projected Image" id="Projected Image">

## Projected Image

Range: 240'

Magic-User 6

Duration: 6 turns

This spell creates a quasi-real, illusory version of the
caster. This illusory projected image looks, sounds, and
smells like the caster, in addition to mimicking gestures
and actions (including speech, which is projected from
the caster to the illusory image as if by a form of
**ventriloquism**). Any further spells cast seem to
originate from the illusion, not the actual caster.

A line of sight between the caster and their illusory self
must be maintained or the spell ends. Any effect or
action that breaks the line of sight dispels the image, as
does the illusionary caster being struck in combat. Note
that this spell grants no special sensory powers to the
caster; for example, if the illusory self is positioned so as
to be able to see something the caster can't directly see,
the caster does not see it. Also, all spell ranges are still
figured from the caster's actual position, not the illusory
self's position.

</div>
<div class="spell" data-tag="Protection from Evil*" id="Protection from Evil*">

## Protection from Evil*

Cleric 1, Magic-User 1

Range: Touch

Duration: 1 turn/level

This spell protects the caster or a creature touched by
the caster (the "subject") from evil; specifically, the spell
wards against summoned creatures, creatures with
significantly evil intentions, and extraplanar creatures of
evil nature. A magical barrier with a radius of just 1
foot is created around the subject. The barrier moves
with the subject, and provides three specific forms of
magical protection against attacks or other effects
attempted by the affected creatures against the subject.

First, the subject receives a bonus of +2 to their Armor
Class, and a similar bonus of +2 on all saving throws.
Second, the barrier blocks all attempts to **charm** or
otherwise control the subject, or to possess the subject
(such as with **magic jar**). Such attempts simply fail
during the duration of this spell. Note however that a
creature who receives this protection after being
possessed is not cured of the possession.

Third, any and all summoned creatures and extraplanar
creatures of evil nature are unable to physically touch
the subject. Attacks by such creatures using their
natural weapons simply fail. This effect is canceled if
the subject performs any form of physical attack (even
with a ranged weapon) on any affected creature, but
the other features of the spell continue in force.

Reversed, this spell becomes **protection from good**. It
functions in all ways as described above, save that
"good" creatures are kept away, rather than "evil" ones.

</div>
<div class="spell" data-tag="Protection from Evil 10' Radius*" id="Protection from Evil 10' Radius*">

## Protection from Evil 10' Radius*

Cleric 4, Magic-User 3

Range: Touch

Duration: 1 turn/level

This spell functions exactly as **protection from evil**, but with a 10' radius rather than a 1' radius. All within the radius receive the protection; those who leave and then re-enter, or who enter after the spell is cast, receive the protection as well.

Reversed, this spell becomes **protection from good 10' radius**, and functions exactly as the reversed form of **protection from evil**, except that it covers a 10' radius around the target rather than the normal 1' radius.

</div>
<div class="spell" data-tag="Protection from Normal Missiles" id="Protection from Normal Missiles">

## Protection from Normal Missiles

Magic-User 3

Range: Self

Duration: 1 turn/level

The caster is completely protected from small sized, non-magical missile attacks. Therefore, magic arrows, hurled boulders, or other such are not blocked, but any number of normal arrows, sling bullets, crossbow bolts, thrown daggers, etc. will be fended off. Note that normal missiles projected by magic bows count as magical missiles for the purposes of this spell.

</div>
<div class="spell" data-tag="Purify Food and Water" id="Purify Food and Water">

## Purify Food and Water

Cleric 1

Range: 10'

Duration: Instantaneous

With this spell the caster makes contaminated food or
water pure and safe to eat or drink. Poison is
neutralized and spoilage is reversed by this spell. The
spell does not protect against future decay, however,
nor does it affect magic potions (including,
unfortunately, **Potions of Poison**). Unholy water, if it
exists in your campaign, is ruined by the casting of this
spell. The spell affects about 2 pounds of food and/or
drink per caster level; note that a quart of water or
similar drink weighs just over 2 pounds.

</div>
<div class="spell" data-tag="Quest*" id="Quest*">

## Quest*

Range: 5'/level

Cleric 5

Duration: Special

By means of this spell the caster compels a living
creature to perform some specific action or services, or
alternately to avoid performing some action. The target
creature must be able to hear and understand the
caster, or it cannot be affected. This spell will
automatically fail if used to compel a creature to engage
in some obviously self-destructive action.

A saving throw vs. Spells will allow an unwilling target
to resist a quest when it is first cast. However, the
target may choose to accept the quest, typically as part
of a bargain with the caster to perform some service.
Once subjected to this spell, the subject must obey the
instructions given by the caster indefinitely, though if
the quest is to perform some action the spell effectively
ends when that action has been completed.

For every 24 hours that an affected creature chooses
not to obey the quest (or is prevented from obeying it),
it suffers 3d6 points of damage. This damage is limited,
in that it will not kill the target; if the damage is enough
to do so, roll 1d4 for the number of hit points the
affected creature retains (similar to the spell **harm**, the
reverse of **heal**).

If the task assigned to the subject of this spell is open-
ended or otherwise unable to be completed, the subject
is still compelled to try to perform the task, but the spell
will end in no more than one day per caster level.

Very clever creatures may be able to subvert the
instructions given; the GM must decide on the results of
any such attempts.

A quest (and all effects thereof) can be ended by a
**remove curse** spell from a caster two or more levels
higher than the caster of the quest, or by a wish, or by
the reverse of this spell. **Dispel magic** does not affect a
quest spell.

</div>
<div class="spell" data-tag="Raise Dead*" id="Raise Dead*">

## Raise Dead*

Range: Touch

Cleric 5

Duration: Instantaneous

This spell restores life to a deceased humanoid (as
defined in **charm person**). The caster can only raise a
being that has not been dead for more days than the
caster has levels. The spirit of the target of this spell
must be willing to return. If the target's spirit is trapped
or contained in any way, the spell will fail. It will also
fail if the target died of old age, as the body simply has
no life left in it. Similarly, undead creatures are not
affected by this spell as they can no longer be returned
to life in any normal sense.

The body of the target must be adequately intact to
support life, but all wounds no matter how major are
healed. Body parts missing when the target is raised
are still missing afterward. Normal poison and normal
disease are cured in the process of raising the subject,
but magical diseases and curses are not undone.

Creatures brought back from the dead always suffer
some loss or penalty from the ordeal. Characters lose
one level of ability permanently (i.e. it does not accrue
a negative level, but rather loses an actual level, being
reduced to the minimum number of experience points
required for the previous level). First level characters
are reduced to Normal Man status; if the character was
already a Normal Man they lose a point of Constitution.
These losses are permanent, though of course the
character may gain levels in the normal fashion.
(Characters reduced to Normal Man status must gain
1,000 XP to return to 1st level).

Monstrous humanoids (orcs, goblins, and the like) lose
one hit die, or are reduced to ½ hit dice if the monster
has just one to start with. Such humanoids who
already have ½ hit dice are reduced to a single hit point.
These losses are generally permanent, though the GM
may allow such creatures in service to a player
character to recover by gaining 1,000 XP per hit die the
creature would be returning to (so a lizard man who has
been reduced to 1 hit die must earn 2,000 XP to return
to its original 2 hit dice); treat such a creature as being a
retainer for this purpose.

Upon being raised, the target has 1 hit point per level or
hit die (using its current reduced figure, of course), with
a minimum of 1 hit point. A character who died with
spells prepared has none prepared upon being raised.

The reverse of this spell, **slay living**, will kill instantly
the creature touched (which may be of any sort, not
just a humanoid) unless a save vs. Spells is made. If
the saving throw is successful, 2d6 points of damage is
dealt to the victim instead. An attack roll is required to
apply this spell in combat.

</div>
<div class="spell" data-tag="Read Languages" id="Read Languages">

## Read Languages

Range: 0

Magic-User 1

Duration: Special

This spell grants the caster the ability to read almost any written language. It may be cast in one of three modes:

In the first mode, the spell allows the caster to read any number of written works in a variety of languages. This mode lasts for 1 turn per caster level.

In the second mode, the spell allows the caster to read any one book or tome; this mode lasts 3 hours per caster level.

In the third mode, the spell allows the caster to read any one non-magical scroll or other single-sheet document; this mode is permanent.

This spell does not work on any sort of magical text, such as spell scrolls or spellbooks; see **read magic**, below, for the correct spell to use in such cases.

The spell grants the ability to read the texts, but does not in any way hasten the reading nor grant understanding of concepts the caster doesn't otherwise have the ability to understand. Also, for this spell to function, there must be at least one living creature that can read the given language somewhere on the same plane. The knowledge is not copied from that creature's mind; rather, it is the existence of the knowledge that enables the spell to function.

</div>
<div class="spell" data-tag="Read Magic" id="Read Magic">

## Read Magic

Range: 0

Magic-User 1

Duration: Permanent

When cast upon any magical text, such as a spellbook or magic-user spell scroll, this spell enables the caster to read that text. Casting this spell on a cursed text will generally trigger the curse. All Magic-Users begin play knowing this spell, and it can be prepared even if the Magic-User loses access to his or her spellbook.

</div>
<div class="spell" data-tag="Regenerate" id="Regenerate">

## Regenerate

Range: Touch

Cleric 6

Duration: Permanent

This spell causes the subject's severed body members (fingers, toes, hands, feet, arms, legs, tails, or even heads of multiheaded creatures), broken bones, and ruined organs to grow back. After the spell is cast, the physical regeneration is complete in 1 round if the severed members are present and touching the creature. Otherwise, a full turn is required for the regeneration to complete.

This spell also heals 3d8 points of damage. Regenerate has no effect on nonliving creatures or constructs (including undead).

</div>
<div class="spell" data-tag="Reincarnate" id="Reincarnate">

## Reincarnate

Range: Touch

Magic-User 6

Duration: Instantaneous

By touching the body of a deceased humanoid (as
defined in **charm person**), the caster brings them back
in an entirely new body. The whole body is not
needed; in fact, even the smallest fragment of body is
sufficient, so long as that fragment was part of the body
at the time of the target's death.

The caster can only reincarnate a being that has not
been dead for more than a week. The spirit of the
target of this spell must be willing to return. If the
target's spirit is trapped or contained in any way, the
spell will fail.

Roll on the following table to determine what sort of creature the character becomes:

```{ojs}

import {generalTableSelect} from "./custom.js"

viewof reincarnate = Inputs.button(html`<button style="color: black; background-color: lightgray;">Roll on Table</button>`, {value: 0, reduce: () => highlightTableRow("#reincarnate-spell", generalTableSelect([1,100,0],[[1,1],[2,15],[16,29],[30,30],[31,39],[40,46],[47,60],[61,88],[89,91],[92,93],[94,98],[99,100]]))})

```
<br>

:::{#reincarnate-spell}

| d% | Incarnation |
|----|----|
| 01 | Bugbear |
| 02--15 | Dwarf |
| 16--29 | Elf |
| 30 | Gnoll |
| 31--39 | Gnome |
| 40--46 | Goblin |
| 47--60 | Halfling |
| 61--88 | Human |
| 89--91 | Kobold |
| 92--93 | Lizard Man |
| 94--98 | Orc |
| 99--100 | Choice* |

:::

If "choice" is rolled for a player character being
reincarnated, the player is allowed to choose the new
form from among those on the table above. If an NPC
is being reincarnated, the GM may choose or roll again.

When the spell is cast, a new body forms in a nearby
location selected by the caster. The body forms over a
period of 6 turns (i.e. an hour), first as a misty outline,
then becoming more solid moment by moment until it
takes its first breath and awakens. The new form is a
young adult, unless the target was younger than that
when they died, in which case the new body is the
same age as the deceased body.

The target creature's new body has obviously suffered
none of the harm that may have befallen the old one,
and is completely healthy (at least, to start with).

The target remembers their previous life, and retains
the same class (if possible for the new form) as well as its Intelligence, Wisdom, and Charisma. Strength,
Dexterity, and Constitution scores should be rerolled.
(If the character's ability scores are outside the allowable
range for the new form, they should be adjusted up or
down by the GM as needed.) The target loses one
level (or hit die); this is a real reduction, not a negative
level, and is not subject to magical **restoration**. The
target's hit points should be rerolled completely, as this
is an entirely new body. If the target was 1st level,
instead of a hit point reduction its new Constitution
score is reduced by 2

Characters turned into non-character humanoids (such
as an elf who returns as a kobold) will require
adjudication by the GM; if the restored target is a player
character, the GM is counseled to give as much leeway
to the player as possible with the character's new form.
Conversely, non-character humanoids who return as
characters will need all ability scores rolled; such
characters will usually be fighters with a level equal to
the target's previous hit dice minus 1, or as Normal Men
if the target's previous hit dice were 1 or less.

Undead creatures are not affected by this spell; such
creatures can no longer be returned to life in any
normal sense.

</div>
<div class="spell" data-tag="Remove Curse*" id="Remove Curse*">

## Remove Curse*

Range: 30'

Cleric 3, Magic-User 4

Duration: Instantaneous

This spell removes any and all ordinary curses afflicting
a creature. It does not generally remove the curse from
a magic item such as a sword or suit of armor, but a
character afflicted by a cursed item of this type will be
freed of it long enough to discard the item (a turn, at
least).

Some special curses are more difficult to remove, and
may require a caster of a certain minimum level. A
very few curses created by godlike beings cannot be
removed by this spell at all.

The reverse of this spell, bestow curse, allows the
caster to place a curse on the subject. A save vs. Spells
is allowed to resist. The caster must choose one of the
following three effects:

* -4 decrease to an ability score (minimum 1).

* -4 penalty on attack rolls and saves.

* Each round of combat, the target has a 50% chance to act normally; otherwise, it takes no action.

The caster may also invent his or her own curse, but it should be no more powerful than those described above. The curse thus bestowed cannot be dispelled, but it can be removed with a **remove curse** spell.

</div>
<div class="spell" data-tag="Remove Fear*" id="Remove Fear*">

## Remove Fear*

Range: Touch (120')

Cleric 1

Duration: Instantaneous (2 turns)

This spell will calm the creature touched. If the target creature is currently subject to any sort of magical fear, it is allowed a new save vs. Spells to resist that fear, at a bonus of +1 per level of the caster.

The reverse of this spell, **cause fear**, causes one target creature within 120' to become frightened; if the target fails to save vs. Spells, it flees for 2 turns. Creatures with 6 or more hit dice are immune to this effect.

</div>
<div class="spell" data-tag="Resist Cold" id="Resist Cold">

## Resist Cold

Range: Touch

Cleric 1

Duration: 1 round/level

This spell makes the caster, or any living creature the
caster touches, completely immune to normal cold.
The spell also gives protection against magical or
otherwise superior cold such as the breath of an Ice
Dragon or the **ice storm** spell. Specifically, the spell
gives the protected creature a bonus of +3 on all saving
throws against such effects, and reduces any damage
suffered by half (so that for example a successful save
vs. the Ice Dragon's breath would reduce damage to
just one-fourth normal, and even if the saving throw
fails the protected creature only takes half damage).

</div>
<div class="spell" data-tag="Resist Fire" id="Resist Fire">

## Resist Fire

Range: Touch

Cleric 2

Duration: 1 round/level

This spell makes the caster, or any living creature the
caster touches, completely immune to normal heat or
fire. The spell also gives protection against magical or
otherwise superior heat or fire such as the breath of a
Mountain Dragon or the **fireball** spell. Specifically, the
spell gives the protected creature a bonus of +3 on all
saving throws against such effects, and reduces any
damage suffered by half (so that for example a
successful save vs. the **fireball** spell would reduce
damage to just one-fourth normal, and even if the
saving throw fails the protected creature only takes half
damage).

</div>
<div class="spell" data-tag="Restoration" id="Restoration">

## Restoration

Range: Touch

Cleric 6

Duration: Permanent

Each casting of the spell removes a single negative level from a creature who has suffered energy drain. At 16th level, two negative levels may be removed. See the rules for Energy Drain (in the [Encounter](combat.qmd#energy-drain) section) for more details.

Alternately, this spell can be used to restore drained ability score points. If applied to a character who has suffered temporary loss of ability points, it will restore up to 1d4 lost points to any one drained ability immediately. If applied to a character who has suffered permanent loss of ability points, 1 point can be restored.

Restoration does not restore levels lost due to death (as described for the spell **raise dead**).

</div>
<div class="spell" data-tag="Shield" id="Shield">

## Shield

Range: Self

Magic-User 1

Duration: 5 rounds+1/level

Shield creates an invisible, shield-like mobile disk of force that hovers in front of the caster. It negates **magic missile** attacks directed at the caster, and improves the caster's Armor Class by +3 vs. melee attacks and +6 vs. missile weapons. The Armor Class benefits do not apply to attacks originating from behind the caster, but **magic missiles** are warded off from all directions.

</div>
<div class="spell" data-tag="Silence 15' Radius" id="Silence 15' Radius">

## Silence 15' Radius

Cleric 2

Range: 360'

Duration: 2 rounds/level

This spell creates a spherical area with a 15 foot radius
where no sound will pass. No one within the affected
area can make nor hear any sound. Neither does
sound issue from the affected area; those outside
cannot hear those inside. This effect blocks verbal
communication, of course, as well as spell casting.

This effect can be cast in a fixed area, upon an item
(making it portable), or upon a creature. An unwilling
target receives a save vs. Spells to negate the spell. If
an item in another creature’s possession is targeted, that
creature also receives a save vs. Spells to negate.

This spell can be used to protect against any kind of
attack or magic where the victims must be able to hear
the attacker, for such attacks cannot pass into or out of
the affected area

</div>
<div class="spell" data-tag="Sleep" id="Sleep">

## Sleep

Range: 90'

Magic-User 1

Duration: 5 rounds/level

This spell puts several creatures of 3 or fewer hit dice,
or a single 4 hit die creature, into a magical slumber.
Creatures of 5 or more hit dice are not affected. The
caster chooses a point of origin for the spell (within the
given range, of course), and those creatures within 30'
of the chosen point may be affected. Each creature in
the area of effect is allowed a save vs. Spells to resist.

Victims of this spell can always be hit if attacked.
Injuring such a creature will cause it to awaken, and it
may begin fighting back or defending itself on the very
next round. Slapping or shaking such a creature will
awaken it in 1d4 rounds, but normal noises will not.

Sleep does not affect unconscious creatures, constructs,
or undead creatures.

When the duration elapses, the sleeping creatures
normally wake up immediately; however, if they are
made very comfortable and the surroundings are quiet,
the affected creatures may continue sleeping normally
at the GM's option.

</div>
<div class="spell" data-tag="Speak with Animals" id="Speak with Animals">

## Speak with Animals

Cleric 2

Range: special

Duration: 1 turn/4 levels

This spell allows the caster to speak to and understand
any single animal (normal or giant sized, but not
magical or monstrous) that is in sight of the caster and
able to hear them. The caster may change which
animal they are speaking with at will, once per round.
The spell doesn’t alter the animal’s reaction or attitude
towards the caster; a standard reaction roll should be
made to determine this. The GM should ensure that
the animal's manner of speaking reflects its intelligence
and nature

</div>
<div class="spell" data-tag="Speak with Monsters" id="Speak with Monsters">

## Speak with Monsters

Cleric 6

Range: special

Duration: 1 turn/5 levels

This spell allows the caster to speak to and understand
any single living monster that is in sight of the caster
and able to hear them. The caster may change which
monster they are speaking with at will, once per round.
Others able to understand the language spoken by the
target monster (if any) will be able to understand the
caster. The spell doesn’t alter the monster’s reaction or
attitude towards the caster. Mindless monsters, plant
creatures and undead are unaffected by this spell.

</div>
<div class="spell" data-tag="Speak with Plants" id="Speak with Plants">

## Speak with Plants

Range: 20'

Cleric 4

Duration: 1 turn

This spell allows the caster to speak to and understand
any single plant (either normal plant or animate plant
creature). The GM should remember that normal
plants have a limited sense of their surroundings, and
most never move from the place where they sprouted.
The spell doesn’t alter the plant’s reaction or attitude
towards the caster; however, normal plants will
generally communicate freely with the caster, as they
have nothing else of importance to do. Plant creatures
will tend to be slightly more intelligent, and a reaction
roll should be used to determine how such creatures
respond to the caster's words.

</div>
<div class="spell" data-tag="Speak with Dead" id="Speak with Dead">

## Speak with Dead

Range: 10'

Cleric 3

Duration: 3 rounds/level

With this spell the caster causes the corpse of an
intelligent creature to become animated and to answer
the caster's questions. It does not matter how long the
corpse has been dead, but it must be essentially intact
with at least a comple
te mouth in order to answer
questions.
The corpse will answer at most one question per two
caster levels, but if the duration expires any remaining
questions are lost. The corpse only knows what it knew
when it was alive; this includes the languages it knew in
life. Thus, the caster must share a language with the
deceased in order to get any questions answered at all.

The answers given are drawn from knowledge
"imprinted" on the corpse during life; the caster does
not in any case actually communicate with the spirit of
the deceased creature. The corpse cannot retain any
information given to it, and does not even remember
any previous instances of communication via this spell.

The answers given may not be useful for various
reasons. If the corpse knew the caster when it was
alive, or if the caster is a member of a group the
deceased disliked, it may choose to lie or mislead the
caster. If the caster asks the corpse questions of a
personal nature, or questions that indicate the caster
may be working against whatever interests the corpse
had in life, it will almost certainly seek to mislead the
caster.

If the corpse has been roused by this spell within the
last seven days, the spell will fail. Undead creatures
(including the remains of defeated undead creatures)
cannot be affected by this spell.

</div>
<div class="spell" data-tag="Spiritual Hammer" id="Spiritual Hammer">

## Spiritual Hammer

Range: 30'

Cleric 2

Duration: 1 round/level

This spell causes a warhammer made of pure force to spring into existence, attacking any foe chosen by the Cleric within range once per round. It deals 1d6 hit points of damage per strike, +1 point per three caster levels (maximum of +5). It uses the caster's normal attack bonus, striking as a magical weapon, and thus can inflict damage upon creatures that are only hit by magic weapons. If the hammer goes beyond the spell range, the Cleric loses sight of it, or the caster ceases to direct it, the hammer disappears. The hammer cannot be attacked or harmed by physical attacks, but **dispel magic**, **disintegrate**, or a **rod of cancellation** will dispel it.

</div>
<div class="spell" data-tag="Sticks to Snakes" id="Sticks to Snakes">

## Sticks to Snakes

Range: 120'

Cleric 4

Duration: 6 turns

This spell transforms normal wooden sticks into 1d4 hit dice worth of normal (not giant) snakes per every four caster levels. (See the **Monsters** section for details on types of [snakes](monstersAll.qmd#snake-giant-rattlesnake).) The snakes follow the commands of the caster. When slain, dispelled, or the spell expires, the snakes return to their original stick form. Magical "sticks" such as enchanted staves cannot be affected.

</div>
<div class="spell" data-tag="Striking" id="Striking">

## Striking

Range: Touch

Cleric 3

Duration: 1 round/level

This spell bestows upon one weapon the ability to deal 1d6 points of additional damage. This extra damage is applied on each successful attack for the duration of the spell. It provides no attack bonus, but if cast on a normal weapon, the spell allows monsters only hit by magical weapons to be affected; only the 1d6 points of magical damage applies to such a monster, however.

</div>
<div class="spell" data-tag="Telekinesis" id="Telekinesis">

## Telekinesis

Range: Self

Magic-User 5

Duration: 3 turns

This spell permits the caster to move objects or
creatures by concentration alone; the caster can move
such things weighing up to 50 pounds per caster level
at a rate of up to 20 feet per round. Creatures targeted
by this spell are allowed a saving throw vs. Death Ray
to resist, whether it is the creature itself being affected
or an object in its possession.

In order to use this power the caster must maintain
concentration, moving no more than normal movement
(no running), making no attacks and casting no further
spells. If concentration is lost (whether intentionally or
not), the power may be used again on the next round
but the target of the effect is allowed a new saving
throw.

</div>
<div class="spell" data-tag="Teleport" id="Teleport">

## Teleport

Range: Self

Magic-User 5

Duration: Instantaneous

The caster of this spell is instantly transported to
another location up to 100 miles away per level of
ability. The spell transports the caster only within their
current plane of existence.
Other creatures
(passengers) and inanimate objects (cargo) may be
transported along with the caster, up to a maximum of
300 pounds plus 100 pounds per level above 10th.
The caster must be in contact with all objects and/or
creatures to be transported (although creatures to be
transported may be in contact with one another, with at
least one of those creatures in contact with the caster).
Unwilling creatures are allowed a saving throw vs.
Spells to resist the spell, and the caster may need to
make an attack roll to make contact with such a
creature. Likewise, a successful save vs. Spells will
prevent items in a creature's possession from being
teleported.

The spell is directed by the mind of the caster, who
must visualize the destination area; failure to visualize it
properly can cause the spell to fail in a variety of ways,
and destinations heavily saturated with magical energy
(as defined by the Game Master) will cause the spell to
fail automatically.

To determine the results of this spell, roll d% and consult the table below. Below the table is an explanation of the terms used.

| Knows Well | Knows Somewhat | Saw Once | Spell Result | 
|------------|----------------|----------|--------------|
| 01         | 01--02         | 01-03    | Disaster     |
| 02         | 03--07         | 04--13   | Wrong Place  |
| 03         | 08--13         | 14--25   | Fell Short   |
| 04--100    | 14--00         | 26--100  | Success!     |


**Knows Well** applies when the caster has visited the
destination frequently and/or spent a substantial
amount of time there; generally, the caster should have
spent at least 7 days (not necessarily in a row) at the
destination within the last year to qualify for this
category. Any place where the caster lived for more
than a month in the last ten years, or more than a year
in their life, also qualifies.

**Knows Somewhat** applies when the caster has spent
substantial time in the destination area, but not enough
to qualify for Knows Well. Alternately, the caster may
have made an in-depth study of the area, looking at
accurate drawings, maps, and floorplans or spending
hours listening to descriptions from one or more people
who Know Well the destination.

**Saw Once** applies when the caster has visited a place
for as much as a day, but no more, or when the caster
has attempted the study required for the second
definition of Knows Somewhat but has failed to acquire
enough information (in the GM's opinion).

**If the caster attempts to travel to a location that
does not exist**, or perhaps once existed but has been
destroyed or otherwise changed so much that the caster
would not recognize it, roll 2d20 instead d% for the
result of the casting. In this case, if Success! is rolled
the spell simply fails and no one is transported
anywhere.

**Success!** means exactly what it says. The caster,
passengers, and cargo arrive safely exactly where the
caster intended

**Fell Short** indicates that the caster, passengers, and
cargo arrive safely 1d8x10% of the way to the intended
destination. Note that arriving "safely" does not mean
that the destination is safe, but only the trip

**Wrong Place** means that the caster, passengers, and
cargo arrive at some place that resembles the intended
destination. This means that the caster appears in the
closest similar place within range, as decided by the
GM. If no such area exists within the spell’s range, the
spell simply fails instead.

**Disaster** indicates that the caster, passengers, and
cargo have encountered dimensional turbulence and
have crashed, becoming separated (if passengers
and/or cargo accompanied the caster) and being injured
in the process. Each creature including the caster
suffers 1d12 points of damage, and then rolls again on
the same column using 2d20 instead of d%. If another
Disaster is rolled for any creature, apply another 1d12
points of damage and roll once more. Cargo objects
are not normally damaged but the result must be rolled
for each such item to determine where it has appeared;
in this case, if Disaster is rolled the cargo item
disappears forever.

</div>

<div class="spell" data-tag="Tongues" id="Tongues">
## Tongues

Cleric 3, Magic-User 2

Range: Touch

Duration: 1 turn/level

This spell allows the creature touched to speak and understand any language or dialect. Only one language can be spoken at a time, but any number can be understood. This spell does not alter other creatures’ dispositions and does not allow the affected creature to speak to creatures that cannot understand language.
</div>

<div class="spell" data-tag="True Seeing" id="True Seeing">

## True Seeing

Range: Touch

Cleric 5

Duration: 1 round/level

This spell confers on the target the ability to see all things as they actually are. The subject sees through normal and magical darkness, notices secret doors, sees the exact locations of displaced creatures or objects, sees through normal or magical disguises, sees invisible creatures or objects normally, sees through illusions, and sees the true form of polymorphed, changed, or transmuted things. The range of true seeing conferred is 120 feet.

True seeing, however, does not penetrate solid objects. It in no way confers X-ray vision or its equivalent. It does not negate concealment, including that caused by fog and the like. In addition, the spell effects cannot be further enhanced with known magic, so one cannot use true seeing through a **crystal ball** or in conjunction with **clairvoyance**.

</div>
<div class="spell" data-tag="Ventriloquism" id="Ventriloquism">

## Ventriloquism

Range: 60'

Magic-User 1

Duration: 1 turn/level

This spell causes the caster's voice to appear to come
from another location within range, for example, from a
dark alcove or statue. The caster may choose a new
location each round if desired, and can cause the spell
to temporarily abate without ending it and then resume
it again at any time within the given duration

</div>
<div class="spell" data-tag="Wall of Fire" id="Wall of Fire">

## Wall of Fire

Range: 180'

Cleric 5, Magic-User 4

Duration: 1 round/level (or special)

This spell creates a vertical sheet of flames in an area
indicated by the caster, which is either a wall of flame
up to 20' in length per caster level, or a ring with a
radius up to 5' per caster level. The caster may choose
to make the wall smaller if desired. The wall may be up
to 20' tall (as desired by the caster and/or constrained
by the ceiling). The entire wall must lie within the range
given above. One or both sides of the wall may be hot,
as determined by the caster at the time of casting.
Once created, the wall cannot be moved or changed.

Any creature within 20 feet of a hot side of the wall will
suffer 1d4 points of damage each round, or 2d4 points
if within 10 feet. Damage is applied on the round the
spell is cast and each round thereafter. Actually passing
through the wall causes 2d6 points of damage, plus 1
per caster level, even if the side the character or
creature entered from was not a hot side.

Undead creatures are particularly susceptible to this
spell, and suffer twice the damage described above.

If the caster evokes the wall so that it appears where
creatures are, each creature takes damage as if passing
through the wall; a save vs. Spells is allowed, with
success indicating that damage is rolled as if the
creature is within 10' of the wall.

The caster may choose to maintain the spell indefinitely
(within reasonable limits of endurance) by
concentration, or may cast it with the standard duration
of 1 round per level, at their option

</div>
<div class="spell" data-tag="Wall of Iron" id="Wall of Iron">

## Wall of Iron

Range: 90'

Magic-User 6

Duration: Permanent

Using this spell the caster creates an iron wall. The wall
stands upright, and consists of up to one 10'x10' square
section, one inch thick, per caster level. The caster can
increase the thickness of the wall with a proportionate
reduction in the area; for example, doubling the
thickness halves the area. The caster may choose to
make the wall smaller than the maximum size if desired.
The wall may not be made less than one inch thick, and
must always be created in contact with the ground or
floor beneath it. It is always a flat plate with no bends,
but the edges do not have to be straight; indeed, the
caster can cause the wall edge to mold itself around any
obstructing object very closely. The wall cannot
otherwise be created such that it occupies the space of
any object or creature.

If the caster wishes, the wall edges will bond to any
inanimate materials they touch (stone walls, soil,
furnishings, and so on). If this is not done, the wall may
be unsupported (as determined by the GM based on
the situation) and will thus likely fall. If left unattended,
there is an equal chance it will fall in either direction in
1d6 rounds, but it can be pushed in a specific direction
by any character having a minimum of Strength score
of 13, or any monster with 4 or more hit dice. Several
creatures can work together to do so if desired. (If the
optional Ability Roll rule is being used, a Strength roll at
-3 is sufficient to topple the wall.)

When the wall falls, any creatures it falls upon are likely
to be injured or killed. If it is possible for a character or
creature to escape the area (i.e. it has sufficient
movement rate and is not otherwise prevented from
doing so), it is allowed to roll a save vs. Death Ray (with
Dexterity bonus added). If this save is successful, the
creature or character moves by the most direct route to
the nearest safe space; if the save fails or it is for some
reason impossible to flee, 10d6 points of damage are
inflicted on that victim. Creatures larger than ogre-sized
are immune to being crushed and will simply be
knocked down if the save fails.

The wall is permanent, as indicated, but being made of
iron is susceptible to rust and corrosion

</div>
<div class="spell" data-tag="Wall of Stone" id="Wall of Stone">

## Wall of Stone

Range: 15' per level

Magic-User 5

Duration: Permanent

Using this spell the caster creates a stone wall. The wall
is composed of up to one 10'x10' square section, one
foot thick, per caster level. The caster can form this
wall into almost any shape, with some restrictions. The
caster can increase the thickness of the wall with a
proportionate reduction in the area; for example,
doubling the thickness halves the area. The wall cannot
be created such that it occupies the space of any object
or creature. It must be adequately supported by
existing stone, which it will bond with automatically, but
need not be supported over its entire area. For
example, a wall of stone may be formed into a bridge
over a stream or chasm, so long as both ends of the
bridge rest solidly upon (and bond with) existing stone.

Bridges longer than 20 feet must be arched, buttressed,
or both in order to stand; this extra construction
reduces the wall's usable volume by half, as does
creating a wall with battlements, crenelations, and
similar basic structural elements. No complex structural
elements may be created by this spell.

Though made by magic, the wall is made of stone and
can be broken or damaged just as if it were ordinary
stone.

The wall can be formed into a container to trap
creatures, and if this is attempted the targets of the spell
are allowed to save vs. Death Ray to avoid being
trapped. If the save is successful the targets are able to
make up to one full move to a space outside the
container.

</div>
<div class="spell" data-tag="Water Breathing" id="Water Breathing">

## Water Breathing

Range: Touch

Magic-User 3

Duration: 2 hours/level

This spell grants living creatures touched by the caster
(including the caster, if desired) the ability to breath in
water as a fish does. The duration may be divided
evenly if the caster touches multiple targets one after
another. Affected targets do not lose the ability to
breathe air.

</div>
<div class="spell" data-tag="Web" id="Web">

## Web

Range: 10' per level

Magic-User 2

Duration: 2 turns/level

This spell creates a volume of sticky strands resembling
a spider's web but much larger and thicker. The spell
fills a volume of up to 8,000 cubic feet (equivalent to
eight 10'x10'x10' cubes). The webs must be attached
to adjacent solid objects such as walls, pillars, and the
like; any unsupported section of webbing collapses to
the ground and disappears. Within this limitation, the
caster may choose any arrangement of webs they wish,
up to the limit of range and the given 8,000 cubic foot
volume. The caster may choose to create a smaller
volume if they wish.

Creatures within the web at the time the spell is cast, as
well as anyone entering the area afterward, will become
entangled. Each should roll a save vs. Death Ray, and
any creatures who succeed at this save may move
through the webbing but are reduced to one-half
normal movement rate. Such creatures may not cast
spells or perform normal attacks; whether other actions
are possible is left to the GM to decide. Once an
entangled creature leaves the area of effect of the web,
it will be able to act normally again.

Those who fail the save are fully entangled and
trapped. They cannot move, cast spells, or perform
normal attacks or any other physical action. Speech
remains possible, however. Creatures with Strength of
13 or higher (or 4 or more hit dice) may be able to
break loose, however; each round, such creatures are
allowed another save vs. Death Ray with results as
given above. Creatures failing the initial save and
having Strength of 12 or less (or fewer than 4 hit dice)
are trapped until the duration expires or the webs are
otherwise removed.

Attacks against an entangled creature by one outside
the webbing will not normally entrap the attacker, so
long as they do not need to venture into the web to
reach the entangled target.

The web can be ignited; any application of fire to the
webbing will cause a 10 foot cube to burn away in one
round, with all 10 foot cubes adjacent to the destroyed
one burning in the next round, and so on. If any part
of the web becomes unsupported it will collapse and
disappear as noted above.

Creatures trapped within the burning web suffer 2d4
points of damage when the cube they are trapped in
burns, but they are thereafter completely free of the
web.

</div>
<div class="spell" data-tag="Wizard Eye" id="Wizard Eye">

## Wizard Eye

Range: 240'

Magic-User 4

Duration: 6 turns

With this spell the caster creates an invisible magical "eye" through which he or she can see. The eye has Darkvision, but otherwise sees exactly as the caster would. It can be created in any place the caster can see, up to a range of 240' away, and thereafter can move at a rate of 40' per round as directed by the caster. The eye will not move more than 240' feet away from the caster under any circumstances. The eye cannot pass through solid objects, but as it is exactly the size of a normal human's eye, it can pass through holes as small as 1 inch in diameter. The caster must concentrate to use the eye.

</div>
<div class="spell" data-tag="Wizard Lock" id="Wizard Lock">

## Wizard Lock

Range: 20'

Magic-User 2

Duration: Permanent

This spell magically holds shut a door, gate, window, or
shutter of wood, metal, or stone. The magic affects the
portal just as if it were securely closed and normally
locked. The effect lasts indefinitely. **Knock** can be
used to open the doorway without ending the spell, and
**dispel magic** can be used to end it permanently. The
caster of this spell can easily open the door or other
portal without ending the spell, as can a Magic-User
three or more levels higher than the caster.

</div>

<div class="spell" data-tag="Word of Recall" id="Word of Recall">

## Word of Recall

Range: Self (special)

Cleric 6

Duration: Instantaneous

With the utterance of a single word this spell transports
the caster to a place of refuge which they designate
when preparing the spell. The place must be Known
Well (as explained for **teleport**) to the caster to be so
designated. This spell cannot transport the caster
beyond their current plane of existence.

The caster can bring along objects or creatures, not to
exceed 300 pounds plus 100 pounds per level above
10th. The caster must be in contact with all objects
and/or creatures to be transported (although creatures
to be transported may be in contact with one another,
with at least one of those creatures in contact with the
caster).

Unwilling creatures cannot be transported by this spell,
nor can items in their possession. If the caster or one of
their passengers is holding an object that is also being
held by an unwilling creature, the latter can retain
possession of the object with a successful save vs.
Spells.

</div>

```{=html}

<script>
let input = document.getElementById('input');
let animalDivs = document.querySelectorAll('.spell');

input.addEventListener('input', function(e) {
  const term = this.value.toLowerCase();
  animalDivs.forEach(function(div) {
    const animal = div.dataset.tag.toLocaleLowerCase();
    div.hidden = !animal.includes(term)
  });
});
</script>
```
