# Dungeon Adventures

### Time and Scale

Time is measured with a certain level of abstraction. Each **Round** of combat is comprised of a set of actions, which take place based on the initiative. For example, one attack roll may represent a whole series of feints, parries, and lunges.

Each **Action** is approximately 10 seconds long. The order a character’s action takes place in is determined by initiative.

A full combat Round (the entire initiative order) is approximately 1 minute and includes all actions (6).

A **Turn** is approximately 10 minutes (10 full combat Rounds or 60 initiative Actions).

Distances in the dungeon are measured in feet. Outdoors, change all distance measurements (movement, range, etc.) to yards (so 100' becomes 100 yards) but area of effect measurements (for spells, for instance) normally remain in feet.

### Weapon Proficiency

Being proficient in a weapon means you can add your Attack Bonus to attack rolls made with that weapon. If you're not proficient, you can still use the weapon but cannot add your Attack Bonus.

[Fighters](class.qmd#fighter), [Rangers](class.qmd#ranger), and [Paladins](class.qmd#paladin) start with 4 weapon proficiencies and gain 1 weapon proficiency every other level after 1st (1 at 3rd, 1 at 5th, 1 at 7th, etc.). Only true Fighters can also specialize in a weapon.

[Clerics](class.qmd#cleric) start with 3 weapon proficiencies and gain 1 weapon proficiency every 3 levels (1 at 4th, 1 at 7th, etc.). Clerics may wear any armor and have no weapon restrictions.

[Druids](class.qmd#druids) start with 3 weapon proficiencies and gain 1 weapon proficiency every 4 levels (1 at 5th, 1 at 9th, etc.). Druids may not utilize metal armor of any type and are likewise limited to wooden shields. Druids may utilize any one-handed melee weapons, as well as staff, sling, and short bow.

[Thieves](class.qmd#thief) and Assassins start with 3 weapon proficiencies and gain 1 weapon proficiency every 3 levels (1 at 4th, 1 at 7th, etc.). Thieves may wear leather armor without penalty to thieving abilities and have no weapon restrictions. The Assassins' Assassinate attack must be carried out with a one-handed piercing weapon, such as a dagger or sword.

[Magic Users](class.qmd#magic-user) start with 2 weapon proficiencies and gain no new proficiencies as they spend most of their training time studying books and not practicing with weapons.


### Carrying Capacity

Player characters with average strength are able to carry up to 40 pounds and still be considered lightly loaded, or up to 115 pounds and be considered heavily loaded. 
Note a character's armor weight counts against their load.

+----------+------------+-------------+------------+
| Strength | Light Load | Medium Load | Heavy Load |
+:=========+:==========:+:===========:+:==========:+
| 3        | 15 lbs.    | 20 lbs.     | 40  lbs.   |
+----------+------------+-------------+------------+
| 4-5      | 15 lbs.    | 30 lbs.     | 50 lbs.    |
+----------+------------+-------------+------------+
| 6-8      | 25 lbs.    | 50 lbs.     | 70 lbs.    |
+----------+------------+-------------+------------+
| 9-12     | 40 lbs.    | 75 lbs.     | 115 lbs.   |
+----------+------------+-------------+------------+
| 13-15    | 60 lbs.    | 115 lbs.    | 175 lbs.   |
+----------+------------+-------------+------------+
| 16-17    | 75 lbs.    | 150 lbs.    | 250 lbs.   |
+----------+------------+-------------+------------+
| 18       | 90 lbs.    | 200 lbs.    | 300 lbs.   |
+----------+------------+-------------+------------+
: Player Character Carrying Capacity {#tbl-carrying-capacity}

The carrying capacities of various domesticated animals are given in the [Monsters section](monsters.qmd#beasts-of-burden).

### Movement and Encumbrance

The movement rate of a character or creature is expressed as the number of feet it can move per combat round. The normal player character races can all move 50' per round. When exploring a dungeon, time is expressed in turns, as explained above; normal movement per turn is 3 times the movement rate per round.

This may seem slow, but this rate of movement includes such things as drawing maps, watching out for traps and monsters (though they may still surprise the party), etc. In a combat situation, on the other hand, everyone is moving around swiftly, and such things as drawing maps are not important.

A character's movement rate is adjusted by his or her Encumbrance (the load he or she is carrying) as follows:

+-----------+------------+-------------+------------+
| Race      | Light Load | Medium Load | Heavy Load |
+:==========+:==========:+:===========:+:==========:+
| Dwarf     | 40'        | 30'         | 20'        |
+-----------+------------+-------------+------------+
| Elf       | 60'        | 50'         | 40'        |
+-----------+------------+-------------+------------+
| Half-Elf  | 55'        | 45'         | 35'        |
+-----------+------------+-------------+------------+
| Halfling  | 50'        | 40'         | 30'        |
+-----------+------------+-------------+------------+
| Human     | 50'        | 40'         | 30'        |
+-----------+------------+-------------+------------+  
: Player Character Movement Rates {#tbl-movement-rates}     
 

### Mapping

In any dungeon expedition, making maps is important. Generally one player will do this, drawing a map on graph paper as the Game Master describes each room or corridor. Absolute accuracy is usually not possible; the main thing is to ensure that the party can find its way back out of the dungeon.

### Light

A torch or lantern will provide light covering a **30' radius**; dim light will extend about **20' further**. Normal torches burn for 1d4+4 turns, while a flask of oil in a lantern will burn for 18+1d6 turns. A candle will shed light over a 5' radius, with dim light extending 5' further. In general, taper candles such as are used for illumination will burn about 3 turns per inch of height.


```{ojs}
viewof torch = Inputs.button(html`<button style="color: black; background-color: lightgray;">Torch Turns (1d4+4)</button>`, {value: 0, reduce: () => (4 + generalDice(1,4,0))})

htl.html`
  <div style="display: flex; align-items: center;">
    <div>
      ${viewof torch}
    </div>
    <div style="margin-left: 10px;">
      Torch burn turns = ${torch}
    </div>
  </div>
`

```

<br>

```{ojs}

viewof oil = Inputs.button(html`<button style="color: black; background-color: lightgray;">Oil Lantern (1d6 +18)</button>`, {value: 0, reduce: () => (18 + generalDice(1,6,0) )})

htl.html`
  <div style="display: flex; align-items: center;">
    <div>
      ${viewof torch}
    </div>
    <div style="margin-left: 10px;">
      Lantern turns = ${torch}
    </div>
  </div>
`

```

### Darkvision

Some character races, and almost all monsters, have Darkvision. This gives them the ability to see even in total darkness. Darkvision is black and white only but otherwise like normal sight. Darkvision does not grant one the ability to see in magical darkness. The range of Darkvision is typically either 30' or 60'; if not given for a particular creature, assume the 60' range.

Darkvision is totally ineffective in any light greater than moonlight.

### Doors

A stuck door can be opened on a roll of 1 on 1d6; add the character's Strength bonus to the range, so that a character with a bonus of +2 can open a stuck door on a roll of 1-3 on 1d6.

Locked doors can be forced by rolling the same range, but on 1d10. Metal bars can sometimes be bent on a roll of this range on 1d20.

A careful character might choose to listen at a door before opening it. Thieves have a special ability, Listen, which should be applied if the listener is a Thief. For other characters, the GM rolls 1d6, with 1 indicating success. Sounds heard might include voices, footsteps, or any other sound the GM considers appropriate. Of course, the room beyond the door might really be silent; thus, the Game Master must make the roll, so that a roll of 1 in such a case will not give anything away to the players.


```{ojs}

import {generalDice} from "./custom.js"

viewof i = Inputs.input(0)
viewof j = Inputs.input(0)
viewof k = Inputs.input(0)


viewof form = Inputs.form(
  {
    doors: Inputs.bind(Inputs.button(html`<button style="color: black; background-color: lightgray;" 1d6 </button>`, {value: 1, reduce: () => (rolld6() )}), viewof i),
    forceBars: Inputs.bind(Inputs.button(html`<button style="color: black; background-color: lightgray;"> Force Bar </button>`, {value: 0, reduce: () => (generalDice(1,20,0) )}), viewof j),
    forceDoor: Inputs.bind(Inputs.button(html`<button style="color: black; background-color: lightgray;"> Force Door </button>`, {value: 0, reduce: () => (generalDice(1,10,0) )}), viewof k),
  },
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 50% auto; 
         vertical-align:midle;
         row-gap: 10px;
       ">
         ${Object.values(formParts)[0]} 1d6 result: ${i.value}
         ${Object.values(formParts)[1]} Force Bar: ${j.value}
         ${Object.values(formParts)[2]} Force Door: ${k.value}

       </div>
     </div>`
  }
)
```



### Traps

Dungeons and ruins frequently contain traps, including spear-throwers, covered pits, etc. The GM will decide what is required to trigger a trap, and what happens when the trap is triggered. (Some guidance on this is provided in the Game Master section later in this book.) In general, there will be some way to avoid or reduce the effect of the trap being sprung. For instance, a save vs. Death Ray is often used to avoid falling into a covered pit (with Dexterity bonus added), while spear-throwers, automated crossbows, and the like are sometimes treated as if they were monsters (attacking vs. the victim's Armor Class at some given attack bonus).

Normal characters have a chance equal to a roll of 1 on 1d6 to detect a trap if a search for one is made. Note that this is about a 16.7% chance; Thieves have a special ability to find and remove traps, which supersedes this roll, as does the stonework trap-finding ability of Dwarves. A Dwarven Thief is a special case; apply whichever trap-detection ability is higher. In all cases, a search for traps takes at least a turn per 10' square area. A single character may only effectively search a given area for traps once, even if the character has more than one trap-detection roll "type" allowed (such as the Dwarven Thief above).

Trap detection may not be allowed if the trap is purely magical in nature; on the other hand, in such cases Magic-Users and/or Clerics may be able to detect magical traps at the given 1 in 1d6 chance, at the Game Master's option.

### Secret Doors

Under normal conditions, searching for secret doors takes one turn per character per 10' of wall searched. A secret door is found on a roll of 1 on 1d6; characters with 15 or higher Intelligence succeed on a roll of 1-2. Also, as noted previously, Elves add 1 to the range automatically, such that an Elf discovers secret doors on a 1-2 on 1d6, or 1-3 if the Elf has an Intelligence of 15 or higher. The GM may create secret doors that are more difficult (or easier) to detect at his or her option.

Multiple characters searching for secret doors ensures that any such will eventually be found; however, if the first and second searchers fail, the next searcher must take two turns to search, and all subsequent searches of the area require an hour.

Note that finding a secret door does not grant understanding of how it works. The GM may require
additional rolls or other actions to be taken before the
door can be opened.

### Dungeon Survival

As described in the [Equipment](equipment.qmd) section, normal characters must consume one day's worth of rations (or equivalent food) and at least one quart of water per day.

Failure to consume enough food does not significantly affect a character for the first two days, after which he or she loses 1 hit point per day. Furthermore, at that point the character loses the ability to heal wounds normally, though magic will still work. Eating enough food for a day (over the course of about a day, not all at once) restores the ability to heal, and the character will recover lost hit points at the normal rate.

Inadequate water affects characters more swiftly; after a single day without adequate water, the character loses 1d4 hit points, and will lose an additional 1d4 hit points per day thereafter; healing ability is lost when the first die of damage is rolled.

