# Feats

Characters of every class may select one feat at 2nd, 4th, 6th, 8th, and 10th level. Note that some feats have prerequisites that must be met, such as an ability score qualifier, or class or race restriction.

## Attack Feats

### Arcane Bolt, Greater (Magic User only)

This improves the Magic-User Arcane Bolt. Target gets a save vs. magic for half damage. The bolt has a range of 40 feet and does 1d6 damage. Since it is pure magic, it will affect creatures that are only affected by magical weapons. The spell does not affect inanimate objects.

### Armed Caster (Magic-User only)

The Magic-User can learn a single additional weapon proficiency. Must be 5th level or higher to take this feat.

### Battle Cry (Minimum Cha 12)

Once during an encounter, the character can inspire all members within a 20-foot radius to gain a +1 to both their next attack and a +1 to damage.

### Blind Fighting

The character can fight while blind or in total darkness with a -2 penalty to its attack rolls, a -2 penalty to its Armor Class, and a -1 penalty to its Initiative rolls.

### Blind Fighting, Improved (Blind Fighting required)

The character can fight while blind or in total darkness with a -1 penalty to its attack rolls, a -1 penalty to its Armor Class, and no penalty to its Initiative rolls.

### Combat Casting (Magic-User or Cleric Only)

If damaged while casting a spell, the character is allowed a saving throw vs. spells +1 to avoid having the spell disrupted and lost.

### Cleave (Fighter only)

Upon successfully dispatching an enemy with a melee attack, the character gets an immediate attack against another adversary within reach.

### Brawling, Improved

Characters that are skilled in Hand-to-Hand can use either Dex or Str bonuses. The character does +1 to hit, 1d4 +1 (+Str or Dex) of subduing damage with a punch, 1d6 with a kick; kicks are rolled at a -1 attack penalty. On a successful critical hit, the opponent must save versus Death or be knocked out.

### Focused Attack (Fighter only)

The character can take a penalty of -1 to damage inflicted in exchange for a bonus of +2 to hit.

### Grenadier

The character has a knack for hurled items such as flaming flasks of oil, acid, holy water, etc., and gains +1 to hit and damage with such items, as well as twice the normal throwing range.

### Improved Critical

After the character scores a critical hit on a natural roll of 20, the subsequent d20 roll to determine a special is at an additional +2.

### Improved Initiative

The character receives a bonus of +1 to individual initiative checks.

### Last Hurrah

Once per battle, if the character is brought to zero or less hit points, the character can still do one action before falling unconscious or dying at +4 chance to hit and damage. This includes spells or attacks within reach.

### Mounted Combat

Requires riding skill. The character receives a +1 bonus to melee attacks made while mounted.

### Mounted Archery

Requires riding skill. The character receives no penalty to ranged attacks made while mounted.

### Point Blank Shot

The character receives an additional bonus of +1 to attacks and damage against targets within thirty feet range.

### Power Attack (Fighter only)

The character can take a penalty of -1 to melee attacks in exchange for a bonus of +2 to damage.

### Precise Shot

The character can fire into melee combat without risk of hitting an ally.

### Quick Draw

The character can pull a weapon or change weapons before initiative is rolled without penalty.

### Rapid Reload

The character can reload crossbows and other mechanical ranged weapons at twice the normal rate.

### Shield Bash

The character, if equipped with a shield, can elect to forgo the armor class benefit (must state the intention to do so before initiative is checked) in exchange for gaining a second attack at +1 to hit for 1d4 points of damage (plus any strength bonus).

### Two-weapon style (Dex 13)

-1 to attack with the primary weapon and -3 to attack with the secondary weapon

### Two-weapon style, Improved (Dex 13, Two-weapon style prerequisite)

-0 to attack with the primary weapon and -1 to attack with the secondary weapon

### Undead Bane (Cleric and Paladins only)

+1 to Turn Undead and receive a +1 to the 2D6 affected roll.

### Weapon Finesse

A character may use the Dex bonus, rather than Str bonus, when fighting with light melee weapons.

## Defense Feats

### Alcohol Resistance (Minimum Con 15)

The character possesses an almost supernatural ability drink large amounts of alcohol before succumbing to its effects. This feat gives a +2 inherent bonus on saves against drunkenness.

### Armored Caster (Magic-User only)

The Magic-User can wear studded leather armor and cast spells. Must be 5th level or higher to take this feat.

### Combat Expertise

While in melee combat, the character is allowed to take a penalty of -1 to melee attacks in exchange for a bonus of +1 to armor class.

### Combat Expertise, Improved

Must have Combat Expertise to take this feat and can increase the armor class bonus to +2 (while still suffering only a penalty of -1 to attacks).

### Parry and Dodge, Improved

Improved Parry and Dodge is a Defensive action instead of an attack that gives a +3 bonus to AC.

### Endurance

The character is unusually hardy, and can heal 2 hit points per day, as well as being able to subsist on just half the daily food and water of a normal person for as long as a month.

### Great Fortitude

The character receives a bonus of +1 to saves against poisons and diseases.

### Iron Will

The character receives a bonus of +1 to saving throws against charms and compulsions.

### Two-weapon Defense

A character with the Two-weapon Defense feat receives a bonus of +1 to armor class when wielding two weapons.

### Zen

The character is a master of control and receives a +1 to any saves that deal with the character's mind. EX: charm, confusion, deceptions, seduction, or pain.

## Roleplaying Feats

### Accomplished (minimum Cha 15)

This feat adds two extra ranks to the Perform
