# Multi Class Options

## Combination Classes

To become a member of a combination class, a character must meet the requirements of both classes. Combination class characters use the best attack bonus and the best saving throw values of their original two classes, but must gain experience equal to the combined requirements of both base classes to advance in levels. [Elves](races.qmd#elves) are the only characters eligible to be a member of one of these combination classes:

**Fighter/Magic-User:** These characters may both fight and cast magic spells; further, they are allowed to cast magic spells while wearing armor. These characters roll six-sided dice (d6) for hit points.

**Magic-User/Thief:** Members of this combination class may cast spells while wearing leather armor, and may use any weapon. These characters roll four-sided dice (d4) for hit points.

## Class-Kits

A Class-Kit is a set of class-like options that can be layered upon another base-class in order to create additional character archetypes or types of characters that cannot be easily achieved by use of the typical or core class offerings. Each class-kit has its own set of requirements and offers unique benefits in exchange for an additional experience point requirement. Many class-kits are designed to emulate certain standard fantasy gaming concepts such as a Shadowblade is essentially a Figther with the Assassin class-kit.  Or a Arcane Healer is a Magic-User with the Mystic Theurge class-kit. Other class-kits are altogether new character concepts that have not been represented in these sorts of games.

Overall, the idea is to create a multitude of character concepts with just a few additional options added. If one uses just the four core classes, each added class-kit adds another four variations for character types, leading to many more combinations if some of the optional standard sub-classes are utilized as well. That all said, the Dungeon Master should not feel obligated to use every class-kit presented here, nor allow every conceivable combination.

### The Class-Kit Mechanic

Adding a class-kit works in a similar fashion to combination class characters or multi-class characters found in other game editions. One main difference is that the class-kit does not alter or expand the standard base-class features such as hit die, saves, or attacking bonus directly, except in certain situations that are detailed in the individual class-kit description.

Typically, a class-kit is chosen when the character is created. The sum of experience points for both the base and class-kit is necessary to achieve the new character level in a manner just like combo-classes. While not generally recommended, a character might decide to take on a class-kit after adventuring for a time (and acquiring levels). In this case, it is suggested that the character must devote all earned experience toward the class-kit until the class-kit level matches the base-class level. After achieving that equilibrium, normal progression (at the combined XP requirement) resumes.

While the Dungeon Master may make special individual exceptions, it is generally recommended that a class-kit cannot be added to a character that is already combination-classed, as the character must split their attention between two such professions. Likewise, it is not recommended that more than one class-kit be applied to a single character. However, it is permissible that a character might mix a particular sub-class (if such are available) with an appropriate class-kit. For instance, if the Dungeon Master utilizes Druids (clerical sub-class), the character might be allowed to become a Barbaric-Druid with the DM's approval. Certain combinations may be inappropriate regardless. The DM is suggested to exercise care with non-standard combinations with an eye for overall balance or campaign consistency.

### Mystic Theurge Kit

A Magic-User may choose to add the Mystic Theurge Kit. The additional Experience Point requirements for Mystic Theurge are added to those of the Magic-User.

Mystic Theurges are Magic-Users who place no boundaries on their magical abilities and find no irreconcilable paradox in devotion to the arcane as well as the divine. They seek magic in all of its forms, finding no reason or logic in denying themselves instruction by limiting their knowledge to one stifling paradigm, though many are simply hungry for limitless power. No matter what their motivations, Mystic Theurges believe that perception is reality, and through the divine forces and astral energies of the multiverse, that perception can be used to manipulate and control not only the nature of this reality, but destiny itself.

#### Requirements
- For a Wizard to qualify to become a mystic theurge, the character must have at least 1 skill point in Religion.
- Mystic Theurges must tithe at least 5% of their earnings toward the church.

#### Mystic Theurge

| Level | Additional Exp. Points | Lay Hands | Holy Burst | Max. Cleric Spell Level | Religion Skill Point Requirement |
|-------|-------------------------|-----------|-------------|--------------------------|----------------------------------|
| 1     | 1000                    | 1/per day | 1/per day   | 0                        | 1                                |
| 2     | 2000                    | 1/per day | 1/per day   | 0                        | 1                                |
| 3     | 3500                    | 1/per day | 1/per day   | 1                        | 1                                |
| 4     | 4500                    | 2/per day | 2/per day   | 1                        | 1                                |
| 5     | 5500                    | 2/per day | 2/per day   | 1                        | 1                                |
| 6     | 7500                    | 2/per day | 2/per day   | 2                        | 2                                |
| 7     | 9500                    | 2/per day | 2/per day   | 2                        | 2                                |
| 8     | 11,500                  | 3/per day | 3/per day   | 2                        | 2                                |
| 9     | 14,000                  | 3/per day | 3/per day   | 3                        | 3                                |
| 10    | 16,500                  | 3/per day | 3/per day   | 3                        | 3                                |
| 11    | 19,000                  | 3/per day | 3/per day   | 3                        | 3                                |
| 12    | 23,000                  | 4/per day | 4/per day   | 4                        | 3                                |
| 13    | 26,000                  | 4/per day | 4/per day   | 4                        | 3                                |
| 14    | 29,000                  | 4/per day | 4/per day   | 4                        | 3                                |
| 15    | 33,000                  | 4/per day | 4/per day   | 5                        | 4                                |
| 16    | 37,000                  | 5/per day | 5/per day   | 5                        | 4                                |
| 17    | 42,000                  | 5/per day | 5/per day   | 6                        | 4                                |
| 18    | 47,000                  | 5/per day | 5/per day   | 6                        | 4                                |
| 19    | 52,000                  | 5/per day | 5/per day   | 6                        | 4                                |
| 20    | 60,000                  | 6/per day | 6/per day   | 7                        | 5                                |

#### Study of the Divine
When memorizing spells, the Mystic Theurge can replace a number of magic-user spells (up to their Intelligence bonus) with Cleric spells of the same level instead. The spell level can’t exceed the maximum level of Cleric Spell outlined in the chart above.

#### Holy Burst
A Mystic Theurge may channel divine power in order to combat the forces of darkness. This Holy Burst causes damage equal to the Mystic Theurge level to any undead, affecting all such creatures within a 10-foot radius. The Mystic Theurge may use this power a number of times per day according to their level (see chart) plus their Charisma bonus. For instance, a Magic-User with 3 levels of Mystic Theurge with a 15 Charisma (+1 bonus) can produce a Holy Burst twice per day.

#### Lay on Hands
A Mystic Theurge may lay hands and heal 2 points of damage plus Intelligence Bonus. The Mystic Theurge may use this power a number of times per day according to their level (see chart).

