# Saving Throws

**Saving throws** represent the ability of a character or creature to resist or avoid special attacks, such as spells or poisons. Like an attack roll, a saving throw is a d20 roll, with a target number based on the character's class and level; for monsters, a comparable class and level are provided for the purpose of determining the monster's saving throw figures. A natural (unadjusted) roll of 1 on a saving throw is always a failure, while a natural 20 is always a success.

The five categories of saving throw as follows: **Death Ray or Poison**, **Magic Wands**, **Paralysis or Petrify**, **Dragon Breath**, and **Spells**. Spells and monster special attacks will indicate which category applies (when a saving throw is allowed), but in some unusual situations the Dungeon Master  will need to choose a category. One way to make this choice is to interpret the categories metaphorically. For example, a DM might be writing an adventure wherein there is a trap that pours burning oil on the hapless adventurers. Avoiding the oil might be considered similar to avoiding Dragon Breath. Or perhaps a stone idol shoots beams of energy from its glaring eyes when approached. This attack may be considered similar to a Magic Wand, or if especially potent, a Spell. Another approach is to interpret the categories in terms of which ability is challenged: 

* Death Ray or Poison (Constitution)
* Magic Wands (Wisdom)
* Paralysis or Petrify (Strength)
* Dragon Breath (Dexterity)
* Spells (Intelligence). 


The saving throw vs. Death Ray is often used as a "catch all" save versus many of the "ordinary" dangers encountered in a dungeon environment.

In general, saving throw rolls are not adjusted by ability score bonus or penalty figures. There are a few exceptions:

-   Poison saving throws are always adjusted by the character's [Constitution](abilities.qmd#ability-scores) modifier.
-   Saving throws against illusions (such as **phantasmal force**) are always adjusted by the character's [Intelligence](abilities.qmd#ability-scores) modifier.
-   Saving throws against **charm** spells (and other forms of mind control) are adjusted by the character's [Wisdom](abilities.qmd#ability-scores) modifier.

The DM may decide on other saving throw adjustments as he or she sees fit.

## Item Saving Throws

Area effects (such as fireball or lightning bolt spells) may damage items carried by a character as well as injuring the character. For simplicity, assume that items carried are unaffected if the character or creature carrying them makes his or her own saving throw. However, very fragile items (paper vs. fire, glass vs. physical impact, etc.) may still be considered subject to damage even if the bearer makes his or her save.

In any case where one or more items may be subject to damage, use the saving throw roll of the bearer to determine if the item is damaged or not. For example, a character holding an open spellbook is struck by a fireball spell; he or she must save vs. Spells, and then save again at the same odds for the spellbook.

The DM should feel free to amend this rule as he or she wishes; for instance, a backpack full of fragile items might be given a single saving throw rather than laboriously rolling for each and every item.

## Saving Throw Tables by Class

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 11 | 12 | 14 | 16 | 15 |
| **2-3** | 10 | 11 | 13 | 15 | 14 |
| **4-5** | 9 | 10 | 13 | 15 | 14 |
| **6-7** | 9 | 10 | 12 | 14 | 13 |
| **8-9** | 8 | 9 | 12 | 14 | 13 |
| **10-11** | 8 | 9 | 11 | 13 | 12 |
| **12-13** | 7 | 8 | 11 | 13 | 12 |
| **14-15** | 7 | 8 | 10 | 12 | 11 |
| **16-17** | 6 | 7 | 10 | 12 | 11 |
| **18-19** | 6 | 7 | 9 | 11 | 10 |
| **20** | 5 | 6 | 9 | 11 | 10 |
: Cleric Saving Throws {#tbl-save-clerics-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath | Spells |
|----|---|----|----|---|---|---|
| **1**     | 13 | 14 | 13 | 16 | 15 |
| **2-3**   | 13 | 14 | 13 | 15 | 14 |
| **4-5**   | 12 | 13 | 12 | 15 | 13 |
| **6-7**   | 12 | 12 | 11 | 14 | 13 |
| **8-9**   | 11 | 11 | 10 | 14 | 12 |
| **10-11** | 11 | 10 | 9 | 13 | 11 |
| **12-13** | 10 | 10 | 9 | 13 | 11 |
| **14-15** | 10 | 9  | 8 | 12 | 10 |
| **16-17** | 9  | 8  | 7 | 12 | 9 |
| **18-19** | 9  | 7  | 6  | 11 | 9 |
| **20**    | 8  | 6  | 5  | 11 | 8 |
: Druid Saving Throws {#tbl-save-druids-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **NM** | 13 | 14 | 15 | 16 | 18 |
| **1** | 12 | 13 | 14 | 15 | 17 |
| **2-3** | 11 | 12 | 14 | 15 | 16 |
| **4-5** | 11 | 11 | 13 | 14 | 15 |
| **6-7** | 10 | 11 | 12 | 14 | 15 |
| **8-9** | 9 | 10 | 12 | 13 | 14 |
| **10-11** | 9 | 9 | 11 | 12 | 13 |
| **12-13** | 8 | 9 | 10 | 12 | 13 |
| **14-15** | 7 | 8 | 10 | 11 | 12 |
| **16-17** | 7 | 7 | 9 | 10 | 11 |
| **18-19** | 6 | 7 | 8 | 10 | 11 |
| **20** | 5 | 6 | 8 | 9 | 10 |
: Fighter Saving Throws {#tbl-save-fighter-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath | Spells |
|----|---|----|----|---|---|---|
| **NM** | 13 | 14 | 15 | 16 | 18 |
| **1** | 12 | 13 | 14 | 15 | 17 |
| **2-3** | 11 | 12 | 14 | 15 | 16 |
| **4-5** | 11 | 11 | 13 | 14 | 15 |
| **6-7** | 10 | 11 | 12 | 14 | 15 |
| **8-9** | 9 | 10 | 12 | 13 | 14 |
| **10-11** | 9 | 9 | 11 | 12 | 13 |
| **12-13** | 8 | 9 | 10 | 12 | 13 |
| **14-15** | 7 | 8 | 10 | 11 | 12 |
| **16-17** | 7 | 7 | 9 | 10 | 11 |
| **18-19** | 6 | 7 | 8 | 10 | 11 |
| **20** | 5 | 6 | 8 | 9 | 10 |
: Paladin Saving Throws {#tbl-save-paladin-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath | Spells |
|----|---|----|----|---|---|---|
| 1     | 12                  | 13          | 14                   | 15            | 17     |
| 2-3   | 11                  | 12          | 14                   | 15            | 16     |
| 4-5   | 11                  | 11          | 13                   | 14            | 15     |
| 6-7   | 10                  | 11          | 12                   | 14            | 15     |
| 8-9   | 9                   | 10          | 12                   | 13            | 14     |
| 10-11 | 9                   | 9           | 11                   | 12            | 13     |
| 12-13 | 8                   | 9           | 10                   | 12            | 13     |
| 14-15 | 7                   | 8           | 10                   | 11            | 12     |
| 16-17 | 7                   | 7           | 9                    | 10            | 11     |
| 18-19 | 6                   | 7           | 8                    | 10            | 11     |
| 20    | 5                   | 6           | 8                    | 9             | 10     |
: Ranger Saving Throws {#tbl-save-ranger-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 13 | 14 | 13 | 16 | 15 |
| **2-3** | 13 | 14 | 13 | 15 | 14 |
| **4-5** | 12 | 13 | 12 | 15 | 13 |
| **6-7** | 12 | 12 | 11 | 14 | 13 |
| **8-9** | 11 | 11 | 10 | 14 | 12 |
| **10-11** | 11 | 10 | 9 | 13 | 11 |
| **12-13** | 10 | 10 | 9 | 13 | 11 |
| **14-15** | 10 | 9 | 8 | 12 | 10 |
| **16-17** | 9 | 8 | 7 | 12 | 9 |
| **18-19** | 9 | 7 | 6 | 11 | 9 |
| **20** | 8 | 6 | 5 | 11 | 8 |
: Magic-User Saving Throws {#tbl-save-mage-2}

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 13 | 14 | 13 | 16 | 15 |
| **2-3** | 12 | 14 | 12 | 15 | 14 |
| **4-5** | 11 | 13 | 12 | 14 | 13 |
| **6-7** | 11 | 13 | 11 | 13 | 13 |
| **8-9** | 10 | 12 | 11 | 12 | 12 |
| **10-11** | 9 | 12 | 10 | 11 | 11 |
| **12-13** | 9 | 10 | 10 | 10 | 11 |
| **14-15** | 8 | 10 | 9 | 9 | 10 |
| **16-17** | 7 | 9 | 9 | 8 | 9 |
| **18-19** | 7 | 9 | 8 | 7 | 9 |
| **20** | 6 | 8 | 8 | 6 | 8 |
: Thief Saving Throws {#tbl-save-thief-2}

## Difficulty Challenge (DC) 

There will be times when a player character tries to do something in the game that seems to have no rule covering it. In some of those cases, the DM will assign a Difficulty Challenge (DC) number from 1 to 20.
The player rolls 1d20 and adds their Ability Bonus for the score the DM thinks is most appropriate, as well as any situational bonus or penalty the DM assigns. The resulting number must equal or be greater than the DC number.

| Percentile% (2d10) | (1d6) | (1d20) | Description          |
|---------------------|-------|--------|----------------------|
| 85%                 | 1-5   | DC 3   | Very Easy            |
| 70%                 | 1-4   | DC 6   | Easy                 |
| 50%                 | 1-3   | DC 10  | Normal               |
| 35%                 | 1-2   | DC 13  | Hard                 |
| 15%                 | 1-1   | DC 15  | Very Hard            |
| 5%                  | -     | DC 20  | Extremely Difficult  |
: Difficulty Challenge {#tbl-difficulty-challege}


