# Skills

At first level, a character starts with 3 skill level points. Every level after 1st, the character gets 1 additional skill level point that can be applied to a skill as long as the skill level does not exceed the character level.

When a character uses a skill, make a skill check. The higher the result of the skill check, the better. Based on the circumstances, the result must match or beat a particular number (a DC or the result of an opposed skill check) for the check to be successful. The harder the task, the higher the number a character needs to roll.
A skill check considers a character’s training (skill rank), natural talent (ability modifier), and luck (the die roll). It may also consider their race’s knack for doing certain things (racial bonus) or what armor they are wearing (armor check penalty), or a certain feat the character possesses, among other things.
To make a skill check, roll 1d20 and add your character’s skill modifier for that skill. The skill modifier incorporates the character’s ranks in that skill and the ability modifier for that skill’s key ability, plus any other miscellaneous modifiers that may apply, including racial bonuses and armor check penalties. The higher the result, the better. Unlike with attack rolls and saving throws, a natural roll of 20 on the d20 is not an automatic success, and a natural roll of 1 is not an automatic failure.


**The Skill Check Difficulty Challenge (DC)**

The skills listed below have DC targets assigned. These targets can be modified to fit the circumstance by either changing the DC number itself or providing a bonus or penalty to the character's roll.

There will be times when a player character tries to do something in the game that seems to have no rule covering it. In some of those cases, the DM will assign a Difficulty Challenge (DC) number from 1 to 20. The player rolls 1d20 and adds their Ability Bonus for the score the DM thinks is most appropriate, as well as any situational bonus or penalty the DM assigns. The resulting number must equal or be greater than the DC number.


| Percentile% (2d10) | (1d6) | (1d20) | Description         |
|--------------------|-------|--------|---------------------|
| 85%                | 1-5   | DC 3   | Very Easy           |
| 70%                | 1-4   | DC 6   | Easy                |
| 50%                | 1-3   | DC 10  | Normal              |
| 35%                | 1-2   | DC 13  | Hard                |
| 15%                | 1-1   | DC 15  | Very Hard           |
| 5%                 | -     | DC 20  | Extremely Difficult |
: Skill Check DC {#tbl-skill-dc}

When the player performs a skill action, they roll d20, modified by the ability score of the skill and the number of ranks in the skill. The roll must be greater than or equal to the Skill Check Difficulty Challenge (DC) that the DM assigns.

**Adjusted DC**

- Give the skilled user a +2 circumstance bonus to represent conditions that improve performance, such as having the perfect tool for the job, getting help from another character, or possessing unusually accurate information.
- Give the skilled user a -2 circumstance penalty to represent conditions that hamper performance, such as being forced to use improvised tools or having misleading information.
- Reduce the DC by 2 to represent circumstances that make the task easier, such as having a friendly audience or doing work that can be subpar.
- Increase the DC by 2 to represent circumstances that make the task harder, such as having an uncooperative audience or doing work that must be flawless.

**Opposed Skill Check**

An opposed check is a check whose success or failure is determined by comparing the Skill check result to another character’s Skill check result. In an opposed check, the higher result succeeds, while the lower result fails. In case of a tie, the higher skill modifier wins. If these scores are the same, roll again to break the tie.

| Task                       | Skill (Key Ability)        | Opposing Skill (Key Ability)  |
|----------------------------|----------------------------|-------------------------------|
| Con someone                | Bluff (Cha)                | Sense Motive (Wis)            |
| Pretend to be someone else | Disguise (Cha)             | Spot (Wis)                    |
| Create a false map         | Forgery (Int)              | Investigation (Int)           |
| Hide from someone          | Hide (Dex)                 | Spot (Wis)                    |
| Make a bully back down     | Intimidate (Cha)           | Sense Motive (Wis)            |
| Sneak up on someone        | Move Silently (Dex)        | Listen (Wis)                  |
| Steal a coin pouch         | Sleight of Hand (Dex)      | Spot (Wis)                    |
| Tie a prisoner securely    | Use Rope (Dex)             | Escape Artist (Dex)           |
: Opposed Skill Check {#tbl-opposed-skill-check}

**Trying Again**

In some cases, a character can try a skill check again. Some skills, however, have consequences of failure. A few skills are virtually useless once a check has failed. For most skills, when a character has succeeded once at a given task, additional successes are meaningless.

**Untrained Skill Checks**

Generally, if a character attempts to use an unranked skill they do not possess, they make a skill check as normal. The skill modifier doesn’t have a skill rank added in because the character has no ranks in the skill. Any other applicable modifiers, such as the modifier for the skill’s key ability, are applied to the check.


**Skills List and Descriptions**

Players may select skills from the general skills and their class skills sections

## Alchemy – INT

The character understands chemistry, potions and the elements of nature and can identify properties. Alchemy requires a successful check against a Hard Target (DC 13).

## Animal Handling – CHA

This task involves commanding an animal to perform a task or trick that it knows. If the animal is wounded or frightened, the Target Number increases by 2. If your check succeeds, the animal performs the task or trick.

*Push an Animal*

To push an animal means to get it to perform a task or trick that it doesn't know but is physically capable of performing. This category also covers making an animal perform a forced march or forcing it to hustle for more than 1 hour between sleep cycles. If the animal is wounded, the Target Number increases by 2 levels. If your check succeeds, the animal performs the task or trick on its next action.

*Teach an Animal a Trick*

You can teach an animal a specific trick with one week of work and a successful Handle Animal check. An animal can learn a maximum of six tricks. Possible tricks include, but are not necessarily limited to, the following.

- **Attack:** The animal attacks apparent enemies.
- **Come:** The animal comes to you, even if it normally would not do so.
- **Defend:** The animal defends you (or is ready to defend you if no threat is present), even without any command being given. Alternatively, you can command the animal to defend a specific other character.
- **Down:** The animal breaks off from combat or otherwise backs down. An animal that doesn't know this trick continues to fight until it must flee or its opponent is defeated.
- **Fetch:** The animal goes and gets something. If you do not point out a specific item, the animal fetches some random object.
- **Guard:** The animal stays in place and prevents others from approaching.
- **Heel:** The animal follows you closely, even to places where it normally wouldn't go.
- **Perform:** The animal performs a variety of simple tricks, such as sitting up, rolling over, barking, and so on.
- **Seek:** The animal moves into an area and looks around for anything that is obviously alive or animate.
- **Stay:** The animal stays in place, waiting for you to return. It does not challenge other creatures that come by, though it still defends itself if it needs to.
- **Track:** The animal tracks the scent presented to it.
- **Work:** The animal pulls or pushes a medium or heavy load.

## Appraise – INT

You can appraise common or well-known objects with an Appraise check. Failure means that you estimate the value at 50% to 150% (2d6+3 times 10%) of its actual value.

Appraising a rare or exotic item requires a successful check against a Target Number of 17 or higher. If the check is successful, you estimate the value correctly; failure means you cannot estimate the item's value.

## Balance – DEX

The character can walk on a precarious surface. Balance requires a successful check against a Very Hard Target (DC 15). A successful check allows the character to move at half the character's speed along the surface for 1 round. A failure by 4 or less means the character can’t move for 1 round. A failure by 5 or more means the character falls.

## Bluff – CHA

A successful Bluff check indicates that the target reacts as the character wishes, at least for a short time (usually 1 round or less) or believes something that the character wants it to believe. A bluff requires interaction between the character and the target. Creatures unaware of the character cannot be bluffed. Bluff requires a successful check against a Very Hard Target (DC 15).

## Brawling/Grappling – STR or DEX

The character gets a bonus on an opposed Grapple check.

## Climb – STR

The character gets a bonus when climbing. Climbing requires a successful check against a Normal/Hard Target (DC 12).

## Craft – INT

A Craft skill is specifically focused on a single type of craft, e.g., armorer, bowyer, glass blower, leatherworker, potter, shipbuilder, silversmith, wheelwright, and weaver creating and/or repairing something. If nothing is created by the endeavor, it probably falls under the heading of a Profession skill rather than Craft.
Craft requires a successful check against a Very Hard Target (DC 15).
With enough slots, a character would be considered a “Master Craftsmen” with this skill. Time and proper materials are required to be present to succeed.

## Decipher – INT

The character can decipher writing in an unfamiliar language, or a message written in an incomplete or archaic form. This includes intricate, exotic, or very old writing.
Decipher requires a successful check against an Extremely Difficult Target (DC 19). If the check succeeds, the character understands the general content of a piece of writing about one page long (or the equivalent). If the check fails, another check should be made to see if the character avoids drawing a false conclusion about the text. (Success means that the character does not draw a false conclusion; failure means that the character does.)

## Diplomacy – CHA

You can change the attitudes of others with a successful Diplomacy check. In negotiations, the GM adds the number of skill points in the character's diplomacy skill to the Reaction roll on the [Reaction Roll table](combat.qmd#monster-reactions). More than one roll may be required for checks to resolve situations when two advocates or diplomats plead opposite cases in a hearing before a third party.

## Disguise – CHA

This is the ability to change the character's appearance or impersonate another character. The character's Disguise check result determines how good the disguise is. The target number of the check is against a Very Hard Target (DC 15), but this should be modified by the situation.
If the character doesn’t draw any attention to themselves, the DM may grant up to a +5 to the checks. If the character comes to the attention of people who are suspicious (such as a guard who is watching commoners walking through a city gate), a -5 may be appropriate to apply to the check.

## Endurance – CON

The character has the ability to perform tiring tasks for long periods of time. Each successful check allows the character to perform the task for one hour. Another check must be made every hour with a -1 cumulative penalty to the roll. When the character has completed the task or fails the check, they collapse and must rest for three times the amount of time used performing the task.

## Engineering – INT
The character understands buildings, aqueducts, bridges, fortifications, etc. Engineering requires a successful check against a Hard Target (DC 15).

## Escape Artist – DEX
The character with the Escape Artist skill has the uncanny ability to get loose from ropes when tied up. Escape Artist requires a successful check against a Hard Target (DC 15).

## Forgery – INT

The character is adept at faking documents or detecting forgeries that others try to pass off. To forge documents and detect them, the character must be able to read and write the required language.

Making a forgery requires appropriate writing materials, sufficient visual acuity to see details, wax for seals (if appropriate), and about 1 minute for a very short and simple document. A longer or more complex document takes 1d4 minutes per page.

To forge a document on which the handwriting is not specific to a person (e.g., military orders, a government decree, a business ledger), the character only needs to have seen a similar document before, gaining a +4 bonus on the check. To forge a signature, the character needs an autograph of that person.

Forgery requires a successful check against a Very Hard Target (DC 15). The DM makes the Forgery check secretly, so that the character is not sure of the quality of the forgery.

A document that contradicts procedure, orders, or previous knowledge, or one that requires sacrifice on the part of the person checking the document, can increase suspicion and create favorable circumstances for the checker’s opposing Forgery check.

## Geography – INT

The character has knowledge of the lands, features, inhabitants, and phenomena of OnceWas. Geography requires a successful check against a Hard Target (DC 13).

## Heal – WIS

The character understands how to give first aid. When a character falls below zero hit points, but not below -10, another character with the Heal skill can attempt first aid to save the life of the dying character. 

A Heal skill check is against a Normal Target (DC 10). If successful, it will stabilize the dying character and add 1 hit point.

After stabilization, the character must spend one week in bed rest to restore the first hit point; after this, healing proceeds at the normal rate.

## History – INT

The character understands the history of OnceWas - royalty, wars, colonies, migrations, founding of cities. History requires a successful check against a Hard Target (DC 13).

## Hunting – WIS

The character has a bonus to fish or hunt. Hunting requires a successful check against a Hard Target (DC 13).

## Inside Knowledge (Rumors Around Town) – CHA

The character is knowledgeable about events in their hometown or city. By spending an evening's time, a few gold pieces for buying drinks and making new friends, the character can make a Knowledge (Rumors Around Town) check to gain a general idea of a city’s major news items, assuming there are no obvious reasons why the information would be withheld.

Inside Knowledge requires a successful check against a Hard Target (DC 13). The higher the character's check result, the better the information obtained.

## Intimidate – CHA or STR

The character can change another’s behavior through intimidation. Intimidate requires a successful check against a Medium Target (DC 10). If the character succeeds on the skill check, the target may temporarily treat the character as very favorable, but only for the purpose of actions taken while it remains intimidated. The target retains its normal attitude but may chat, advise, offer limited help, or advocate on the character's behalf while intimidated.

The effect lasts as long as the target remains in the character's presence, and for 1d6 turns afterward. After this time, the target’s default attitude toward the character shifts to unfavorable (or, if normally unfavorable, to immediate attack).

## Investigation – INT

This skill is used when the character is searching for something that is not in plain sight, relying on intelligence to make connections and deductions to uncover hidden secrets. Whatever the character is looking for is not easily discerned by the character's senses, thus relying on their intellect is crucial.
Investigation involves utilizing studies, street smarts, or other knowledge to find clues, objects, or information.

Each rank of Investigation adds +1 to Checking for Traps. Investigation requires a successful check against a Very Hard Target (DC 15).

## Jump – STR

### Long Jump:
A long jump is a horizontal leap, made across a gap such as a chasm or stream. At the midpoint of the jump, the character attains a vertical height equal to one-quarter of the horizontal distance. The DC for the jump is equal to the distance jumped in feet.

### High Jump:
A high jump is a vertical leap made to reach a ledge high above or to grasp something overhead. The DC is equal to 4 times the distance to be cleared.

## Labor – CON

The character is highly proficient in a specific type of manual labor, such as bricklaying, carpentry, farming, hunting, mining, or sailing. These tasks demand some training but don't necessitate extensive skill. Labor requires a successful check against a Hard Target (DC 13).

## Leadership – Cha

The Leadership skill allows the character to exert influence over others. A successful Leadership skill check adds +1 to each rank for Reaction roles. Additionally, it can be used to convince non-retainer NPCs to follow an order, but these NPCs will not comply if there's a good reason not to do so. The use of the Leadership skill upon an NPC does not shift their attitude to unfavorable afterward.

## Magic Lore – Int

Magic Lore represents the character's knowledge gained from the study of Arcana. This knowledge may include ancient mysteries, magic traditions, arcane symbols, cryptic phrases, constructs, dragons, magical beasts, spells, magic items, and magic effects. Magic Lore requires a successful check against a Very Hard Target (DC 15).

## Perception - Wis

Perception is used to sense the world around the character using their natural senses (sight, smell, hearing, touch, taste). It's employed to detect hidden objects or creatures, observe details, and perceive the environment. Perception requires a successful check against a Hard Target (DC 13).

## Perform – Cha

Perform represents the character's ability to entertain through various means. A successful Perform check requires meeting a Hard Target (DC 13). The character can be proficient in one of the following categories:

- Act (comedy, drama, mime)
- Comedy (buffoonery, limericks, joke-telling)
- Dance (ballet, waltz, jig)
- Musical Instruments (one of bells, chimes, drums, fiddle, flute, gong, harp, harpsichord, lute, mandolin, pan pipes, piano, pipe organ, recorder, trumpet)
- Oratory (epic, ode, storytelling)
- Vocals (ballad, chant, melody)

## Poison – Int

The Poison skill reflects the character's knowledge of poisons, poisonous plants, and animals. Poison requires a successful check against a Very Hard Target (DC 15).

## Profession – Wis

The Profession skill represents the character's proficiency in a secondary, non-labor profession such as estate management, cartography, cooking, law, or laymen clergy. It requires a successful check against a Normal Target (DC 10). The character can use their profession to make a living, handle daily tasks, supervise helpers, and solve common problems.

## Religion - Wis

Religion measures the character's ability to recall lore about deities, religious rites and prayers, hierarchies, holy symbols, and practices of secret cults. Religion requires a successful check against a Hard Target (DC 13).

## Ride – Dex

The character is knowledgeable in the means of riding one type of mount. They can saddle, mount, ride, and dismount without a problem if not rushed. However, special actions while mounted require a skill check (e.g., guiding the mount with knees, staying in the saddle to avoid falling when the mount rears or bolts, getting the mount to leap obstacles, attempting to control a mount not trained for combat while riding in battle).

## Rope Use – Dex

The character can tie several sophisticated knots. Rope Use requires a successful check against a Normal Target (DC 10).

## Sail – Int

The sailing skill involves knowledge of basic terminology, rigging, and navigation for boating. Sail requires a successful check against a Very Hard Target (DC 15).

## Sense Motive – Wis

This use of the skill involves assessing the situation. Sense Motive requires a successful check against a Very Hard Target (DC 13). The character can get the feeling from another’s behavior that something is wrong, such as when the character is talking to an impostor. Alternatively, the character can get the feeling that someone is trustworthy.

## Sleight of Hand – DEX

Whenever the character attempts an act of manual trickery, such as planting something on someone else or concealing an object on the character's person, making a Sleight of Hand check requires a Very Hard Target (DC 15).

## Soldier – Highest Attribute

The character was enlisted to a standing national army during a recent Crusade. The character trained to use standard weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield. A character with the Soldier Skill understands military tactics, troop movements, sieges, etc. Soldier requires a successful check against a Hard Target (DC 13). The character is proficient already with a short sword, long sword, short bow, and shield. Any class with this skill can use these weapons without penalty.

## Spot – Wis

The Spot skill is used primarily to detect characters or creatures that are hiding. Typically, a Spot check is opposed by the Hide check of the creature trying not to be seen. Sometimes a creature isn’t intentionally hiding but is still difficult to see, so a successful Spot check is necessary to notice it. 

### Spot Check Penalty
Condition | Penalty
-1 | Per 10 feet of distance
-5 | Spotter distracted

Spot checks can also be used to read lips. To understand what someone is saying by reading lips, a character must be within 30 feet of the speaker, be able to see them speaking, and understand the speaker’s language. The base DC is 15, but it increases for complex speech or an inarticulate speaker. A character must maintain a line of sight to the lips being read. If the Spot check succeeds, a character can understand the general content of a minute’s worth of speaking, but they miss certain details. If the check fails by 4 or less, a character can’t read the speaker’s lips. If the check fails by 5 or more, they draw some incorrect conclusion about the speech. The check is rolled secretly in this case, so that a character doesn’t know whether they succeeded or missed by 5.

## Survival – Wis

The character can build shelter, start fires, and gather food in the wilderness. Survival requires a successful check against a Very Hard Target (DC 15).

## Swim – Str

Make a Swim check against a Normal Target (DC 10) once per round while the character is in the water. Success means the character may swim at up to one-half the character's speed. Swimming in armor is normally impossible.

## Tracking – Wis

The character has a bonus to identify and follow tracks. Tracking requires a successful check against a Very Hard Target (DC 15).

## Tumble – Dex

The character can land softly when falling. Tumble requires a successful check against a Very Hard Target (DC 15). The character can also tumble to entertain an audience (as though using the Perform skill). Treat a fall as if it were 10 feet shorter than it really is when determining damage.

