# Character Stats

To generate your character’s ability scores, roll **3d6** six times.  Assign these numbers to the six abilities as you wish, then record each score and its modifier on your sheet.  *Optional:* If none of your scores are **14** or higher, you may discard the set and roll a new six scores.


:::{#tbl-ability-modifiers}
+-------------------+-------------------+
| **Ability Score** | **Modifier**      |
+:=================:+:=================:+
| 1-3               | -4                |
+-------------------+-------------------+
| 4-5               | -3                |
+-------------------+-------------------+
| 6-7               | -2                |
+-------------------+-------------------+
| 8-9               | -1                |
+-------------------+-------------------+
| 10-11             | 0                 |
+-------------------+-------------------+
| 12-13             | +1                |
+-------------------+-------------------+
| 14-15             | +2                |
+-------------------+-------------------+
| 16-17             | +3                |
+-------------------+-------------------+
| 18+               | +4                |
+-------------------+-------------------+
:::
:::{.table-caption}
**Table:** Ability Modifiers
:::

**Strength:** Raw physical power. Apply the Strength modifier to all melee attack rolls. See [Combat](../combatDetails.qmd#damage) for details.  

**Dexterity:** Quickness, balance, and deft hands. Apply the Dexterity modifier to all ranged **attack rolls**, to [Armor Class](09-Equipment.qmd#armor-and-shields), and to [Intiative](../combatDetails.qmd#initiative).  

**Constitution:** Health and vitality. Apply the Constitution modifier to each **hit die** you roll (a penalty never reduces a hit-die roll below 1).  

**Intelligence:** Learning and lore. Important to [Magic-Users](05-Classes.qmd#magic-users), who gain a **Spell Bonus** from Intelligence.  

**Wisdom:** Will, insight, and common sense. Primary for [Clerics](05-Classes.qmd#cleric), who gain a **Spell Bonus** from Wisdom. Wisdom may also modify certain saving DCs against mind-affecting magic.  

**Charisma:** Presence and leadership. Apply the Charisma modifier to **reaction rolls**; it also affects the number and loyalty of [Hirelings](../hirelings.qmd#retainers-and-hirelings).

---


#### Stat Roller

```{ojs}
import { rollAbilityScore } from "../custom.js"

viewof statRolls = Inputs.button(html`<button style="color: black; background-color: lightgray;">Roll Stats</button>`, {value: null, reduce: () => [rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore(),rollAbilityScore()]})

```


```{ojs}
import { calculateModifier } from "../custom.js"
{
    var x = ""
    if (statRolls != null) {
        x = html`<br><table style="max-width:20%;">
                    <tr>
                        <th>Roll:</th>
                        <th>Modifier:</th>
                    </tr>
                    <tr>
                        <td>${statRolls[0]}</td>
                        <td>(${calculateModifier(statRolls[0])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[1]}</td>
                        <td>(${calculateModifier(statRolls[1])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[2]}</td>
                        <td>(${calculateModifier(statRolls[2])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[3]}</td>
                        <td>(${calculateModifier(statRolls[3])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[4]}</td>
                        <td>(${calculateModifier(statRolls[4])})</td>
                    </tr>
                    <tr>
                        <td>${statRolls[5]}</td>
                        <td>(${calculateModifier(statRolls[5])})</td>
                    </tr>
                `
    } else {x = md`<br><b>Press button to roll stats<b>`}

    return x
    } 

```