# Level Advancement

## Experience Points

XP represents your learning, influence, and increasing skill. XP awards are based on the quality of the treasure and boons you gain during a session.  DMs should see [Awarding XP guidance](../Awarding-XP.qmd). The DM can award XP right away or at the end of each session.


## Leveling Up

To gain a level, you need to earn your current level x 10 XP. Once you reach a new level, your total XP resets back to zero. You get any new title, spells, and talent improvements listed for your level. Your maximum HP increases, and you might also gain a talent roll.

:::{#level-talent-table}
| **Level** | **Talent** | **Level Up At…** |
|:--------:|:-----------|:------------------|
| 1        | +1         | 10 XP             |
| 2        | -          | 20 XP             |
| 3        | +1         | 30 XP             |
| 4        | -          | 40 XP             |
| 5        | +1         | 50 XP             |
| 6        | -          | 60 XP             |
| 7        | +1         | 70 XP             |
| 8        | -          | 80 XP             |
| 9        | +1         | 90 XP             |
| 10       | -          | 100 XP            |
:::
:::{.table-caption}
**Table:** Level Progression and Talents
:::

## Talent Roll
You gain one roll on your class's talent table when you reach the indicated levels. Duplicate talents stack unless noted.

## Hit Points
Roll your class's hit points die and add it to your maximum HP
