# Languages

There are twelve languages in the OnceWas:

1. Common
2. Ancient Tongue (from the Age of Dragons, before the Age of Man)
3. Elvish or Sylvan
4. Dwarven or Underspeak
5. Northern or the Cold Tongue
6. Sunndi or the Desert Tongue
7. Orkish (goblins, bugbears, gnolls, etc. all speak this)
8. Draconic (dragons, lizardmen, kobolds, etc. all speak this)
9. Abysmal or Demonic
10. Arcane or Magic Tongue
11. Thieve’s Cant or Thieve’s Tongue
12. Druidic

- All characters speak Common.
- Elves and Dwarves know their language as well.
- Magic-Users will know Arcane.
- Thieves will know Thieve's Cant.

Characters with Intelligence of 13 or higher may choose to begin the game knowing one or more languages other than those given above; the number of additional languages that may be learned is equal to the [Intelligence bonus](03-Abilities.qmd#ability-scores) (+1, +2, or +3).

Characters may choose to learn other demi-human languages, as well as humanoid languages such as Orkish, etc. The DM will decide which humanoid languages may be learned. The player may choose to leave one or more bonus language "slots" open, to be filled during play.

Some Game Masters may even allow player characters to learn exotic languages such as Draconic; also, "dead" or otherwise archaic languages might be allowed to more scholarly characters.
